-- CreateEnum
CREATE TYPE "Symbol" AS ENUM ('DREHLEITER', 'HEBEGERAET', 'BAGGER', 'RAEUMGERAET', 'BRUECKE', 'SPRENGMITTEL', 'BELEUCHTUNG', 'BETT', 'VERPFLEGUNG', 'VERBRAUCHSGUETER', 'TRINKWASSER', 'BRAUCHWASSER', 'ELEKTRIZITAET', 'GERAETE', 'SPRENGUNG', 'BERGUNG', 'TRANSPORT', 'FAHRZEUG', 'FAHRRAD', 'KRAFTRAD', 'FLUGZEUG', 'HUBSCHRAUBER', 'ENTSTEHUNGSBRAND', 'FORTENTWICKELTER_BRAND', 'VOLLBRAND', 'SIRENE', 'LAUTSPRECHER', 'WARNUNG', 'ZELT', 'SICHTEN', 'SAMMELN', 'SAMMELPLATZ_BETROFFENE', 'VETERINAERWESEN', 'SCHLACHTEN', 'TIER_VERLETZT', 'TIER_TOT', 'PERSON', 'PERSON_VERLETZT', 'PERSON_TOT', 'PERSON_VERMISST', 'PERSON_VERSCHUETTET', 'PERSON_GERETTET', 'PERSON_ZU_TRANSPORTIEREN', 'PERSON_TRANSPORTIERT', 'BESCHAEDIGT', 'TEILZERSTOERT', 'ZERSTOERT', 'TEILBLOCKIERT', 'BLOCKIERT', 'TENDENZ_STEIGEND', 'TENDENZ_FALLEND', 'TENDENZ_UNVERAENDERT', 'AUSFALL_25', 'AUSFALL_50', 'AUSFALL_75', 'AUSFALL_100', 'ABC', 'DEKONTAMINATION', 'DEKONTAMINATION_PERSONEN', 'DEKONTAMINATION_GERAETE', 'WASSER', 'WASSERFAHRZEUG', 'PUMPE', 'BILDUEBERTRAGUNG', 'BILDUEBERTRAGUNG_FUNK', 'DATENUEBERTRAGUNG', 'DATENUEBERTRAGUNG_FUNK', 'FAX', 'FAX_FUNK', 'FERNSPRECHEN', 'FERNSPRECHEN_FUNK', 'FERNSCHREIBEN', 'FERNSCHREIBEN_FUNK', 'FESTBILDUEBERTRAGUNG', 'FESTBILDUEBERTRAGUNG_FUNK', 'RELAISFUNKBETRIEB', 'RICHTBETRIEB', 'KABELBAU', 'VERMUTUNG', 'AKUT', 'TECHNISCHE_HILFELEISTUNG', 'SEELSORGE', 'DROHNE');

-- AlterTable
ALTER TABLE "optaFunktion"
    ADD COLUMN "symbol" "Symbol";

UPDATE "optaFunktion"
SET symbol = CASE
                 WHEN "optaCode" = 0 THEN 'FERNSPRECHEN_FUNK'::"Symbol"
                 WHEN "optaCode" = 7 THEN 'PERSON'::"Symbol"
                 WHEN "optaCode" = 8 THEN 'PERSON'::"Symbol"
                 WHEN "optaCode" = 9 THEN 'PERSON'::"Symbol"
                 WHEN "optaCode" = 10 THEN 'FAHRZEUG'::"Symbol"
                 WHEN "optaCode" = 11 THEN 'DATENUEBERTRAGUNG'::"Symbol"
                 WHEN "optaCode" = 12 THEN 'DATENUEBERTRAGUNG'::"Symbol"
                 WHEN "optaCode" = 14 THEN 'DATENUEBERTRAGUNG_FUNK'::"Symbol"
                 WHEN "optaCode" = 15 THEN 'DROHNE'::"Symbol"
                 WHEN "optaCode" = 16 THEN 'VERPFLEGUNG'::"Symbol"
                 WHEN "optaCode" = 59 THEN 'GERAETE'::"Symbol"
                 WHEN "optaCode" = 60 THEN 'VERBRAUCHSGUETER'::"Symbol"
                 WHEN "optaCode" = 61 THEN 'WASSER'::"Symbol"
                 WHEN "optaCode" = 62 THEN 'WASSER'::"Symbol"
                 WHEN "optaCode" = 67 THEN 'HEBEGERAET'::"Symbol"
                 WHEN "optaCode" = 74 THEN 'GERAETE'::"Symbol"
                 WHEN "optaCode" = 76 THEN 'VERPFLEGUNG'::"Symbol"
                 WHEN "optaCode" = 80 THEN 'HUBSCHRAUBER'::"Symbol"
                 WHEN "optaCode" = 90 THEN 'SICHTEN'::"Symbol"
                 WHEN "optaCode" = 95 THEN 'SICHTEN'::"Symbol"
                 WHEN "optaCode" = 96 THEN 'PERSON_VERLETZT'::"Symbol"
                 WHEN "optaCode" = 97 THEN 'ABC'::"Symbol"
    END
WHERE "optaCode" IN (0, 7, 8, 9, 10, 11, 12, 14, 15, 16, 59, 60, 61, 62, 67, 74, 76, 80, 90, 95, 96, 97);
