services:
  postgres:
    image: postgres:13
    ports:
      - "9901:5432"
    networks:
      internal:
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-project-rescue}
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    image: ghcr.io/rubenvitt/project-rescue:release
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "9900:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://user:password@postgres:5432/project-rescue}
      SERVER_NAME: ${SERVER_NAME}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      AUTH_TOKEN: ${AUTH_TOKEN}
    networks:
      internal:
      proxy-net:
        aliases:
          - ember-rescue
    env_file:
      - .env
    depends_on:
      - postgres

networks:
  internal:
  proxy-net:
    external: true

volumes:
  postgres: