/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface BearbeiterCoreControllerFindOneV1Request {
  name: string;
}

export interface BearbeiterCoreControllerLoginV1Request {
  body: object;
}

/**
 *
 */
export class BearbeiterCoreApi extends runtime.BaseAPI {
  /**
   */
  async bearbeiterCoreControllerFindAllV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/users`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async bearbeiterCoreControllerFindAllV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.bearbeiterCoreControllerFindAllV1Raw(initOverrides);
  }

  /**
   */
  async bearbeiterCoreControllerFindOneV1Raw(
    requestParameters: BearbeiterCoreControllerFindOneV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['name'] == null) {
      throw new runtime.RequiredError(
        'name',
        'Required parameter "name" was null or undefined when calling bearbeiterCoreControllerFindOneV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/users/{name}`.replace(`{${'name'}}`, encodeURIComponent(String(requestParameters['name']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async bearbeiterCoreControllerFindOneV1(
    requestParameters: BearbeiterCoreControllerFindOneV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.bearbeiterCoreControllerFindOneV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async bearbeiterCoreControllerLoginV1Raw(
    requestParameters: BearbeiterCoreControllerLoginV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['body'] == null) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling bearbeiterCoreControllerLoginV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/users`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['body'] as any,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async bearbeiterCoreControllerLoginV1(
    requestParameters: BearbeiterCoreControllerLoginV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.bearbeiterCoreControllerLoginV1Raw(requestParameters, initOverrides);
  }
}
