/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface EinsatzCoreControllerChangeEinsatzV1Request {
  id: string;
  bearbeiter: string;
}

export interface EinsatzCoreControllerCloseEinsatzV1Request {
  bearbeiter: string;
  id: string;
}

export interface EinsatzCoreControllerGetEinsaetzeV1Request {
  abgeschlossen: boolean;
}

export interface EinsatzCoreControllerGetEinsatzV1Request {
  id: string;
}

/**
 *
 */
export class EinsatzCoreApi extends runtime.BaseAPI {
  /**
   */
  async einsatzCoreControllerChangeEinsatzV1Raw(
    requestParameters: EinsatzCoreControllerChangeEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling einsatzCoreControllerChangeEinsatzV1().',
      );
    }

    if (requestParameters['bearbeiter'] == null) {
      throw new runtime.RequiredError(
        'bearbeiter',
        'Required parameter "bearbeiter" was null or undefined when calling einsatzCoreControllerChangeEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters['bearbeiter'] != null) {
      headerParameters['bearbeiter'] = String(requestParameters['bearbeiter']);
    }

    const response = await this.request(
      {
        path: `/v1/missions/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzCoreControllerChangeEinsatzV1(
    requestParameters: EinsatzCoreControllerChangeEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzCoreControllerChangeEinsatzV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async einsatzCoreControllerCloseEinsatzV1Raw(
    requestParameters: EinsatzCoreControllerCloseEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['bearbeiter'] == null) {
      throw new runtime.RequiredError(
        'bearbeiter',
        'Required parameter "bearbeiter" was null or undefined when calling einsatzCoreControllerCloseEinsatzV1().',
      );
    }

    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling einsatzCoreControllerCloseEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters['bearbeiter'] != null) {
      headerParameters['bearbeiter'] = String(requestParameters['bearbeiter']);
    }

    const response = await this.request(
      {
        path: `/v1/missions/{id}/close`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzCoreControllerCloseEinsatzV1(
    requestParameters: EinsatzCoreControllerCloseEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzCoreControllerCloseEinsatzV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async einsatzCoreControllerCreateEinsatzV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzCoreControllerCreateEinsatzV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzCoreControllerCreateEinsatzV1Raw(initOverrides);
  }

  /**
   */
  async einsatzCoreControllerGetEinsaetzeV1Raw(
    requestParameters: EinsatzCoreControllerGetEinsaetzeV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['abgeschlossen'] == null) {
      throw new runtime.RequiredError(
        'abgeschlossen',
        'Required parameter "abgeschlossen" was null or undefined when calling einsatzCoreControllerGetEinsaetzeV1().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['abgeschlossen'] != null) {
      queryParameters['abgeschlossen'] = requestParameters['abgeschlossen'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzCoreControllerGetEinsaetzeV1(
    requestParameters: EinsatzCoreControllerGetEinsaetzeV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzCoreControllerGetEinsaetzeV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async einsatzCoreControllerGetEinsatzV1Raw(
    requestParameters: EinsatzCoreControllerGetEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling einsatzCoreControllerGetEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzCoreControllerGetEinsatzV1(
    requestParameters: EinsatzCoreControllerGetEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzCoreControllerGetEinsatzV1Raw(requestParameters, initOverrides);
  }
}
