/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ManyEinsatzAlarmstichwortDto } from '../models/index';
import { ManyEinsatzAlarmstichwortDtoFromJSON, ManyEinsatzAlarmstichwortDtoToJSON } from '../models/index';

/**
 *
 */
export class AlarmstichwortApi extends runtime.BaseAPI {
  /**
   */
  async alarmstichwortControllerGetAlarmstichworteV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyEinsatzAlarmstichwortDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/alarmstichwort`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyEinsatzAlarmstichwortDtoFromJSON(jsonValue));
  }

  /**
   */
  async alarmstichwortControllerGetAlarmstichworteV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyEinsatzAlarmstichwortDto> {
    const response = await this.alarmstichwortControllerGetAlarmstichworteV1Raw(initOverrides);
    return await response.value();
  }
}
