/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateBearbeiterDto, ManyBearbeiterResponse, OneBearbeiterResponse } from '../models/index';
import {
  CreateBearbeiterDtoFromJSON,
  CreateBearbeiterDtoToJSON,
  ManyBearbeiterResponseFromJSON,
  ManyBearbeiterResponseToJSON,
  OneBearbeiterResponseFromJSON,
  OneBearbeiterResponseToJSON,
} from '../models/index';

export interface BearbeiterCoreControllerFindOneV1Request {
  name: string;
}

export interface BearbeiterCoreControllerLoginV1Request {
  createBearbeiterDto: CreateBearbeiterDto;
}

/**
 *
 */
export class BearbeiterCoreApi extends runtime.BaseAPI {
  /**
   */
  async bearbeiterCoreControllerFindAllV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyBearbeiterResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/users`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyBearbeiterResponseFromJSON(jsonValue));
  }

  /**
   */
  async bearbeiterCoreControllerFindAllV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyBearbeiterResponse> {
    const response = await this.bearbeiterCoreControllerFindAllV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async bearbeiterCoreControllerFindOneV1Raw(
    requestParameters: BearbeiterCoreControllerFindOneV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<OneBearbeiterResponse>> {
    if (requestParameters['name'] == null) {
      throw new runtime.RequiredError(
        'name',
        'Required parameter "name" was null or undefined when calling bearbeiterCoreControllerFindOneV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/users/{name}`.replace(`{${'name'}}`, encodeURIComponent(String(requestParameters['name']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OneBearbeiterResponseFromJSON(jsonValue));
  }

  /**
   */
  async bearbeiterCoreControllerFindOneV1(
    requestParameters: BearbeiterCoreControllerFindOneV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<OneBearbeiterResponse> {
    const response = await this.bearbeiterCoreControllerFindOneV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async bearbeiterCoreControllerLoginV1Raw(
    requestParameters: BearbeiterCoreControllerLoginV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<OneBearbeiterResponse>> {
    if (requestParameters['createBearbeiterDto'] == null) {
      throw new runtime.RequiredError(
        'createBearbeiterDto',
        'Required parameter "createBearbeiterDto" was null or undefined when calling bearbeiterCoreControllerLoginV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/users`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateBearbeiterDtoToJSON(requestParameters['createBearbeiterDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OneBearbeiterResponseFromJSON(jsonValue));
  }

  /**
   */
  async bearbeiterCoreControllerLoginV1(
    requestParameters: BearbeiterCoreControllerLoginV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<OneBearbeiterResponse> {
    const response = await this.bearbeiterCoreControllerLoginV1Raw(requestParameters, initOverrides);
    return await response.value();
  }
}
