/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { AddVehicleToMissionDto, ChangeStatusDto, VehiclesResponse } from '../models/index';
import {
  AddVehicleToMissionDtoFromJSON,
  AddVehicleToMissionDtoToJSON,
  ChangeStatusDtoFromJSON,
  ChangeStatusDtoToJSON,
  VehiclesResponseFromJSON,
  VehiclesResponseToJSON,
} from '../models/index';

export interface EinsatzFahrzeugeControllerAddFahrzeugToEinsatzV1Request {
  einsatzId: string;
  addVehicleToMissionDto: AddVehicleToMissionDto;
}

export interface EinsatzFahrzeugeControllerChangeStatusV1Request {
  einsatzId: string;
  fullOpta: string;
  changeStatusDto: ChangeStatusDto;
}

export interface EinsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1Request {
  einsatzId: string;
}

export interface EinsatzFahrzeugeControllerRemoveFromEinsatzV1Request {
  einsatzId: string;
  fullOpta: string;
}

/**
 *
 */
export class EinsatzFahrzeugeApi extends runtime.BaseAPI {
  /**
   */
  async einsatzFahrzeugeControllerAddFahrzeugToEinsatzV1Raw(
    requestParameters: EinsatzFahrzeugeControllerAddFahrzeugToEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling einsatzFahrzeugeControllerAddFahrzeugToEinsatzV1().',
      );
    }

    if (requestParameters['addVehicleToMissionDto'] == null) {
      throw new runtime.RequiredError(
        'addVehicleToMissionDto',
        'Required parameter "addVehicleToMissionDto" was null or undefined when calling einsatzFahrzeugeControllerAddFahrzeugToEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/missions/{einsatzId}/vehicles/add`.replace(
          `{${'einsatzId'}}`,
          encodeURIComponent(String(requestParameters['einsatzId'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: AddVehicleToMissionDtoToJSON(requestParameters['addVehicleToMissionDto']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzFahrzeugeControllerAddFahrzeugToEinsatzV1(
    requestParameters: EinsatzFahrzeugeControllerAddFahrzeugToEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzFahrzeugeControllerAddFahrzeugToEinsatzV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async einsatzFahrzeugeControllerChangeStatusV1Raw(
    requestParameters: EinsatzFahrzeugeControllerChangeStatusV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling einsatzFahrzeugeControllerChangeStatusV1().',
      );
    }

    if (requestParameters['fullOpta'] == null) {
      throw new runtime.RequiredError(
        'fullOpta',
        'Required parameter "fullOpta" was null or undefined when calling einsatzFahrzeugeControllerChangeStatusV1().',
      );
    }

    if (requestParameters['changeStatusDto'] == null) {
      throw new runtime.RequiredError(
        'changeStatusDto',
        'Required parameter "changeStatusDto" was null or undefined when calling einsatzFahrzeugeControllerChangeStatusV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/missions/{einsatzId}/vehicles/{fullOpta}/status`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'fullOpta'}}`, encodeURIComponent(String(requestParameters['fullOpta']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChangeStatusDtoToJSON(requestParameters['changeStatusDto']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzFahrzeugeControllerChangeStatusV1(
    requestParameters: EinsatzFahrzeugeControllerChangeStatusV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzFahrzeugeControllerChangeStatusV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async einsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1Raw(
    requestParameters: EinsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<VehiclesResponse>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling einsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{einsatzId}/vehicles`.replace(
          `{${'einsatzId'}}`,
          encodeURIComponent(String(requestParameters['einsatzId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => VehiclesResponseFromJSON(jsonValue));
  }

  /**
   */
  async einsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1(
    requestParameters: EinsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<VehiclesResponse> {
    const response = await this.einsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async einsatzFahrzeugeControllerRemoveFromEinsatzV1Raw(
    requestParameters: EinsatzFahrzeugeControllerRemoveFromEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling einsatzFahrzeugeControllerRemoveFromEinsatzV1().',
      );
    }

    if (requestParameters['fullOpta'] == null) {
      throw new runtime.RequiredError(
        'fullOpta',
        'Required parameter "fullOpta" was null or undefined when calling einsatzFahrzeugeControllerRemoveFromEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{einsatzId}/vehicles/{fullOpta}`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'fullOpta'}}`, encodeURIComponent(String(requestParameters['fullOpta']))),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzFahrzeugeControllerRemoveFromEinsatzV1(
    requestParameters: EinsatzFahrzeugeControllerRemoveFromEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzFahrzeugeControllerRemoveFromEinsatzV1Raw(requestParameters, initOverrides);
  }
}
