/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateEinsatztagebuchDto } from '../models/index';
import { CreateEinsatztagebuchDtoFromJSON, CreateEinsatztagebuchDtoToJSON } from '../models/index';

export interface EinsatztagebuchControllerArchiveEinsatztagebuchEintragV1Request {
  id: string;
  missionId: string;
}

export interface EinsatztagebuchControllerCreateEinsatztagebuchEintragV1Request {
  missionId: string;
  createEinsatztagebuchDto: CreateEinsatztagebuchDto;
}

export interface EinsatztagebuchControllerGetEinsatztagebuchV1Request {
  bearbeiter: string;
  missionId: string;
}

/**
 *
 */
export class EinsatztagebuchApi extends runtime.BaseAPI {
  /**
   */
  async einsatztagebuchControllerArchiveEinsatztagebuchEintragV1Raw(
    requestParameters: EinsatztagebuchControllerArchiveEinsatztagebuchEintragV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling einsatztagebuchControllerArchiveEinsatztagebuchEintragV1().',
      );
    }

    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling einsatztagebuchControllerArchiveEinsatztagebuchEintragV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/journal/{id}/archive`
          .replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))
          .replace(`{${'missionId'}}`, encodeURIComponent(String(requestParameters['missionId']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatztagebuchControllerArchiveEinsatztagebuchEintragV1(
    requestParameters: EinsatztagebuchControllerArchiveEinsatztagebuchEintragV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatztagebuchControllerArchiveEinsatztagebuchEintragV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async einsatztagebuchControllerCreateEinsatztagebuchEintragV1Raw(
    requestParameters: EinsatztagebuchControllerCreateEinsatztagebuchEintragV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling einsatztagebuchControllerCreateEinsatztagebuchEintragV1().',
      );
    }

    if (requestParameters['createEinsatztagebuchDto'] == null) {
      throw new runtime.RequiredError(
        'createEinsatztagebuchDto',
        'Required parameter "createEinsatztagebuchDto" was null or undefined when calling einsatztagebuchControllerCreateEinsatztagebuchEintragV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/journal`.replace(
          `{${'missionId'}}`,
          encodeURIComponent(String(requestParameters['missionId'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateEinsatztagebuchDtoToJSON(requestParameters['createEinsatztagebuchDto']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatztagebuchControllerCreateEinsatztagebuchEintragV1(
    requestParameters: EinsatztagebuchControllerCreateEinsatztagebuchEintragV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatztagebuchControllerCreateEinsatztagebuchEintragV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async einsatztagebuchControllerGetEinsatztagebuchV1Raw(
    requestParameters: EinsatztagebuchControllerGetEinsatztagebuchV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['bearbeiter'] == null) {
      throw new runtime.RequiredError(
        'bearbeiter',
        'Required parameter "bearbeiter" was null or undefined when calling einsatztagebuchControllerGetEinsatztagebuchV1().',
      );
    }

    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling einsatztagebuchControllerGetEinsatztagebuchV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters['bearbeiter'] != null) {
      headerParameters['bearbeiter'] = String(requestParameters['bearbeiter']);
    }

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/journal`.replace(
          `{${'missionId'}}`,
          encodeURIComponent(String(requestParameters['missionId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatztagebuchControllerGetEinsatztagebuchV1(
    requestParameters: EinsatztagebuchControllerGetEinsatztagebuchV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatztagebuchControllerGetEinsatztagebuchV1Raw(requestParameters, initOverrides);
  }
}
