/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface EinsatzFahrzeugeControllerAddFahrzeugToEinsatzV1Request {
  einsatzId: string;
}

export interface EinsatzFahrzeugeControllerChangeStatusV1Request {
  einsatzId: string;
  fahrzeugId: string;
}

export interface EinsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1Request {
  einsatzId: string;
}

export interface EinsatzFahrzeugeControllerRemoveFromEinsatzV1Request {
  einsatzId: string;
  fahrzeugId: string;
}

/**
 *
 */
export class EinsatzFahrzeugeApi extends runtime.BaseAPI {
  /**
   */
  async einsatzFahrzeugeControllerAddFahrzeugToEinsatzV1Raw(
    requestParameters: EinsatzFahrzeugeControllerAddFahrzeugToEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling einsatzFahrzeugeControllerAddFahrzeugToEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{einsatzId}/vehicles/add`.replace(
          `{${'einsatzId'}}`,
          encodeURIComponent(String(requestParameters['einsatzId'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzFahrzeugeControllerAddFahrzeugToEinsatzV1(
    requestParameters: EinsatzFahrzeugeControllerAddFahrzeugToEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzFahrzeugeControllerAddFahrzeugToEinsatzV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async einsatzFahrzeugeControllerChangeStatusV1Raw(
    requestParameters: EinsatzFahrzeugeControllerChangeStatusV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling einsatzFahrzeugeControllerChangeStatusV1().',
      );
    }

    if (requestParameters['fahrzeugId'] == null) {
      throw new runtime.RequiredError(
        'fahrzeugId',
        'Required parameter "fahrzeugId" was null or undefined when calling einsatzFahrzeugeControllerChangeStatusV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{einsatzId}/vehicles/{fahrzeugId}/status`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'fahrzeugId'}}`, encodeURIComponent(String(requestParameters['fahrzeugId']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzFahrzeugeControllerChangeStatusV1(
    requestParameters: EinsatzFahrzeugeControllerChangeStatusV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzFahrzeugeControllerChangeStatusV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async einsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1Raw(
    requestParameters: EinsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling einsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{einsatzId}/vehicles`.replace(
          `{${'einsatzId'}}`,
          encodeURIComponent(String(requestParameters['einsatzId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1(
    requestParameters: EinsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzFahrzeugeControllerFindFahrzeugeImEinsatzV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async einsatzFahrzeugeControllerRemoveFromEinsatzV1Raw(
    requestParameters: EinsatzFahrzeugeControllerRemoveFromEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling einsatzFahrzeugeControllerRemoveFromEinsatzV1().',
      );
    }

    if (requestParameters['fahrzeugId'] == null) {
      throw new runtime.RequiredError(
        'fahrzeugId',
        'Required parameter "fahrzeugId" was null or undefined when calling einsatzFahrzeugeControllerRemoveFromEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{einsatzId}/vehicles/{fahrzeugId}`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'fahrzeugId'}}`, encodeURIComponent(String(requestParameters['fahrzeugId']))),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async einsatzFahrzeugeControllerRemoveFromEinsatzV1(
    requestParameters: EinsatzFahrzeugeControllerRemoveFromEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.einsatzFahrzeugeControllerRemoveFromEinsatzV1Raw(requestParameters, initOverrides);
  }
}
