/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface ExportControllerCreateExportPdfV1Request {
  einsatz: string;
}

/**
 *
 */
export class ExportApi extends runtime.BaseAPI {
  /**
   */
  async exportControllerCreateExportPdfV1Raw(
    requestParameters: ExportControllerCreateExportPdfV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatz'] == null) {
      throw new runtime.RequiredError(
        'einsatz',
        'Required parameter "einsatz" was null or undefined when calling exportControllerCreateExportPdfV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters['einsatz'] != null) {
      headerParameters['einsatz'] = String(requestParameters['einsatz']);
    }

    const response = await this.request(
      {
        path: `/v1/features/export/pdf`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async exportControllerCreateExportPdfV1(
    requestParameters: ExportControllerCreateExportPdfV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.exportControllerCreateExportPdfV1Raw(requestParameters, initOverrides);
  }
}
