/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface FahrzeugeControllerImportFahrzeugeV1Request {
  requestBody: Array<string>;
}

export interface FahrzeugeControllerUpdateManyV1Request {
  requestBody: Array<string>;
}

/**
 *
 */
export class FahrzeugeApi extends runtime.BaseAPI {
  /**
   */
  async fahrzeugeControllerExportFahrzeugeV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/vehicles/export`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async fahrzeugeControllerExportFahrzeugeV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.fahrzeugeControllerExportFahrzeugeV1Raw(initOverrides);
  }

  /**
   */
  async fahrzeugeControllerFindAllTypenV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/vehicles/typen`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async fahrzeugeControllerFindAllTypenV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.fahrzeugeControllerFindAllTypenV1Raw(initOverrides);
  }

  /**
   */
  async fahrzeugeControllerFindAllV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/vehicles`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async fahrzeugeControllerFindAllV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.fahrzeugeControllerFindAllV1Raw(initOverrides);
  }

  /**
   */
  async fahrzeugeControllerGetImportSchemaV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/vehicles/import/schema/v2`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async fahrzeugeControllerGetImportSchemaV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.fahrzeugeControllerGetImportSchemaV1Raw(initOverrides);
  }

  /**
   */
  async fahrzeugeControllerImportFahrzeugeV1Raw(
    requestParameters: FahrzeugeControllerImportFahrzeugeV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['requestBody'] == null) {
      throw new runtime.RequiredError(
        'requestBody',
        'Required parameter "requestBody" was null or undefined when calling fahrzeugeControllerImportFahrzeugeV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/templates/vehicles/import`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['requestBody'],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async fahrzeugeControllerImportFahrzeugeV1(
    requestParameters: FahrzeugeControllerImportFahrzeugeV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.fahrzeugeControllerImportFahrzeugeV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async fahrzeugeControllerUpdateManyV1Raw(
    requestParameters: FahrzeugeControllerUpdateManyV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['requestBody'] == null) {
      throw new runtime.RequiredError(
        'requestBody',
        'Required parameter "requestBody" was null or undefined when calling fahrzeugeControllerUpdateManyV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/templates/vehicles`,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['requestBody'],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async fahrzeugeControllerUpdateManyV1(
    requestParameters: FahrzeugeControllerUpdateManyV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.fahrzeugeControllerUpdateManyV1Raw(requestParameters, initOverrides);
  }
}
