/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateJournalEntryDto, JournalEntryResponse, JournalResponse } from '../models/index';
import {
  CreateJournalEntryDtoFromJSON,
  CreateJournalEntryDtoToJSON,
  JournalEntryResponseFromJSON,
  JournalEntryResponseToJSON,
  JournalResponseFromJSON,
  JournalResponseToJSON,
} from '../models/index';

export interface JournalControllerArchiveJournalEntryV1Request {
  id: string;
  missionId: string;
}

export interface JournalControllerCreateJournalEntryV1Request {
  missionId: string;
  createJournalEntryDto: CreateJournalEntryDto;
}

export interface JournalControllerGetJournalV1Request {
  missionId: string;
}

/**
 *
 */
export class JournalApi extends runtime.BaseAPI {
  /**
   */
  async journalControllerArchiveJournalEntryV1Raw(
    requestParameters: JournalControllerArchiveJournalEntryV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling journalControllerArchiveJournalEntryV1().',
      );
    }

    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling journalControllerArchiveJournalEntryV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/journal/{id}/archive`
          .replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])))
          .replace(`{${'missionId'}}`, encodeURIComponent(String(requestParameters['missionId']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async journalControllerArchiveJournalEntryV1(
    requestParameters: JournalControllerArchiveJournalEntryV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.journalControllerArchiveJournalEntryV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async journalControllerCreateJournalEntryV1Raw(
    requestParameters: JournalControllerCreateJournalEntryV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<JournalEntryResponse>> {
    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling journalControllerCreateJournalEntryV1().',
      );
    }

    if (requestParameters['createJournalEntryDto'] == null) {
      throw new runtime.RequiredError(
        'createJournalEntryDto',
        'Required parameter "createJournalEntryDto" was null or undefined when calling journalControllerCreateJournalEntryV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/journal`.replace(
          `{${'missionId'}}`,
          encodeURIComponent(String(requestParameters['missionId'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateJournalEntryDtoToJSON(requestParameters['createJournalEntryDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => JournalEntryResponseFromJSON(jsonValue));
  }

  /**
   */
  async journalControllerCreateJournalEntryV1(
    requestParameters: JournalControllerCreateJournalEntryV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<JournalEntryResponse> {
    const response = await this.journalControllerCreateJournalEntryV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async journalControllerGetJournalV1Raw(
    requestParameters: JournalControllerGetJournalV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<JournalResponse>> {
    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling journalControllerGetJournalV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/journal`.replace(
          `{${'missionId'}}`,
          encodeURIComponent(String(requestParameters['missionId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => JournalResponseFromJSON(jsonValue));
  }

  /**
   */
  async journalControllerGetJournalV1(
    requestParameters: JournalControllerGetJournalV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<JournalResponse> {
    const response = await this.journalControllerGetJournalV1Raw(requestParameters, initOverrides);
    return await response.value();
  }
}
