/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { MetaResponse } from '../models/index';
import { MetaResponseFromJSON, MetaResponseToJSON } from '../models/index';

/**
 *
 */
export class MetaApi extends runtime.BaseAPI {
  /**
   */
  async metaControllerGetMetaV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<MetaResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/core/meta`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => MetaResponseFromJSON(jsonValue));
  }

  /**
   */
  async metaControllerGetMetaV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetaResponse> {
    const response = await this.metaControllerGetMetaV1Raw(initOverrides);
    return await response.value();
  }
}
