/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateMissionDto, ManyMissionsResponse, OneMissionResponse, UpdateMissionDto } from '../models/index';
import {
  CreateMissionDtoFromJSON,
  CreateMissionDtoToJSON,
  ManyMissionsResponseFromJSON,
  ManyMissionsResponseToJSON,
  OneMissionResponseFromJSON,
  OneMissionResponseToJSON,
  UpdateMissionDtoFromJSON,
  UpdateMissionDtoToJSON,
} from '../models/index';

export interface MissionCoreControllerChangeEinsatzV1Request {
  id: string;
  updateMissionDto: UpdateMissionDto;
}

export interface MissionCoreControllerCloseEinsatzV1Request {
  id: string;
}

export interface MissionCoreControllerCreateEinsatzV1Request {
  createMissionDto: CreateMissionDto;
}

export interface MissionCoreControllerGetMissionV1Request {
  id: string;
}

export interface MissionCoreControllerGetMissionsV1Request {
  abgeschlossen?: boolean;
}

/**
 *
 */
export class MissionCoreApi extends runtime.BaseAPI {
  /**
   */
  async missionCoreControllerChangeEinsatzV1Raw(
    requestParameters: MissionCoreControllerChangeEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<OneMissionResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling missionCoreControllerChangeEinsatzV1().',
      );
    }

    if (requestParameters['updateMissionDto'] == null) {
      throw new runtime.RequiredError(
        'updateMissionDto',
        'Required parameter "updateMissionDto" was null or undefined when calling missionCoreControllerChangeEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/missions/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateMissionDtoToJSON(requestParameters['updateMissionDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OneMissionResponseFromJSON(jsonValue));
  }

  /**
   */
  async missionCoreControllerChangeEinsatzV1(
    requestParameters: MissionCoreControllerChangeEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<OneMissionResponse> {
    const response = await this.missionCoreControllerChangeEinsatzV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async missionCoreControllerCloseEinsatzV1Raw(
    requestParameters: MissionCoreControllerCloseEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<OneMissionResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling missionCoreControllerCloseEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{id}/close`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OneMissionResponseFromJSON(jsonValue));
  }

  /**
   */
  async missionCoreControllerCloseEinsatzV1(
    requestParameters: MissionCoreControllerCloseEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<OneMissionResponse> {
    const response = await this.missionCoreControllerCloseEinsatzV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async missionCoreControllerCreateEinsatzV1Raw(
    requestParameters: MissionCoreControllerCreateEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<OneMissionResponse>> {
    if (requestParameters['createMissionDto'] == null) {
      throw new runtime.RequiredError(
        'createMissionDto',
        'Required parameter "createMissionDto" was null or undefined when calling missionCoreControllerCreateEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/missions`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateMissionDtoToJSON(requestParameters['createMissionDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OneMissionResponseFromJSON(jsonValue));
  }

  /**
   */
  async missionCoreControllerCreateEinsatzV1(
    requestParameters: MissionCoreControllerCreateEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<OneMissionResponse> {
    const response = await this.missionCoreControllerCreateEinsatzV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async missionCoreControllerGetMissionV1Raw(
    requestParameters: MissionCoreControllerGetMissionV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<OneMissionResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling missionCoreControllerGetMissionV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OneMissionResponseFromJSON(jsonValue));
  }

  /**
   */
  async missionCoreControllerGetMissionV1(
    requestParameters: MissionCoreControllerGetMissionV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<OneMissionResponse> {
    const response = await this.missionCoreControllerGetMissionV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async missionCoreControllerGetMissionsV1Raw(
    requestParameters: MissionCoreControllerGetMissionsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyMissionsResponse>> {
    const queryParameters: any = {};

    if (requestParameters['abgeschlossen'] != null) {
      queryParameters['abgeschlossen'] = requestParameters['abgeschlossen'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyMissionsResponseFromJSON(jsonValue));
  }

  /**
   */
  async missionCoreControllerGetMissionsV1(
    requestParameters: MissionCoreControllerGetMissionsV1Request = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyMissionsResponse> {
    const response = await this.missionCoreControllerGetMissionsV1Raw(requestParameters, initOverrides);
    return await response.value();
  }
}
