/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { MyApiResponse, MyMultiApiResponse } from '../models/index';
import {
  MyApiResponseFromJSON,
  MyApiResponseToJSON,
  MyMultiApiResponseFromJSON,
  MyMultiApiResponseToJSON,
} from '../models/index';

export interface NinaControllerGetWarningDetailsV1Request {
  id: string;
}

/**
 *
 */
export class NinaApi extends runtime.BaseAPI {
  /**
   */
  async ninaControllerGetAllWarningDetailsV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<MyMultiApiResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/features/nina/warnings`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => MyMultiApiResponseFromJSON(jsonValue));
  }

  /**
   */
  async ninaControllerGetAllWarningDetailsV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<MyMultiApiResponse> {
    const response = await this.ninaControllerGetAllWarningDetailsV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async ninaControllerGetGeoJsonV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<MyApiResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/features/nina/warnings.geojson`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => MyApiResponseFromJSON(jsonValue));
  }

  /**
   */
  async ninaControllerGetGeoJsonV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MyApiResponse> {
    const response = await this.ninaControllerGetGeoJsonV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async ninaControllerGetWarningDetailsV1Raw(
    requestParameters: NinaControllerGetWarningDetailsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<MyMultiApiResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling ninaControllerGetWarningDetailsV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/features/nina/warning/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => MyMultiApiResponseFromJSON(jsonValue));
  }

  /**
   */
  async ninaControllerGetWarningDetailsV1(
    requestParameters: NinaControllerGetWarningDetailsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<MyMultiApiResponse> {
    const response = await this.ninaControllerGetWarningDetailsV1Raw(requestParameters, initOverrides);
    return await response.value();
  }
}
