/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateNotizDto, ManyNoteResponse, OneNoteResponse } from '../models/index';
import {
  CreateNotizDtoFromJSON,
  CreateNotizDtoToJSON,
  ManyNoteResponseFromJSON,
  ManyNoteResponseToJSON,
  OneNoteResponseFromJSON,
  OneNoteResponseToJSON,
} from '../models/index';

export interface NotizenControllerCompleteNotizV1Request {
  notizId: string;
  missionId: string;
}

export interface NotizenControllerCreateNotizV1Request {
  missionId: string;
  createNotizDto: CreateNotizDto;
}

export interface NotizenControllerDeleteNotizV1Request {
  notizId: string;
  missionId: string;
}

export interface NotizenControllerGetNotizenV1Request {
  missionId: string;
  done?: boolean;
}

export interface NotizenControllerUpdateNotizV1Request {
  notizId: string;
  missionId: string;
  createNotizDto: CreateNotizDto;
}

/**
 *
 */
export class NotizenApi extends runtime.BaseAPI {
  /**
   */
  async notizenControllerCompleteNotizV1Raw(
    requestParameters: NotizenControllerCompleteNotizV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['notizId'] == null) {
      throw new runtime.RequiredError(
        'notizId',
        'Required parameter "notizId" was null or undefined when calling notizenControllerCompleteNotizV1().',
      );
    }

    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling notizenControllerCompleteNotizV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/notes/{notizId}/toggle-complete`
          .replace(`{${'notizId'}}`, encodeURIComponent(String(requestParameters['notizId'])))
          .replace(`{${'missionId'}}`, encodeURIComponent(String(requestParameters['missionId']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async notizenControllerCompleteNotizV1(
    requestParameters: NotizenControllerCompleteNotizV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.notizenControllerCompleteNotizV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async notizenControllerCreateNotizV1Raw(
    requestParameters: NotizenControllerCreateNotizV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<OneNoteResponse>> {
    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling notizenControllerCreateNotizV1().',
      );
    }

    if (requestParameters['createNotizDto'] == null) {
      throw new runtime.RequiredError(
        'createNotizDto',
        'Required parameter "createNotizDto" was null or undefined when calling notizenControllerCreateNotizV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/notes`.replace(
          `{${'missionId'}}`,
          encodeURIComponent(String(requestParameters['missionId'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateNotizDtoToJSON(requestParameters['createNotizDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OneNoteResponseFromJSON(jsonValue));
  }

  /**
   */
  async notizenControllerCreateNotizV1(
    requestParameters: NotizenControllerCreateNotizV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<OneNoteResponse> {
    const response = await this.notizenControllerCreateNotizV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async notizenControllerDeleteNotizV1Raw(
    requestParameters: NotizenControllerDeleteNotizV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['notizId'] == null) {
      throw new runtime.RequiredError(
        'notizId',
        'Required parameter "notizId" was null or undefined when calling notizenControllerDeleteNotizV1().',
      );
    }

    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling notizenControllerDeleteNotizV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/notes/{notizId}`
          .replace(`{${'notizId'}}`, encodeURIComponent(String(requestParameters['notizId'])))
          .replace(`{${'missionId'}}`, encodeURIComponent(String(requestParameters['missionId']))),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async notizenControllerDeleteNotizV1(
    requestParameters: NotizenControllerDeleteNotizV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.notizenControllerDeleteNotizV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async notizenControllerGetNotizenV1Raw(
    requestParameters: NotizenControllerGetNotizenV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyNoteResponse>> {
    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling notizenControllerGetNotizenV1().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['done'] != null) {
      queryParameters['done'] = requestParameters['done'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/notes`.replace(
          `{${'missionId'}}`,
          encodeURIComponent(String(requestParameters['missionId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyNoteResponseFromJSON(jsonValue));
  }

  /**
   */
  async notizenControllerGetNotizenV1(
    requestParameters: NotizenControllerGetNotizenV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyNoteResponse> {
    const response = await this.notizenControllerGetNotizenV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async notizenControllerUpdateNotizV1Raw(
    requestParameters: NotizenControllerUpdateNotizV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['notizId'] == null) {
      throw new runtime.RequiredError(
        'notizId',
        'Required parameter "notizId" was null or undefined when calling notizenControllerUpdateNotizV1().',
      );
    }

    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling notizenControllerUpdateNotizV1().',
      );
    }

    if (requestParameters['createNotizDto'] == null) {
      throw new runtime.RequiredError(
        'createNotizDto',
        'Required parameter "createNotizDto" was null or undefined when calling notizenControllerUpdateNotizV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/notes/{notizId}`
          .replace(`{${'notizId'}}`, encodeURIComponent(String(requestParameters['notizId'])))
          .replace(`{${'missionId'}}`, encodeURIComponent(String(requestParameters['missionId']))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: CreateNotizDtoToJSON(requestParameters['createNotizDto']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async notizenControllerUpdateNotizV1(
    requestParameters: NotizenControllerUpdateNotizV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.notizenControllerUpdateNotizV1Raw(requestParameters, initOverrides);
  }
}
