/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

/**
 *
 */
export class OptaSchemaApi extends runtime.BaseAPI {
  /**
   */
  async optaSchemaControllerGetLocalCodeV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/opta/schema/local-code/v5`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async optaSchemaControllerGetLocalCodeV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.optaSchemaControllerGetLocalCodeV1Raw(initOverrides);
  }

  /**
   */
  async optaSchemaControllerGetSchemaBosV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/opta/schema/bos/v2`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async optaSchemaControllerGetSchemaBosV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.optaSchemaControllerGetSchemaBosV1Raw(initOverrides);
  }

  /**
   */
  async optaSchemaControllerGetSchemaDistrictsV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/opta/schema/districts/v2`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async optaSchemaControllerGetSchemaDistrictsV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.optaSchemaControllerGetSchemaDistrictsV1Raw(initOverrides);
  }

  /**
   */
  async optaSchemaControllerGetSchemaFunktionenV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/opta/schema/funktionen/v2`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async optaSchemaControllerGetSchemaFunktionenV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.optaSchemaControllerGetSchemaFunktionenV1Raw(initOverrides);
  }
}
