/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ManyFunctionOptaTemplatesResponse } from '../models/index';
import { ManyFunctionOptaTemplatesResponseFromJSON, ManyFunctionOptaTemplatesResponseToJSON } from '../models/index';

/**
 *
 */
export class OptaApi extends runtime.BaseAPI {
  /**
   */
  async optaControllerFindFunctionOptaV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyFunctionOptaTemplatesResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/opta/function`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyFunctionOptaTemplatesResponseFromJSON(jsonValue));
  }

  /**
   */
  async optaControllerFindFunctionOptaV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyFunctionOptaTemplatesResponse> {
    const response = await this.optaControllerFindFunctionOptaV1Raw(initOverrides);
    return await response.value();
  }
}
