/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  ManyBosOptaTemplatesResponse,
  ManyDistrictOptaTemplatesResponse,
  ManyFunctionOptaTemplatesResponse,
  ManyLocalCodeOptaTemplatesResponse,
} from '../models/index';
import {
  ManyBosOptaTemplatesResponseFromJSON,
  ManyBosOptaTemplatesResponseToJSON,
  ManyDistrictOptaTemplatesResponseFromJSON,
  ManyDistrictOptaTemplatesResponseToJSON,
  ManyFunctionOptaTemplatesResponseFromJSON,
  ManyFunctionOptaTemplatesResponseToJSON,
  ManyLocalCodeOptaTemplatesResponseFromJSON,
  ManyLocalCodeOptaTemplatesResponseToJSON,
} from '../models/index';

/**
 *
 */
export class OptaApi extends runtime.BaseAPI {
  /**
   */
  async optaControllerFindBosOptaV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyBosOptaTemplatesResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/opta/bos`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyBosOptaTemplatesResponseFromJSON(jsonValue));
  }

  /**
   */
  async optaControllerFindBosOptaV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyBosOptaTemplatesResponse> {
    const response = await this.optaControllerFindBosOptaV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async optaControllerFindDistrictOptaV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyDistrictOptaTemplatesResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/opta/district`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyDistrictOptaTemplatesResponseFromJSON(jsonValue));
  }

  /**
   */
  async optaControllerFindDistrictOptaV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyDistrictOptaTemplatesResponse> {
    const response = await this.optaControllerFindDistrictOptaV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async optaControllerFindFunctionOptaV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyFunctionOptaTemplatesResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/opta/function`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyFunctionOptaTemplatesResponseFromJSON(jsonValue));
  }

  /**
   */
  async optaControllerFindFunctionOptaV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyFunctionOptaTemplatesResponse> {
    const response = await this.optaControllerFindFunctionOptaV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async optaControllerFindLocalCodeOptaV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyLocalCodeOptaTemplatesResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/opta/local-code`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyLocalCodeOptaTemplatesResponseFromJSON(jsonValue));
  }

  /**
   */
  async optaControllerFindLocalCodeOptaV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyLocalCodeOptaTemplatesResponse> {
    const response = await this.optaControllerFindLocalCodeOptaV1Raw(initOverrides);
    return await response.value();
  }
}
