/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ManyQualificationsResponse } from '../models/index';
import { ManyQualificationsResponseFromJSON, ManyQualificationsResponseToJSON } from '../models/index';

/**
 *
 */
export class QualifikationenApi extends runtime.BaseAPI {
  /**
   */
  async qualifikationenControllerFindAllV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyQualificationsResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/qualifications`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyQualificationsResponseFromJSON(jsonValue));
  }

  /**
   */
  async qualifikationenControllerFindAllV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyQualificationsResponse> {
    const response = await this.qualifikationenControllerFindAllV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async qualifikationenControllerGetSchemaV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/qualifications/schema/v4`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async qualifikationenControllerGetSchemaV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.qualifikationenControllerGetSchemaV1Raw(initOverrides);
  }
}
