/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateReminderDto, ManyReminderResponse, OneReminderResponse } from '../models/index';
import {
  CreateReminderDtoFromJSON,
  CreateReminderDtoToJSON,
  ManyReminderResponseFromJSON,
  ManyReminderResponseToJSON,
  OneReminderResponseFromJSON,
  OneReminderResponseToJSON,
} from '../models/index';

export interface RemindersControllerCreateReminderV1Request {
  missionId: string;
  createReminderDto: CreateReminderDto;
}

export interface RemindersControllerGetDueRemindersV1Request {
  missionId: string;
}

export interface RemindersControllerMarkAsNotifiedV1Request {
  missionId: string;
  reminderId: string;
}

export interface RemindersControllerMarkAsReadV1Request {
  missionId: string;
  remindersId: string;
}

/**
 *
 */
export class RemindersApi extends runtime.BaseAPI {
  /**
   */
  async remindersControllerCreateReminderV1Raw(
    requestParameters: RemindersControllerCreateReminderV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<OneReminderResponse>> {
    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling remindersControllerCreateReminderV1().',
      );
    }

    if (requestParameters['createReminderDto'] == null) {
      throw new runtime.RequiredError(
        'createReminderDto',
        'Required parameter "createReminderDto" was null or undefined when calling remindersControllerCreateReminderV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/reminders`.replace(
          `{${'missionId'}}`,
          encodeURIComponent(String(requestParameters['missionId'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateReminderDtoToJSON(requestParameters['createReminderDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OneReminderResponseFromJSON(jsonValue));
  }

  /**
   */
  async remindersControllerCreateReminderV1(
    requestParameters: RemindersControllerCreateReminderV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<OneReminderResponse> {
    const response = await this.remindersControllerCreateReminderV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async remindersControllerGetDueRemindersV1Raw(
    requestParameters: RemindersControllerGetDueRemindersV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyReminderResponse>> {
    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling remindersControllerGetDueRemindersV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/reminders/due`.replace(
          `{${'missionId'}}`,
          encodeURIComponent(String(requestParameters['missionId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyReminderResponseFromJSON(jsonValue));
  }

  /**
   */
  async remindersControllerGetDueRemindersV1(
    requestParameters: RemindersControllerGetDueRemindersV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyReminderResponse> {
    const response = await this.remindersControllerGetDueRemindersV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async remindersControllerMarkAsNotifiedV1Raw(
    requestParameters: RemindersControllerMarkAsNotifiedV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling remindersControllerMarkAsNotifiedV1().',
      );
    }

    if (requestParameters['reminderId'] == null) {
      throw new runtime.RequiredError(
        'reminderId',
        'Required parameter "reminderId" was null or undefined when calling remindersControllerMarkAsNotifiedV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/reminders/{reminderId}/mark-notified`
          .replace(`{${'missionId'}}`, encodeURIComponent(String(requestParameters['missionId'])))
          .replace(`{${'reminderId'}}`, encodeURIComponent(String(requestParameters['reminderId']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async remindersControllerMarkAsNotifiedV1(
    requestParameters: RemindersControllerMarkAsNotifiedV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.remindersControllerMarkAsNotifiedV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async remindersControllerMarkAsReadV1Raw(
    requestParameters: RemindersControllerMarkAsReadV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['missionId'] == null) {
      throw new runtime.RequiredError(
        'missionId',
        'Required parameter "missionId" was null or undefined when calling remindersControllerMarkAsReadV1().',
      );
    }

    if (requestParameters['remindersId'] == null) {
      throw new runtime.RequiredError(
        'remindersId',
        'Required parameter "remindersId" was null or undefined when calling remindersControllerMarkAsReadV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/missions/{missionId}/reminders/{remindersId}/mark-read`
          .replace(`{${'missionId'}}`, encodeURIComponent(String(requestParameters['missionId'])))
          .replace(`{${'remindersId'}}`, encodeURIComponent(String(requestParameters['remindersId']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async remindersControllerMarkAsReadV1(
    requestParameters: RemindersControllerMarkAsReadV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.remindersControllerMarkAsReadV1Raw(requestParameters, initOverrides);
  }
}
