/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface SecretsControllerReadSecretV1Request {
  secret: string;
}

export interface SecretsControllerReadSecretV10Request {
  secret: string;
}

/**
 *
 */
export class SecretsApi extends runtime.BaseAPI {
  /**
   */
  async secretsControllerCreateSecretV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/core/secrets`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async secretsControllerCreateSecretV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.secretsControllerCreateSecretV1Raw(initOverrides);
  }

  /**
   * Read a secrets value
   */
  async secretsControllerReadSecretV1Raw(
    requestParameters: SecretsControllerReadSecretV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['secret'] == null) {
      throw new runtime.RequiredError(
        'secret',
        'Required parameter "secret" was null or undefined when calling secretsControllerReadSecretV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['bearbeiter'] = await this.configuration.apiKey('bearbeiter'); // Bearbeiter authentication
    }

    const response = await this.request(
      {
        path: `/v1/core/secrets/{secret}`.replace(
          `{${'secret'}}`,
          encodeURIComponent(String(requestParameters['secret'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Read a secrets value
   */
  async secretsControllerReadSecretV1(
    requestParameters: SecretsControllerReadSecretV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.secretsControllerReadSecretV1Raw(requestParameters, initOverrides);
  }

  /**
   * Read a secrets value
   */
  async secretsControllerReadSecretV1_1Raw(
    requestParameters: SecretsControllerReadSecretV10Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['secret'] == null) {
      throw new runtime.RequiredError(
        'secret',
        'Required parameter "secret" was null or undefined when calling secretsControllerReadSecretV1_1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['bearbeiter'] = await this.configuration.apiKey('bearbeiter'); // Bearbeiter authentication
    }

    const response = await this.request(
      {
        path: `/v1/core/secrets/{secret}`.replace(
          `{${'secret'}}`,
          encodeURIComponent(String(requestParameters['secret'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Read a secrets value
   */
  async secretsControllerReadSecretV1_1(
    requestParameters: SecretsControllerReadSecretV10Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.secretsControllerReadSecretV1_1Raw(requestParameters, initOverrides);
  }
}
