/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { SecretsDto, SecretsResponse } from '../models/index';
import { SecretsDtoFromJSON, SecretsDtoToJSON, SecretsResponseFromJSON, SecretsResponseToJSON } from '../models/index';

export interface SecretsControllerCreateSecretV1Request {
  secretsDto: SecretsDto;
}

export interface SecretsControllerCreateSecretV10Request {
  secretsDto: SecretsDto;
}

export interface SecretsControllerReadSecretV1Request {
  secret: string;
}

export interface SecretsControllerReadSecretV10Request {
  secret: string;
}

/**
 *
 */
export class SecretsApi extends runtime.BaseAPI {
  /**
   * Create a new secrets
   */
  async secretsControllerCreateSecretV1Raw(
    requestParameters: SecretsControllerCreateSecretV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SecretsResponse>> {
    if (requestParameters['secretsDto'] == null) {
      throw new runtime.RequiredError(
        'secretsDto',
        'Required parameter "secretsDto" was null or undefined when calling secretsControllerCreateSecretV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['bearbeiter'] = await this.configuration.apiKey('bearbeiter'); // Bearbeiter authentication
    }

    const response = await this.request(
      {
        path: `/v1/core/secrets`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: SecretsDtoToJSON(requestParameters['secretsDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => SecretsResponseFromJSON(jsonValue));
  }

  /**
   * Create a new secrets
   */
  async secretsControllerCreateSecretV1(
    requestParameters: SecretsControllerCreateSecretV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SecretsResponse> {
    const response = await this.secretsControllerCreateSecretV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Create a new secrets
   */
  async secretsControllerCreateSecretV1_1Raw(
    requestParameters: SecretsControllerCreateSecretV10Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SecretsResponse>> {
    if (requestParameters['secretsDto'] == null) {
      throw new runtime.RequiredError(
        'secretsDto',
        'Required parameter "secretsDto" was null or undefined when calling secretsControllerCreateSecretV1_1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['bearbeiter'] = await this.configuration.apiKey('bearbeiter'); // Bearbeiter authentication
    }

    const response = await this.request(
      {
        path: `/v1/core/secrets`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: SecretsDtoToJSON(requestParameters['secretsDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => SecretsResponseFromJSON(jsonValue));
  }

  /**
   * Create a new secrets
   */
  async secretsControllerCreateSecretV1_1(
    requestParameters: SecretsControllerCreateSecretV10Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SecretsResponse> {
    const response = await this.secretsControllerCreateSecretV1_1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Read a secrets value
   */
  async secretsControllerReadSecretV1Raw(
    requestParameters: SecretsControllerReadSecretV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SecretsResponse>> {
    if (requestParameters['secret'] == null) {
      throw new runtime.RequiredError(
        'secret',
        'Required parameter "secret" was null or undefined when calling secretsControllerReadSecretV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['bearbeiter'] = await this.configuration.apiKey('bearbeiter'); // Bearbeiter authentication
    }

    const response = await this.request(
      {
        path: `/v1/core/secrets/{secret}`.replace(
          `{${'secret'}}`,
          encodeURIComponent(String(requestParameters['secret'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => SecretsResponseFromJSON(jsonValue));
  }

  /**
   * Read a secrets value
   */
  async secretsControllerReadSecretV1(
    requestParameters: SecretsControllerReadSecretV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SecretsResponse> {
    const response = await this.secretsControllerReadSecretV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Read a secrets value
   */
  async secretsControllerReadSecretV1_2Raw(
    requestParameters: SecretsControllerReadSecretV10Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SecretsResponse>> {
    if (requestParameters['secret'] == null) {
      throw new runtime.RequiredError(
        'secret',
        'Required parameter "secret" was null or undefined when calling secretsControllerReadSecretV1_2().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['bearbeiter'] = await this.configuration.apiKey('bearbeiter'); // Bearbeiter authentication
    }

    const response = await this.request(
      {
        path: `/v1/core/secrets/{secret}`.replace(
          `{${'secret'}}`,
          encodeURIComponent(String(requestParameters['secret'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => SecretsResponseFromJSON(jsonValue));
  }

  /**
   * Read a secrets value
   */
  async secretsControllerReadSecretV1_2(
    requestParameters: SecretsControllerReadSecretV10Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SecretsResponse> {
    const response = await this.secretsControllerReadSecretV1_2Raw(requestParameters, initOverrides);
    return await response.value();
  }
}
