/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { SettingsDto, SettingsResponse } from '../models/index';
import {
  SettingsDtoFromJSON,
  SettingsDtoToJSON,
  SettingsResponseFromJSON,
  SettingsResponseToJSON,
} from '../models/index';

export interface SettingsControllerSaveSettingsV1Request {
  settingsDto: SettingsDto;
}

/**
 *
 */
export class SettingsApi extends runtime.BaseAPI {
  /**
   */
  async settingsControllerFindSettingsV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SettingsResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/core/settings`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => SettingsResponseFromJSON(jsonValue));
  }

  /**
   */
  async settingsControllerFindSettingsV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SettingsResponse> {
    const response = await this.settingsControllerFindSettingsV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async settingsControllerSaveSettingsV1Raw(
    requestParameters: SettingsControllerSaveSettingsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['settingsDto'] == null) {
      throw new runtime.RequiredError(
        'settingsDto',
        'Required parameter "settingsDto" was null or undefined when calling settingsControllerSaveSettingsV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/core/settings`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: SettingsDtoToJSON(requestParameters['settingsDto']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async settingsControllerSaveSettingsV1(
    requestParameters: SettingsControllerSaveSettingsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.settingsControllerSaveSettingsV1Raw(requestParameters, initOverrides);
  }
}
