/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ManyStatusDtoReponse } from '../models/index';
import { ManyStatusDtoReponseFromJSON, ManyStatusDtoReponseToJSON } from '../models/index';

export interface StatusControllerStatusV1Request {
  code?: number;
}

/**
 *
 */
export class StatusApi extends runtime.BaseAPI {
  /**
   */
  async statusControllerSchemaV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/status/schema/v3`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async statusControllerSchemaV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.statusControllerSchemaV1Raw(initOverrides);
  }

  /**
   */
  async statusControllerStatusV1Raw(
    requestParameters: StatusControllerStatusV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyStatusDtoReponse>> {
    const queryParameters: any = {};

    if (requestParameters['code'] != null) {
      queryParameters['code'] = requestParameters['code'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/status`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyStatusDtoReponseFromJSON(jsonValue));
  }

  /**
   */
  async statusControllerStatusV1(
    requestParameters: StatusControllerStatusV1Request = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyStatusDtoReponse> {
    const response = await this.statusControllerStatusV1Raw(requestParameters, initOverrides);
    return await response.value();
  }
}
