/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ImportManyUAVsDto, ManyUAVTemplateResponse } from '../models/index';
import {
  ImportManyUAVsDtoToJSON,
  ManyUAVTemplateResponseFromJSON
} from '../models/index';

export interface UAVControllerDeleteUAVV1Request {
  uavId: string;
}

export interface UAVControllerImportUAVsV1Request {
  importManyUAVsDto: ImportManyUAVsDto;
}

export interface UAVControllerUpdateManyV1Request {
  importManyUAVsDto: ImportManyUAVsDto;
}

/**
 *
 */
export class UAVApi extends runtime.BaseAPI {
  /**
   */
  async uAVControllerDeleteUAVV1Raw(
    requestParameters: UAVControllerDeleteUAVV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['uavId'] == null) {
      throw new runtime.RequiredError(
        'uavId',
        'Required parameter "uavId" was null or undefined when calling uAVControllerDeleteUAVV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/uav/{uavId}`.replace(
          `{${'uavId'}}`,
          encodeURIComponent(String(requestParameters['uavId'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async uAVControllerDeleteUAVV1(
    requestParameters: UAVControllerDeleteUAVV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uAVControllerDeleteUAVV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async uAVControllerFindAllV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyUAVTemplateResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/uav`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyUAVTemplateResponseFromJSON(jsonValue));
  }

  /**
   */
  async uAVControllerFindAllV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyUAVTemplateResponse> {
    const response = await this.uAVControllerFindAllV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async uAVControllerImportUAVsV1Raw(
    requestParameters: UAVControllerImportUAVsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['importManyUAVsDto'] == null) {
      throw new runtime.RequiredError(
        'importManyUAVsDto',
        'Required parameter "importManyUAVsDto" was null or undefined when calling uAVControllerImportUAVsV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/templates/uav/import`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ImportManyUAVsDtoToJSON(requestParameters['importManyUAVsDto']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async uAVControllerImportUAVsV1(
    requestParameters: UAVControllerImportUAVsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uAVControllerImportUAVsV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async uAVControllerUpdateManyV1Raw(
    requestParameters: UAVControllerUpdateManyV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['importManyUAVsDto'] == null) {
      throw new runtime.RequiredError(
        'importManyUAVsDto',
        'Required parameter "importManyUAVsDto" was null or undefined when calling uAVControllerUpdateManyV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/templates/uav`,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: ImportManyUAVsDtoToJSON(requestParameters['importManyUAVsDto']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async uAVControllerUpdateManyV1(
    requestParameters: UAVControllerUpdateManyV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uAVControllerUpdateManyV1Raw(requestParameters, initOverrides);
  }
}
