/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  CreateUAVMissionDto,
  FlightProtocolDto,
  FlightProtocolResponse,
  PostFlightChecksDto,
  PreFlightChecksDto,
  UAVMissionResponse,
  UAVMissionsResponse,
} from '../models/index';
import {
  CreateUAVMissionDtoFromJSON,
  CreateUAVMissionDtoToJSON,
  FlightProtocolDtoFromJSON,
  FlightProtocolDtoToJSON,
  FlightProtocolResponseFromJSON,
  FlightProtocolResponseToJSON,
  PostFlightChecksDtoFromJSON,
  PostFlightChecksDtoToJSON,
  PreFlightChecksDtoFromJSON,
  PreFlightChecksDtoToJSON,
  UAVMissionResponseFromJSON,
  UAVMissionResponseToJSON,
  UAVMissionsResponseFromJSON,
  UAVMissionsResponseToJSON,
} from '../models/index';

export interface UAVMissionControllerAddFlightProtocolV1Request {
  einsatzId: string;
  uavIndex: number;
  flightProtocolDto: FlightProtocolDto;
}

export interface UAVMissionControllerAddUAVToEinsatzV1Request {
  einsatzId: string;
  createUAVMissionDto: CreateUAVMissionDto;
}

export interface UAVMissionControllerGetAllUAVMissionsV1Request {
  einsatzId: string;
}

export interface UAVMissionControllerGetUAVMissionV1Request {
  einsatzId: string;
  uavIndex: number;
}

export interface UAVMissionControllerSubmitPostFlightChecksV1Request {
  einsatzId: string;
  uavIndex: number;
  postFlightChecksDto: PostFlightChecksDto;
}

export interface UAVMissionControllerSubmitPreFlightChecksV1Request {
  einsatzId: string;
  uavIndex: number;
  preFlightChecksDto: PreFlightChecksDto;
}

/**
 *
 */
export class UAVMissionsApi extends runtime.BaseAPI {
  /**
   * Add a flight protocol
   */
  async uAVMissionControllerAddFlightProtocolV1Raw(
    requestParameters: UAVMissionControllerAddFlightProtocolV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FlightProtocolResponse>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerAddFlightProtocolV1().',
      );
    }

    if (requestParameters['uavIndex'] == null) {
      throw new runtime.RequiredError(
        'uavIndex',
        'Required parameter "uavIndex" was null or undefined when calling uAVMissionControllerAddFlightProtocolV1().',
      );
    }

    if (requestParameters['flightProtocolDto'] == null) {
      throw new runtime.RequiredError(
        'flightProtocolDto',
        'Required parameter "flightProtocolDto" was null or undefined when calling uAVMissionControllerAddFlightProtocolV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav/{uavIndex}/flight`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'uavIndex'}}`, encodeURIComponent(String(requestParameters['uavIndex']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: FlightProtocolDtoToJSON(requestParameters['flightProtocolDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => FlightProtocolResponseFromJSON(jsonValue));
  }

  /**
   * Add a flight protocol
   */
  async uAVMissionControllerAddFlightProtocolV1(
    requestParameters: UAVMissionControllerAddFlightProtocolV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FlightProtocolResponse> {
    const response = await this.uAVMissionControllerAddFlightProtocolV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Add a UAV to an Einsatz
   */
  async uAVMissionControllerAddUAVToEinsatzV1Raw(
    requestParameters: UAVMissionControllerAddUAVToEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UAVMissionResponse>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerAddUAVToEinsatzV1().',
      );
    }

    if (requestParameters['createUAVMissionDto'] == null) {
      throw new runtime.RequiredError(
        'createUAVMissionDto',
        'Required parameter "createUAVMissionDto" was null or undefined when calling uAVMissionControllerAddUAVToEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav`.replace(
          `{${'einsatzId'}}`,
          encodeURIComponent(String(requestParameters['einsatzId'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateUAVMissionDtoToJSON(requestParameters['createUAVMissionDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UAVMissionResponseFromJSON(jsonValue));
  }

  /**
   * Add a UAV to an Einsatz
   */
  async uAVMissionControllerAddUAVToEinsatzV1(
    requestParameters: UAVMissionControllerAddUAVToEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UAVMissionResponse> {
    const response = await this.uAVMissionControllerAddUAVToEinsatzV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get all UAV missions for an Einsatz
   */
  async uAVMissionControllerGetAllUAVMissionsV1Raw(
    requestParameters: UAVMissionControllerGetAllUAVMissionsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UAVMissionsResponse>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerGetAllUAVMissionsV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav`.replace(
          `{${'einsatzId'}}`,
          encodeURIComponent(String(requestParameters['einsatzId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UAVMissionsResponseFromJSON(jsonValue));
  }

  /**
   * Get all UAV missions for an Einsatz
   */
  async uAVMissionControllerGetAllUAVMissionsV1(
    requestParameters: UAVMissionControllerGetAllUAVMissionsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UAVMissionsResponse> {
    const response = await this.uAVMissionControllerGetAllUAVMissionsV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a specific UAV mission
   */
  async uAVMissionControllerGetUAVMissionV1Raw(
    requestParameters: UAVMissionControllerGetUAVMissionV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UAVMissionResponse>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerGetUAVMissionV1().',
      );
    }

    if (requestParameters['uavIndex'] == null) {
      throw new runtime.RequiredError(
        'uavIndex',
        'Required parameter "uavIndex" was null or undefined when calling uAVMissionControllerGetUAVMissionV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav/{uavIndex}`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'uavIndex'}}`, encodeURIComponent(String(requestParameters['uavIndex']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UAVMissionResponseFromJSON(jsonValue));
  }

  /**
   * Get a specific UAV mission
   */
  async uAVMissionControllerGetUAVMissionV1(
    requestParameters: UAVMissionControllerGetUAVMissionV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UAVMissionResponse> {
    const response = await this.uAVMissionControllerGetUAVMissionV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Submit post-flight checks
   */
  async uAVMissionControllerSubmitPostFlightChecksV1Raw(
    requestParameters: UAVMissionControllerSubmitPostFlightChecksV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UAVMissionResponse>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerSubmitPostFlightChecksV1().',
      );
    }

    if (requestParameters['uavIndex'] == null) {
      throw new runtime.RequiredError(
        'uavIndex',
        'Required parameter "uavIndex" was null or undefined when calling uAVMissionControllerSubmitPostFlightChecksV1().',
      );
    }

    if (requestParameters['postFlightChecksDto'] == null) {
      throw new runtime.RequiredError(
        'postFlightChecksDto',
        'Required parameter "postFlightChecksDto" was null or undefined when calling uAVMissionControllerSubmitPostFlightChecksV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav/{uavIndex}/post-flight`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'uavIndex'}}`, encodeURIComponent(String(requestParameters['uavIndex']))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: PostFlightChecksDtoToJSON(requestParameters['postFlightChecksDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UAVMissionResponseFromJSON(jsonValue));
  }

  /**
   * Submit post-flight checks
   */
  async uAVMissionControllerSubmitPostFlightChecksV1(
    requestParameters: UAVMissionControllerSubmitPostFlightChecksV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UAVMissionResponse> {
    const response = await this.uAVMissionControllerSubmitPostFlightChecksV1Raw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Submit pre-flight checks
   */
  async uAVMissionControllerSubmitPreFlightChecksV1Raw(
    requestParameters: UAVMissionControllerSubmitPreFlightChecksV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UAVMissionResponse>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerSubmitPreFlightChecksV1().',
      );
    }

    if (requestParameters['uavIndex'] == null) {
      throw new runtime.RequiredError(
        'uavIndex',
        'Required parameter "uavIndex" was null or undefined when calling uAVMissionControllerSubmitPreFlightChecksV1().',
      );
    }

    if (requestParameters['preFlightChecksDto'] == null) {
      throw new runtime.RequiredError(
        'preFlightChecksDto',
        'Required parameter "preFlightChecksDto" was null or undefined when calling uAVMissionControllerSubmitPreFlightChecksV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav/{uavIndex}/pre-flight`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'uavIndex'}}`, encodeURIComponent(String(requestParameters['uavIndex']))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: PreFlightChecksDtoToJSON(requestParameters['preFlightChecksDto']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UAVMissionResponseFromJSON(jsonValue));
  }

  /**
   * Submit pre-flight checks
   */
  async uAVMissionControllerSubmitPreFlightChecksV1(
    requestParameters: UAVMissionControllerSubmitPreFlightChecksV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UAVMissionResponse> {
    const response = await this.uAVMissionControllerSubmitPreFlightChecksV1Raw(requestParameters, initOverrides);
    return await response.value();
  }
}
