/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface UAVMissionControllerAddFlightProtocolV1Request {
  einsatzId: string;
  uavIndex: number;
}

export interface UAVMissionControllerAddUAVToEinsatzV1Request {
  einsatzId: string;
}

export interface UAVMissionControllerGetAllUAVMissionsV1Request {
  einsatzId: string;
}

export interface UAVMissionControllerGetUAVMissionV1Request {
  einsatzId: string;
  uavIndex: number;
}

export interface UAVMissionControllerSubmitPostFlightChecksV1Request {
  einsatzId: string;
  uavIndex: number;
}

export interface UAVMissionControllerSubmitPreFlightChecksV1Request {
  einsatzId: string;
  uavIndex: number;
}

/**
 *
 */
export class UAVMissionApi extends runtime.BaseAPI {
  /**
   */
  async uAVMissionControllerAddFlightProtocolV1Raw(
    requestParameters: UAVMissionControllerAddFlightProtocolV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerAddFlightProtocolV1().',
      );
    }

    if (requestParameters['uavIndex'] == null) {
      throw new runtime.RequiredError(
        'uavIndex',
        'Required parameter "uavIndex" was null or undefined when calling uAVMissionControllerAddFlightProtocolV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav/{uavIndex}/flight`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'uavIndex'}}`, encodeURIComponent(String(requestParameters['uavIndex']))),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async uAVMissionControllerAddFlightProtocolV1(
    requestParameters: UAVMissionControllerAddFlightProtocolV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uAVMissionControllerAddFlightProtocolV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async uAVMissionControllerAddUAVToEinsatzV1Raw(
    requestParameters: UAVMissionControllerAddUAVToEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerAddUAVToEinsatzV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav`.replace(
          `{${'einsatzId'}}`,
          encodeURIComponent(String(requestParameters['einsatzId'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async uAVMissionControllerAddUAVToEinsatzV1(
    requestParameters: UAVMissionControllerAddUAVToEinsatzV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uAVMissionControllerAddUAVToEinsatzV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async uAVMissionControllerGetAllUAVMissionsV1Raw(
    requestParameters: UAVMissionControllerGetAllUAVMissionsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerGetAllUAVMissionsV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav`.replace(
          `{${'einsatzId'}}`,
          encodeURIComponent(String(requestParameters['einsatzId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async uAVMissionControllerGetAllUAVMissionsV1(
    requestParameters: UAVMissionControllerGetAllUAVMissionsV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uAVMissionControllerGetAllUAVMissionsV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async uAVMissionControllerGetUAVMissionV1Raw(
    requestParameters: UAVMissionControllerGetUAVMissionV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerGetUAVMissionV1().',
      );
    }

    if (requestParameters['uavIndex'] == null) {
      throw new runtime.RequiredError(
        'uavIndex',
        'Required parameter "uavIndex" was null or undefined when calling uAVMissionControllerGetUAVMissionV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav/{uavIndex}`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'uavIndex'}}`, encodeURIComponent(String(requestParameters['uavIndex']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async uAVMissionControllerGetUAVMissionV1(
    requestParameters: UAVMissionControllerGetUAVMissionV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uAVMissionControllerGetUAVMissionV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async uAVMissionControllerSubmitPostFlightChecksV1Raw(
    requestParameters: UAVMissionControllerSubmitPostFlightChecksV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerSubmitPostFlightChecksV1().',
      );
    }

    if (requestParameters['uavIndex'] == null) {
      throw new runtime.RequiredError(
        'uavIndex',
        'Required parameter "uavIndex" was null or undefined when calling uAVMissionControllerSubmitPostFlightChecksV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav/{uavIndex}/post-flight`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'uavIndex'}}`, encodeURIComponent(String(requestParameters['uavIndex']))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async uAVMissionControllerSubmitPostFlightChecksV1(
    requestParameters: UAVMissionControllerSubmitPostFlightChecksV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uAVMissionControllerSubmitPostFlightChecksV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async uAVMissionControllerSubmitPreFlightChecksV1Raw(
    requestParameters: UAVMissionControllerSubmitPreFlightChecksV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['einsatzId'] == null) {
      throw new runtime.RequiredError(
        'einsatzId',
        'Required parameter "einsatzId" was null or undefined when calling uAVMissionControllerSubmitPreFlightChecksV1().',
      );
    }

    if (requestParameters['uavIndex'] == null) {
      throw new runtime.RequiredError(
        'uavIndex',
        'Required parameter "uavIndex" was null or undefined when calling uAVMissionControllerSubmitPreFlightChecksV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/einsaetze/{einsatzId}/uav/{uavIndex}/pre-flight`
          .replace(`{${'einsatzId'}}`, encodeURIComponent(String(requestParameters['einsatzId'])))
          .replace(`{${'uavIndex'}}`, encodeURIComponent(String(requestParameters['uavIndex']))),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async uAVMissionControllerSubmitPreFlightChecksV1(
    requestParameters: UAVMissionControllerSubmitPreFlightChecksV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uAVMissionControllerSubmitPreFlightChecksV1Raw(requestParameters, initOverrides);
  }
}
