/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ImportManyFahrzeugeDto, ManyFahrzeugTypResponse, ManyFahrzeugeTemplateResponse } from '../models/index';
import {
  ImportManyFahrzeugeDtoFromJSON,
  ImportManyFahrzeugeDtoToJSON,
  ManyFahrzeugTypResponseFromJSON,
  ManyFahrzeugTypResponseToJSON,
  ManyFahrzeugeTemplateResponseFromJSON,
  ManyFahrzeugeTemplateResponseToJSON,
} from '../models/index';

export interface VehiclesControllerDeleteVehicleV1Request {
  vehicleId: string;
}

export interface VehiclesControllerImportFahrzeugeV1Request {
  importManyFahrzeugeDto: ImportManyFahrzeugeDto;
}

export interface VehiclesControllerUpdateManyV1Request {
  importManyFahrzeugeDto: ImportManyFahrzeugeDto;
}

/**
 *
 */
export class VehiclesApi extends runtime.BaseAPI {
  /**
   */
  async vehiclesControllerDeleteVehicleV1Raw(
    requestParameters: VehiclesControllerDeleteVehicleV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['vehicleId'] == null) {
      throw new runtime.RequiredError(
        'vehicleId',
        'Required parameter "vehicleId" was null or undefined when calling vehiclesControllerDeleteVehicleV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/vehicles/{vehicleId}`.replace(
          `{${'vehicleId'}}`,
          encodeURIComponent(String(requestParameters['vehicleId'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async vehiclesControllerDeleteVehicleV1(
    requestParameters: VehiclesControllerDeleteVehicleV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.vehiclesControllerDeleteVehicleV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async vehiclesControllerFindAllTypenV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyFahrzeugTypResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/vehicles/typen`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyFahrzeugTypResponseFromJSON(jsonValue));
  }

  /**
   */
  async vehiclesControllerFindAllTypenV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyFahrzeugTypResponse> {
    const response = await this.vehiclesControllerFindAllTypenV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async vehiclesControllerFindAllV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ManyFahrzeugeTemplateResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/vehicles`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ManyFahrzeugeTemplateResponseFromJSON(jsonValue));
  }

  /**
   */
  async vehiclesControllerFindAllV1(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ManyFahrzeugeTemplateResponse> {
    const response = await this.vehiclesControllerFindAllV1Raw(initOverrides);
    return await response.value();
  }

  /**
   */
  async vehiclesControllerGetImportSchemaV1Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/v1/templates/vehicles/import/schema/v2`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async vehiclesControllerGetImportSchemaV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.vehiclesControllerGetImportSchemaV1Raw(initOverrides);
  }

  /**
   */
  async vehiclesControllerImportFahrzeugeV1Raw(
    requestParameters: VehiclesControllerImportFahrzeugeV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['importManyFahrzeugeDto'] == null) {
      throw new runtime.RequiredError(
        'importManyFahrzeugeDto',
        'Required parameter "importManyFahrzeugeDto" was null or undefined when calling vehiclesControllerImportFahrzeugeV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/templates/vehicles/import`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ImportManyFahrzeugeDtoToJSON(requestParameters['importManyFahrzeugeDto']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async vehiclesControllerImportFahrzeugeV1(
    requestParameters: VehiclesControllerImportFahrzeugeV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.vehiclesControllerImportFahrzeugeV1Raw(requestParameters, initOverrides);
  }

  /**
   */
  async vehiclesControllerUpdateManyV1Raw(
    requestParameters: VehiclesControllerUpdateManyV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['importManyFahrzeugeDto'] == null) {
      throw new runtime.RequiredError(
        'importManyFahrzeugeDto',
        'Required parameter "importManyFahrzeugeDto" was null or undefined when calling vehiclesControllerUpdateManyV1().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v1/templates/vehicles`,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: ImportManyFahrzeugeDtoToJSON(requestParameters['importManyFahrzeugeDto']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async vehiclesControllerUpdateManyV1(
    requestParameters: VehiclesControllerUpdateManyV1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.vehiclesControllerUpdateManyV1Raw(requestParameters, initOverrides);
  }
}
