/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateEinsatztagebuchDto
 */
export interface CreateEinsatztagebuchDto {
  /**
   *
   * @type {string}
   * @memberof CreateEinsatztagebuchDto
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof CreateEinsatztagebuchDto
   */
  type: CreateEinsatztagebuchDtoTypeEnum;
  /**
   *
   * @type {string}
   * @memberof CreateEinsatztagebuchDto
   */
  absender: string;
  /**
   *
   * @type {string}
   * @memberof CreateEinsatztagebuchDto
   */
  empfaenger: string;
  /**
   *
   * @type {string}
   * @memberof CreateEinsatztagebuchDto
   */
  timestamp: string;
}

/**
 * @export
 */
export const CreateEinsatztagebuchDtoTypeEnum = {
  User: 'USER',
  Generisch: 'GENERISCH',
  Ressourcen: 'RESSOURCEN',
  Kommunikation: 'KOMMUNIKATION',
  Lage: 'LAGE',
  Betroffene: 'BETROFFENE',
} as const;
export type CreateEinsatztagebuchDtoTypeEnum =
  (typeof CreateEinsatztagebuchDtoTypeEnum)[keyof typeof CreateEinsatztagebuchDtoTypeEnum];

/**
 * Check if a given object implements the CreateEinsatztagebuchDto interface.
 */
export function instanceOfCreateEinsatztagebuchDto(value: object): value is CreateEinsatztagebuchDto {
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('absender' in value) || value['absender'] === undefined) return false;
  if (!('empfaenger' in value) || value['empfaenger'] === undefined) return false;
  if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
  return true;
}

export function CreateEinsatztagebuchDtoFromJSON(json: any): CreateEinsatztagebuchDto {
  return CreateEinsatztagebuchDtoFromJSONTyped(json, false);
}

export function CreateEinsatztagebuchDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateEinsatztagebuchDto {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
    type: json['type'],
    absender: json['absender'],
    empfaenger: json['empfaenger'],
    timestamp: json['timestamp'],
  };
}

export function CreateEinsatztagebuchDtoToJSON(json: any): CreateEinsatztagebuchDto {
  return CreateEinsatztagebuchDtoToJSONTyped(json, false);
}

export function CreateEinsatztagebuchDtoToJSONTyped(
  value?: CreateEinsatztagebuchDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
    type: value['type'],
    absender: value['absender'],
    empfaenger: value['empfaenger'],
    timestamp: value['timestamp'],
  };
}
