/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateNotizDto
 */
export interface UpdateNotizDto {
  /**
   *
   * @type {string}
   * @memberof UpdateNotizDto
   */
  content: string;
}

/**
 * Check if a given object implements the UpdateNotizDto interface.
 */
export function instanceOfUpdateNotizDto(value: object): value is UpdateNotizDto {
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function UpdateNotizDtoFromJSON(json: any): UpdateNotizDto {
  return UpdateNotizDtoFromJSONTyped(json, false);
}

export function UpdateNotizDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNotizDto {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
  };
}

export function UpdateNotizDtoToJSON(json: any): UpdateNotizDto {
  return UpdateNotizDtoToJSONTyped(json, false);
}

export function UpdateNotizDtoToJSONTyped(value?: UpdateNotizDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
  };
}
