INSERT INTO "EinheitTyp" (id, label, grundzeichen, description)
VALUES (generate_cuid(), 'RTW', 'kraftfahrzeug-landgebunden', 'Rettungstransportwagen'),
       (generate_cuid(), 'FüKW', 'kraftfahrzeug-landgebunden', 'Führungskraftwagen'),
       (generate_cuid(), 'KdoW', 'kraftfahrzeug-landgebunden', 'Kommandowagen'),
       (generate_cuid(), 'AufklSt Luft', 'taktische-formation', 'Aufklärungsstaffel Luft'),
       (generate_cuid(), 'SEG', 'taktische-formation', 'Schnelleinsatzgruppe'),
       (generate_cuid(), 'BTP', 'stelle', 'Betreuungsplatz'),
       (generate_cuid(), 'KTW', 'kraftfahrzeug-landgebunden', 'Krankentransportwagen'),
       (generate_cuid(), 'NEF', 'kraftfahrzeug-landgebunden', 'Notarzteinsatzfahrzeug'),
       (generate_cuid(), 'GW-San', 'wechsellader', 'Gerätewagen Sanität mit Abrollbehälter'),
       (generate_cuid(), 'AB-San', 'abrollbehaelter', 'Abrollbehälter Sanität für GW-San'),
       (generate_cuid(), 'ELW', 'kraftfahrzeug-landgebunden', 'Einsatzleitwagen'),
       (generate_cuid(), 'MTW', 'kraftfahrzeug-landgebunden', 'Mannschaftstransportwagen'),
       (generate_cuid(), 'GW-Technik', 'kraftfahrzeug-landgebunden', 'Gerätewagen Technik'),
       (generate_cuid(), 'GW-Verpflegung', 'kraftfahrzeug-landgebunden', 'Gerätewagen Verpflegung'),
       (generate_cuid(), 'GW-Betreuung', 'kraftfahrzeug-landgebunden', 'Gerätewagen Betreuung'),
       (generate_cuid(), 'GW-Wasserrettung', 'kraftfahrzeug-landgebunden', 'Gerätewagen Wasserrettung'),
       (generate_cuid(), 'Rettungsboot', 'wasserfahrzeug', 'Rettungsboot'),
       (generate_cuid(), 'Feldküche', 'anhaenger', 'Mobile Feldküche'),
       (generate_cuid(), 'Trinkwasseraufbereitungsanlage', 'abrollbehaelter', 'Trinkwasseraufbereitungsanlage'),
       (generate_cuid(), 'Notunterkunft', 'stelle', 'Mobile Notunterkunft'),
       (generate_cuid(), 'Rettungshundestaffel', 'taktische-formation', 'Rettungshundestaffel'),
       (generate_cuid(), 'GW-Hund', 'kraftfahrzeug-landgebunden', 'Gerätewagen Hund'),
       (generate_cuid(), 'RTH', 'hubschrauber', 'Rettungstransporthubschrauber'),
       (generate_cuid(), 'LNA', 'person', 'Leitender Notarzt'),
       (generate_cuid(), 'OrgL', 'person', 'Organisatorischer Leiter'),
       (generate_cuid(), 'TEL', 'taktische-formation', 'Technische Einsatzleitung'),
       (generate_cuid(), 'UG-SanEL', 'kraftfahrzeug-landgebunden', 'Unterstützungsgruppe Sanitätseinsatzleitung'),
       (generate_cuid(), 'AB-Alles', 'abrollbehaelter', 'Abrollbehälter Alles (Universalbehälter)'),
       (generate_cuid(), 'San-Station', 'abrollbehaelter', 'Sanitätsstation (Abrollbehälter)');

-- Einfügen eines Platzhalter-Rettungsmittels
INSERT INTO einheiten (id, funkrufname, kapazitaet, "istTemporaer", "createdAt", "updatedAt", "aktuellerStatusId",
                       "einheitTypId", fachaufgabe, organisation, verwaltungsstufe)
VALUES (generate_cuid(), '1-1-1', 0, false, now(), now(), null,
        (select id from "EinheitTyp" as ET where ET.label = 'FüKW' limit 1), '', '', '');
