import { UseNavigateResult } from '@tanstack/react-router';
import { MenuItemType } from 'antd/lib/menu/interface.js';
import {
  PiAmbulance,
  PiChartPie,
  PiChecks,
  PiClipboardBold,
  PiClipboardText,
  PiClock,
  PiClockClockwise,
  PiCloud,
  PiDrone,
  PiFirstAid,
  PiGauge,
  PiGaugeBold,
  PiInfo,
  PiMapPinLineBold,
  PiMapTrifold,
  PiNavigationArrowBold,
  PiNotebook,
  PiNotePencilBold,
  PiPersonSimpleCircle,
  PiPlus,
  PiSignOut,
  PiSquaresFour,
  PiSun,
  PiSunDimBold,
  PiUserFocus,
  PiUsers,
  PiVideoCameraBold,
  PiWarningDiamond,
  PiWrench,
} from 'react-icons/pi';
import { MenuItem } from '../../../types/ui/menu.types.js';

export function userNavigation(navigate: UseNavigateResult<string>, toggleTheme: () => unknown): MenuItemType[] {
  return [
    { key: 'theme', label: 'Theme wechseln', onClick: () => toggleTheme(), icon: <PiSun /> },
    { key: 'signout', label: 'Abmelden', onClick: () => navigate({ to: '/auth/signout' }), icon: <PiSignOut /> },
  ];
}

export function navigation(navigate: UseNavigateResult<string>): MenuItem[] {
  return [
    {
      type: 'item',
      key: '/app',
      label: 'Dashboard',
      icon: <PiGauge size={24} />,
      onClick: () => navigate({ to: '/app' }),
    },
    {
      type: 'group',
      label: 'Einsatz',
      children: [
        {
          type: 'item',
          key: '/app/einsatztagebuch',
          label: 'Einsatztagebuch',
          icon: <PiNotebook size={24} />,
          onClick: () => navigate({ to: '/app/einsatztagebuch' }),
        },
        {
          type: 'submenu',
          key: 'kräfte',
          label: 'Kräfte',
          icon: <PiPersonSimpleCircle size={24} />,
          children: [
            {
              type: 'item',
              key: '/app/kräfte',
              label: 'Kräfte Übersicht',
              icon: <PiSquaresFour size={24} />,
              onClick: () => navigate({ to: '/app/kräfte' }),
            },
            {
              type: 'item',
              key: '/app/fahrzeuge',
              label: 'Fahrzeuge',
              icon: <PiAmbulance size={24} />,
              onClick: () => navigate({ to: '/app/fahrzeuge' }),
            },
            {
              type: 'item',
              key: '/app/einsatzkräfte',
              label: 'Einsatzkräfte',
              icon: <PiUserFocus size={24} />,
              onClick: () => navigate({ to: '/app/einsatzkräfte' }),
            },
            {
              type: 'item',
              key: '/app/rollen',
              label: 'Rollen',
              icon: <PiUsers size={24} />,
              onClick: () => navigate({ to: '/app/rollen' }),
            },
          ],
        },
        {
          type: 'submenu',
          key: 'betroffene',
          label: 'Betroffene & Patienten',
          icon: <PiFirstAid size={24} />,
          children: [
            {
              type: 'item',
              key: '/app/betroffene',
              label: 'Betroffene Übersicht',
              icon: <PiSquaresFour size={24} />,
              onClick: () => navigate({ to: '/app/betroffene' }),
            },
            {
              type: 'item',
              key: '/app/betroffene/aufnehmen',
              label: 'Aufnehmen',
              icon: <PiPlus size={24} />,
              onClick: () => navigate({ to: '/app/betroffene/aufnehmen' }),
            },
            {
              type: 'item',
              key: '/app/betroffene/verwalten',
              label: 'Verwalten',
              icon: <PiUsers size={24} />,
              onClick: () => navigate({ to: '/app/betroffene/verwalten' }),
            },
          ],
        },
        {
          type: 'submenu',
          key: 'anforderungen',
          label: 'Anforderungen',
          icon: <PiClipboardText size={24} />,
          children: [
            {
              type: 'item',
              key: '/app/anforderungen',
              label: 'Anforderungen Übersicht',
              icon: <PiSquaresFour size={24} />,
              onClick: () => navigate({ to: '/app/anforderungen' }),
            },
            {
              type: 'item',
              key: '/app/anforderungen/neu',
              label: 'Neue Anforderung',
              icon: <PiPlus size={24} />,
              onClick: () => navigate({ to: '/app/anforderungen/neu' }),
            },
            {
              type: 'item',
              key: '/app/anforderungen/verlauf',
              label: 'Anforderungsverlauf',
              icon: <PiClockClockwise size={24} />,
              onClick: () => navigate({ to: '/app/anforderungen/verlauf' }),
            },
          ],
        },
      ],
    },
    {
      type: 'group',
      label: 'Lageübersicht',
      children: [
        {
          type: 'submenu',
          key: 'lagekarte',
          label: 'Lagekarte',
          icon: <PiMapTrifold size={24} />,
          children: [
            {
              type: 'item',
              key: '/app/lagekarte',
              label: 'Lagekarte Übersicht',
              icon: <PiSquaresFour size={24} />,
              onClick: () => navigate({ to: '/app/lagekarte' }),
            },
            {
              type: 'item',
              key: '/app/lagekarte/letzte-eintraege',
              label: 'Letzte Einträge',
              icon: <PiClock size={24} />,
              onClick: () => navigate({ to: '/app/lagekarte/letzte-eintraege' }),
            },
            {
              type: 'item',
              key: '/app/lagekarte/dwd-wetterkarte',
              label: 'DWD Wetterkarte',
              icon: <PiCloud size={24} />,
              onClick: () => navigate({ to: '/app/lagekarte/dwd-wetterkarte' }),
            },
          ],
        },
        {
          type: 'submenu',
          key: 'uav',
          label: 'UAV',
          icon: <PiDrone size={24} />,
          children: [
            {
              type: 'item',
              key: '/app/uav',
              label: 'UAV Übersicht',
              icon: <PiSquaresFour size={24} />,
              onClick: () => navigate({ to: '/app/uav' }),
            },
            {
              type: 'item',
              key: '/app/uav/flugaufträge',
              label: 'Flugaufträge',
              icon: <PiDrone size={24} />,
              onClick: () => navigate({ to: '/app/uav/flugaufträge' }),
            },
            {
              type: 'item',
              key: '/app/uav/flugzonen',
              label: 'Flugzonen',
              icon: <PiMapPinLineBold size={24} />,
              onClick: () => navigate({ to: '/app/uav/flugzonen' }),
            },
            {
              type: 'item',
              key: '/app/uav/routen',
              label: 'Flugrouten',
              icon: <PiNavigationArrowBold size={24} />,
              onClick: () => navigate({ to: '/app/uav/routen' }),
            },
            {
              type: 'item',
              key: '/app/uav/wetter',
              label: 'Wetter',
              icon: <PiSunDimBold size={24} />,
              onClick: () => navigate({ to: '/app/uav/wetter' }),
            },
            {
              type: 'item',
              key: '/app/uav/stream',
              label: 'Live-Stream',
              icon: <PiVideoCameraBold size={24} />,
              onClick: () => navigate({ to: '/app/uav/stream' }),
            },
            {
              type: 'item',
              key: '/app/uav/telemetrie',
              label: 'Telemetrie',
              icon: <PiGaugeBold size={24} />,
              onClick: () => navigate({ to: '/app/uav/telemetrie' }),
            },
            {
              type: 'item',
              key: '/app/uav/protokoll',
              label: 'Flugprotokoll',
              icon: <PiClipboardBold size={24} />,
              onClick: () => navigate({ to: '/app/uav/protokoll' }),
            },
            {
              type: 'item',
              key: '/app/uav/bericht',
              label: 'Flugbericht',
              icon: <PiNotePencilBold size={24} />,
              onClick: () => navigate({ to: '/app/uav/bericht' }),
            },
          ],
        },
      ],
    },
    {
      type: 'group',
      label: 'Einsatzinformationen',
      children: [
        {
          type: 'item',
          key: '/app/einsatzdaten',
          label: 'Einsatzdaten',
          icon: <PiInfo size={24} />,
          onClick: () => navigate({ to: '/app/einsatzdaten' }),
        },
        {
          type: 'item',
          key: '/app/einsatzabschnitte',
          label: 'Einsatzabschnitte',
          icon: <PiChartPie size={24} />,
          onClick: () => navigate({ to: '/app/einsatzabschnitte' }),
        },
        {
          type: 'submenu',
          key: 'schaden',
          label: 'Schäden',
          icon: <PiWrench size={24} />,
          children: [
            {
              type: 'item',
              key: '/app/schaden',
              label: 'Schäden Übersicht',
              icon: <PiSquaresFour size={24} />,
              onClick: () => navigate({ to: '/app/schaden' }),
            },
            {
              type: 'item',
              key: '/app/schaden/personenschaden',
              label: 'Personenschaden',
              icon: <PiPlus size={24} />,
              onClick: () => navigate({ to: '/app/schaden/personenschaden' }),
            },
            {
              type: 'item',
              key: '/app/schaden/sachschaden',
              label: 'Sachschaden',
              icon: <PiUsers size={24} />,
              onClick: () => navigate({ to: '/app/schaden/sachschaden' }),
            },
          ],
        },
        {
          type: 'item',
          key: '/app/gefahren',
          label: 'Gefahren',
          icon: <PiWarningDiamond size={24} />,
          onClick: () => navigate({ to: '/app/gefahren' }),
        },
      ],
    },
    {
      type: 'item',
      key: '/app/notizen',
      label: 'Notizen & Erinnerungen',
      icon: <PiChecks size={24} />,
      onClick: () => navigate({ to: '/app/notizen' }),
    },
  ];
}
