INSERT INTO "optaOrt" ("id", "label", "optaCode", "categoryId")
VALUES
    -- Städte und Gemeinden (Codes 01-09)
    (generate_cuid(), 'Städte und Gemeinden', 1,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Städte und Gemeinden', 2,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Städte und Gemeinden', 3,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Städte und Gemeinden', 4,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Städte und Gemeinden', 5,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Städte und Gemeinden', 6,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Städte und Gemeinden', 7,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Städte und Gemeinden', 8,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Städte und Gemeinden', 9,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),

    -- Gemeinden (Codes 10-39)
    (generate_cuid(), 'Gemeinden / FF', 10,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 11,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 12,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 13,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 14,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 15,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 16,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 17,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 18,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 19,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 20,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 21,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 22,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 23,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 24,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 25,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 26,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 27,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 28,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 29,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 30,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 31,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 32,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 33,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 34,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 35,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 36,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 37,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 38,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),
    (generate_cuid(), 'Gemeinden / FF', 39,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Städte und Gemeinden')),

    -- DRK (Codes 40-48)
    (generate_cuid(), 'DRK', 40, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DRK', 41, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DRK', 42, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DRK', 43, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DRK', 44, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DRK', 45, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DRK', 46, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DRK', 47, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DRK', 48, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),

    -- JUH (Codes 49-56)
    (generate_cuid(), 'JUH', 49, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'JUH', 50, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'JUH', 51, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'JUH', 52, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'JUH', 53, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'JUH', 54, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'JUH', 55, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'JUH', 56, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),

    -- MHD (Codes 57-63)
    (generate_cuid(), 'MHD', 57, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'MHD', 58, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'MHD', 59, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'MHD', 60, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'MHD', 61, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'MHD', 62, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'MHD', 63, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),

    -- ASB (Codes 64-70)
    (generate_cuid(), 'ASB', 64, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'ASB', 65, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'ASB', 66, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'ASB', 67, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'ASB', 68, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'ASB', 69, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'ASB', 70, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),

    -- DLRG (Codes 71-77)
    (generate_cuid(), 'DLRG', 71, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DLRG', 72, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DLRG', 73, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DLRG', 74, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DLRG', 75, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DLRG', 76, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),
    (generate_cuid(), 'DLRG', 77, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Hilfsorganisationen')),

    -- Sonstige Organisationen (Codes 78-79)
    (generate_cuid(), 'Sonstige', 78,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Sonstige Organisationen')),
    (generate_cuid(), 'Sonstige', 79,
     (SELECT "id" FROM "optaCategory" WHERE "label" = 'Sonstige Organisationen')),

    -- Kommunale Behörden (Codes 80-90)
    (generate_cuid(), 'Funkgeräte', 80, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),
    (generate_cuid(), 'Funkgeräte', 81, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),
    (generate_cuid(), 'Funkgeräte', 82, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),
    (generate_cuid(), 'Funkgeräte', 83, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),
    (generate_cuid(), 'Funkgeräte', 84, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),
    (generate_cuid(), 'Funkgeräte', 85, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),
    (generate_cuid(), 'Funkgeräte', 86, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),
    (generate_cuid(), 'Funkgeräte', 87, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),
    (generate_cuid(), 'Funkgeräte', 88, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),
    (generate_cuid(), 'Funkgeräte', 89, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),
    (generate_cuid(), 'Funkgeräte', 90, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Kommunale Behörden')),

    -- Spezialfunktionen (Codes 91-94)
    (generate_cuid(), 'Intensivtransport', 91, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Spezialfunktionen')),
    (generate_cuid(), 'Waldbrandbeauftragte', 92, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Spezialfunktionen')),
    (generate_cuid(), 'Werkfeuerwehren', 93, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Spezialfunktionen')),
    (generate_cuid(), 'Werkfeuerwehren', 94, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Spezialfunktionen')),

    -- Reservierte Codes (Codes 95-96 und 98)
    (generate_cuid(), 'Gesperrt', 95, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Reservierte Codes')),
    (generate_cuid(), 'Gesperrt', 96, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Reservierte Codes')),
    (generate_cuid(), 'Gesperrt', 98, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Reservierte Codes')),

    -- Weitere Spezialfunktionen (Codes 97 und 99)
    (generate_cuid(), 'Führungskräfte Rettungsdienst', 97, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Spezialfunktionen')),
    (generate_cuid(), 'Führungskräfte der Kreisfeuerwehr und der kreisfreien Städte', 99, (SELECT "id" FROM "optaCategory" WHERE "label" = 'Spezialfunktionen'))
ON CONFLICT ("optaCode") DO NOTHING;
