/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as AppImport } from './routes/app';
import { Route as AdminIndexImport } from './routes/admin/index';
import { Route as AuthSignoutImport } from './routes/auth/signout';

// Create Virtual Routes

const SigninLazyImport = createFileRoute('/signin')();
const SetupEinsatzLazyImport = createFileRoute('/setupEinsatz')();
const IndexLazyImport = createFileRoute('/')();
const AppIndexLazyImport = createFileRoute('/app/')();
const PrestartSettingsLazyImport = createFileRoute('/prestart/settings')();
const AppSchadenLazyImport = createFileRoute('/app/schaden')();
const AppNotizenLazyImport = createFileRoute('/app/notizen')();
const AppLagekarteLazyImport = createFileRoute('/app/lagekarte')();
const AppGefahrenLazyImport = createFileRoute('/app/gefahren')();
const AppEinsatztagebuchLazyImport = createFileRoute('/app/einsatztagebuch')();
const AppEinsatzdatenLazyImport = createFileRoute('/app/einsatzdaten')();
const AppEinheitenLazyImport = createFileRoute('/app/einheiten')();
const AppBetroffeneLazyImport = createFileRoute('/app/betroffene')();

// Create/Update Routes

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route));

const SetupEinsatzLazyRoute = SetupEinsatzLazyImport.update({
  path: '/setupEinsatz',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/setupEinsatz.lazy').then((d) => d.Route));

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any);

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route));

const AppIndexLazyRoute = AppIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/index.lazy').then((d) => d.Route));

const AdminIndexRoute = AdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any);

const PrestartSettingsLazyRoute = PrestartSettingsLazyImport.update({
  path: '/prestart/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/prestart/settings.lazy').then((d) => d.Route));

const AppSchadenLazyRoute = AppSchadenLazyImport.update({
  path: '/schaden',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/schaden.lazy').then((d) => d.Route));

const AppNotizenLazyRoute = AppNotizenLazyImport.update({
  path: '/notizen',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/notizen.lazy').then((d) => d.Route));

const AppLagekarteLazyRoute = AppLagekarteLazyImport.update({
  path: '/lagekarte',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/lagekarte.lazy').then((d) => d.Route));

const AppGefahrenLazyRoute = AppGefahrenLazyImport.update({
  path: '/gefahren',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/gefahren.lazy').then((d) => d.Route));

const AppEinsatztagebuchLazyRoute = AppEinsatztagebuchLazyImport.update({
  path: '/einsatztagebuch',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/einsatztagebuch.lazy').then((d) => d.Route));

const AppEinsatzdatenLazyRoute = AppEinsatzdatenLazyImport.update({
  path: '/einsatzdaten',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/einsatzdaten.lazy').then((d) => d.Route));

const AppEinheitenLazyRoute = AppEinheitenLazyImport.update({
  path: '/einheiten',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/einheiten.lazy').then((d) => d.Route));

const AppBetroffeneLazyRoute = AppBetroffeneLazyImport.update({
  path: '/betroffene',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/betroffene.lazy').then((d) => d.Route));

const AuthSignoutRoute = AuthSignoutImport.update({
  path: '/auth/signout',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/app': {
      id: '/app';
      path: '/app';
      fullPath: '/app';
      preLoaderRoute: typeof AppImport;
      parentRoute: typeof rootRoute;
    };
    '/setupEinsatz': {
      id: '/setupEinsatz';
      path: '/setupEinsatz';
      fullPath: '/setupEinsatz';
      preLoaderRoute: typeof SetupEinsatzLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/signin': {
      id: '/signin';
      path: '/signin';
      fullPath: '/signin';
      preLoaderRoute: typeof SigninLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/auth/signout': {
      id: '/auth/signout';
      path: '/auth/signout';
      fullPath: '/auth/signout';
      preLoaderRoute: typeof AuthSignoutImport;
      parentRoute: typeof rootRoute;
    };
    '/app/betroffene': {
      id: '/app/betroffene';
      path: '/betroffene';
      fullPath: '/app/betroffene';
      preLoaderRoute: typeof AppBetroffeneLazyImport;
      parentRoute: typeof AppImport;
    };
    '/app/einheiten': {
      id: '/app/einheiten';
      path: '/einheiten';
      fullPath: '/app/einheiten';
      preLoaderRoute: typeof AppEinheitenLazyImport;
      parentRoute: typeof AppImport;
    };
    '/app/einsatzdaten': {
      id: '/app/einsatzdaten';
      path: '/einsatzdaten';
      fullPath: '/app/einsatzdaten';
      preLoaderRoute: typeof AppEinsatzdatenLazyImport;
      parentRoute: typeof AppImport;
    };
    '/app/einsatztagebuch': {
      id: '/app/einsatztagebuch';
      path: '/einsatztagebuch';
      fullPath: '/app/einsatztagebuch';
      preLoaderRoute: typeof AppEinsatztagebuchLazyImport;
      parentRoute: typeof AppImport;
    };
    '/app/gefahren': {
      id: '/app/gefahren';
      path: '/gefahren';
      fullPath: '/app/gefahren';
      preLoaderRoute: typeof AppGefahrenLazyImport;
      parentRoute: typeof AppImport;
    };
    '/app/lagekarte': {
      id: '/app/lagekarte';
      path: '/lagekarte';
      fullPath: '/app/lagekarte';
      preLoaderRoute: typeof AppLagekarteLazyImport;
      parentRoute: typeof AppImport;
    };
    '/app/notizen': {
      id: '/app/notizen';
      path: '/notizen';
      fullPath: '/app/notizen';
      preLoaderRoute: typeof AppNotizenLazyImport;
      parentRoute: typeof AppImport;
    };
    '/app/schaden': {
      id: '/app/schaden';
      path: '/schaden';
      fullPath: '/app/schaden';
      preLoaderRoute: typeof AppSchadenLazyImport;
      parentRoute: typeof AppImport;
    };
    '/prestart/settings': {
      id: '/prestart/settings';
      path: '/prestart/settings';
      fullPath: '/prestart/settings';
      preLoaderRoute: typeof PrestartSettingsLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/admin/': {
      id: '/admin/';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/app/': {
      id: '/app/';
      path: '/';
      fullPath: '/app/';
      preLoaderRoute: typeof AppIndexLazyImport;
      parentRoute: typeof AppImport;
    };
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppBetroffeneLazyRoute: typeof AppBetroffeneLazyRoute;
  AppEinheitenLazyRoute: typeof AppEinheitenLazyRoute;
  AppEinsatzdatenLazyRoute: typeof AppEinsatzdatenLazyRoute;
  AppEinsatztagebuchLazyRoute: typeof AppEinsatztagebuchLazyRoute;
  AppGefahrenLazyRoute: typeof AppGefahrenLazyRoute;
  AppLagekarteLazyRoute: typeof AppLagekarteLazyRoute;
  AppNotizenLazyRoute: typeof AppNotizenLazyRoute;
  AppSchadenLazyRoute: typeof AppSchadenLazyRoute;
  AppIndexLazyRoute: typeof AppIndexLazyRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppBetroffeneLazyRoute: AppBetroffeneLazyRoute,
  AppEinheitenLazyRoute: AppEinheitenLazyRoute,
  AppEinsatzdatenLazyRoute: AppEinsatzdatenLazyRoute,
  AppEinsatztagebuchLazyRoute: AppEinsatztagebuchLazyRoute,
  AppGefahrenLazyRoute: AppGefahrenLazyRoute,
  AppLagekarteLazyRoute: AppLagekarteLazyRoute,
  AppNotizenLazyRoute: AppNotizenLazyRoute,
  AppSchadenLazyRoute: AppSchadenLazyRoute,
  AppIndexLazyRoute: AppIndexLazyRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute;
  '/app': typeof AppRouteWithChildren;
  '/setupEinsatz': typeof SetupEinsatzLazyRoute;
  '/signin': typeof SigninLazyRoute;
  '/auth/signout': typeof AuthSignoutRoute;
  '/app/betroffene': typeof AppBetroffeneLazyRoute;
  '/app/einheiten': typeof AppEinheitenLazyRoute;
  '/app/einsatzdaten': typeof AppEinsatzdatenLazyRoute;
  '/app/einsatztagebuch': typeof AppEinsatztagebuchLazyRoute;
  '/app/gefahren': typeof AppGefahrenLazyRoute;
  '/app/lagekarte': typeof AppLagekarteLazyRoute;
  '/app/notizen': typeof AppNotizenLazyRoute;
  '/app/schaden': typeof AppSchadenLazyRoute;
  '/prestart/settings': typeof PrestartSettingsLazyRoute;
  '/admin': typeof AdminIndexRoute;
  '/app/': typeof AppIndexLazyRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute;
  '/setupEinsatz': typeof SetupEinsatzLazyRoute;
  '/signin': typeof SigninLazyRoute;
  '/auth/signout': typeof AuthSignoutRoute;
  '/app/betroffene': typeof AppBetroffeneLazyRoute;
  '/app/einheiten': typeof AppEinheitenLazyRoute;
  '/app/einsatzdaten': typeof AppEinsatzdatenLazyRoute;
  '/app/einsatztagebuch': typeof AppEinsatztagebuchLazyRoute;
  '/app/gefahren': typeof AppGefahrenLazyRoute;
  '/app/lagekarte': typeof AppLagekarteLazyRoute;
  '/app/notizen': typeof AppNotizenLazyRoute;
  '/app/schaden': typeof AppSchadenLazyRoute;
  '/prestart/settings': typeof PrestartSettingsLazyRoute;
  '/admin': typeof AdminIndexRoute;
  '/app': typeof AppIndexLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexLazyRoute;
  '/app': typeof AppRouteWithChildren;
  '/setupEinsatz': typeof SetupEinsatzLazyRoute;
  '/signin': typeof SigninLazyRoute;
  '/auth/signout': typeof AuthSignoutRoute;
  '/app/betroffene': typeof AppBetroffeneLazyRoute;
  '/app/einheiten': typeof AppEinheitenLazyRoute;
  '/app/einsatzdaten': typeof AppEinsatzdatenLazyRoute;
  '/app/einsatztagebuch': typeof AppEinsatztagebuchLazyRoute;
  '/app/gefahren': typeof AppGefahrenLazyRoute;
  '/app/lagekarte': typeof AppLagekarteLazyRoute;
  '/app/notizen': typeof AppNotizenLazyRoute;
  '/app/schaden': typeof AppSchadenLazyRoute;
  '/prestart/settings': typeof PrestartSettingsLazyRoute;
  '/admin/': typeof AdminIndexRoute;
  '/app/': typeof AppIndexLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/app'
    | '/setupEinsatz'
    | '/signin'
    | '/auth/signout'
    | '/app/betroffene'
    | '/app/einheiten'
    | '/app/einsatzdaten'
    | '/app/einsatztagebuch'
    | '/app/gefahren'
    | '/app/lagekarte'
    | '/app/notizen'
    | '/app/schaden'
    | '/prestart/settings'
    | '/admin'
    | '/app/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/setupEinsatz'
    | '/signin'
    | '/auth/signout'
    | '/app/betroffene'
    | '/app/einheiten'
    | '/app/einsatzdaten'
    | '/app/einsatztagebuch'
    | '/app/gefahren'
    | '/app/lagekarte'
    | '/app/notizen'
    | '/app/schaden'
    | '/prestart/settings'
    | '/admin'
    | '/app';
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/setupEinsatz'
    | '/signin'
    | '/auth/signout'
    | '/app/betroffene'
    | '/app/einheiten'
    | '/app/einsatzdaten'
    | '/app/einsatztagebuch'
    | '/app/gefahren'
    | '/app/lagekarte'
    | '/app/notizen'
    | '/app/schaden'
    | '/prestart/settings'
    | '/admin/'
    | '/app/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  AppRoute: typeof AppRouteWithChildren;
  SetupEinsatzLazyRoute: typeof SetupEinsatzLazyRoute;
  SigninLazyRoute: typeof SigninLazyRoute;
  AuthSignoutRoute: typeof AuthSignoutRoute;
  PrestartSettingsLazyRoute: typeof PrestartSettingsLazyRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AppRoute: AppRouteWithChildren,
  SetupEinsatzLazyRoute: SetupEinsatzLazyRoute,
  SigninLazyRoute: SigninLazyRoute,
  AuthSignoutRoute: AuthSignoutRoute,
  PrestartSettingsLazyRoute: PrestartSettingsLazyRoute,
  AdminIndexRoute: AdminIndexRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/setupEinsatz",
        "/signin",
        "/auth/signout",
        "/prestart/settings",
        "/admin/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/betroffene",
        "/app/einheiten",
        "/app/einsatzdaten",
        "/app/einsatztagebuch",
        "/app/gefahren",
        "/app/lagekarte",
        "/app/notizen",
        "/app/schaden",
        "/app/"
      ]
    },
    "/setupEinsatz": {
      "filePath": "setupEinsatz.lazy.tsx"
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/auth/signout": {
      "filePath": "auth/signout.tsx"
    },
    "/app/betroffene": {
      "filePath": "app/betroffene.lazy.tsx",
      "parent": "/app"
    },
    "/app/einheiten": {
      "filePath": "app/einheiten.lazy.tsx",
      "parent": "/app"
    },
    "/app/einsatzdaten": {
      "filePath": "app/einsatzdaten.lazy.tsx",
      "parent": "/app"
    },
    "/app/einsatztagebuch": {
      "filePath": "app/einsatztagebuch.lazy.tsx",
      "parent": "/app"
    },
    "/app/gefahren": {
      "filePath": "app/gefahren.lazy.tsx",
      "parent": "/app"
    },
    "/app/lagekarte": {
      "filePath": "app/lagekarte.lazy.tsx",
      "parent": "/app"
    },
    "/app/notizen": {
      "filePath": "app/notizen.lazy.tsx",
      "parent": "/app"
    },
    "/app/schaden": {
      "filePath": "app/schaden.lazy.tsx",
      "parent": "/app"
    },
    "/prestart/settings": {
      "filePath": "prestart/settings.lazy.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/app/": {
      "filePath": "app/index.lazy.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
