/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/app'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AuthSignoutImport } from './routes/auth/signout'

// Create Virtual Routes

const SigninLazyImport = createFileRoute('/signin')()
const SetupEinsatzLazyImport = createFileRoute('/setupEinsatz')()
const DocsLazyImport = createFileRoute('/docs')()
const IndexLazyImport = createFileRoute('/')()
const DocsIndexLazyImport = createFileRoute('/docs/')()
const AppIndexLazyImport = createFileRoute('/app/')()
const PrestartSettingsLazyImport = createFileRoute('/prestart/settings')()
const AppLagekarteLazyImport = createFileRoute('/app/lagekarte')()
const AppEinsatztagebuchLazyImport = createFileRoute('/app/einsatztagebuch')()
const AppEinsatzdatenLazyImport = createFileRoute('/app/einsatzdaten')()
const AppEinheitenLazyImport = createFileRoute('/app/einheiten')()
const AppBetroffeneLazyImport = createFileRoute('/app/betroffene')()

// Create/Update Routes

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const SetupEinsatzLazyRoute = SetupEinsatzLazyImport.update({
  path: '/setupEinsatz',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/setupEinsatz.lazy').then((d) => d.Route))

const DocsLazyRoute = DocsLazyImport.update({
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/docs.lazy').then((d) => d.Route))

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DocsIndexLazyRoute = DocsIndexLazyImport.update({
  path: '/',
  getParentRoute: () => DocsLazyRoute,
} as any).lazy(() => import('./routes/docs/index.lazy').then((d) => d.Route))

const AppIndexLazyRoute = AppIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/index.lazy').then((d) => d.Route))

const AdminIndexRoute = AdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const PrestartSettingsLazyRoute = PrestartSettingsLazyImport.update({
  path: '/prestart/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/prestart/settings.lazy').then((d) => d.Route),
)

const AppLagekarteLazyRoute = AppLagekarteLazyImport.update({
  path: '/lagekarte',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/lagekarte.lazy').then((d) => d.Route))

const AppEinsatztagebuchLazyRoute = AppEinsatztagebuchLazyImport.update({
  path: '/einsatztagebuch',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/app/einsatztagebuch.lazy').then((d) => d.Route),
)

const AppEinsatzdatenLazyRoute = AppEinsatzdatenLazyImport.update({
  path: '/einsatzdaten',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/app/einsatzdaten.lazy').then((d) => d.Route),
)

const AppEinheitenLazyRoute = AppEinheitenLazyImport.update({
  path: '/einheiten',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/app/einheiten.lazy').then((d) => d.Route))

const AppBetroffeneLazyRoute = AppBetroffeneLazyImport.update({
  path: '/betroffene',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/app/betroffene.lazy').then((d) => d.Route),
)

const AuthSignoutRoute = AuthSignoutImport.update({
  path: '/auth/signout',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsLazyImport
      parentRoute: typeof rootRoute
    }
    '/setupEinsatz': {
      id: '/setupEinsatz'
      path: '/setupEinsatz'
      fullPath: '/setupEinsatz'
      preLoaderRoute: typeof SetupEinsatzLazyImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/signout': {
      id: '/auth/signout'
      path: '/auth/signout'
      fullPath: '/auth/signout'
      preLoaderRoute: typeof AuthSignoutImport
      parentRoute: typeof rootRoute
    }
    '/app/betroffene': {
      id: '/app/betroffene'
      path: '/betroffene'
      fullPath: '/app/betroffene'
      preLoaderRoute: typeof AppBetroffeneLazyImport
      parentRoute: typeof AppImport
    }
    '/app/einheiten': {
      id: '/app/einheiten'
      path: '/einheiten'
      fullPath: '/app/einheiten'
      preLoaderRoute: typeof AppEinheitenLazyImport
      parentRoute: typeof AppImport
    }
    '/app/einsatzdaten': {
      id: '/app/einsatzdaten'
      path: '/einsatzdaten'
      fullPath: '/app/einsatzdaten'
      preLoaderRoute: typeof AppEinsatzdatenLazyImport
      parentRoute: typeof AppImport
    }
    '/app/einsatztagebuch': {
      id: '/app/einsatztagebuch'
      path: '/einsatztagebuch'
      fullPath: '/app/einsatztagebuch'
      preLoaderRoute: typeof AppEinsatztagebuchLazyImport
      parentRoute: typeof AppImport
    }
    '/app/lagekarte': {
      id: '/app/lagekarte'
      path: '/lagekarte'
      fullPath: '/app/lagekarte'
      preLoaderRoute: typeof AppLagekarteLazyImport
      parentRoute: typeof AppImport
    }
    '/prestart/settings': {
      id: '/prestart/settings'
      path: '/prestart/settings'
      fullPath: '/prestart/settings'
      preLoaderRoute: typeof PrestartSettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof AppImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexLazyImport
      parentRoute: typeof DocsLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AppRoute: AppRoute.addChildren({
    AppBetroffeneLazyRoute,
    AppEinheitenLazyRoute,
    AppEinsatzdatenLazyRoute,
    AppEinsatztagebuchLazyRoute,
    AppLagekarteLazyRoute,
    AppIndexLazyRoute,
  }),
  DocsLazyRoute: DocsLazyRoute.addChildren({ DocsIndexLazyRoute }),
  SetupEinsatzLazyRoute,
  SigninLazyRoute,
  AuthSignoutRoute,
  PrestartSettingsLazyRoute,
  AdminIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/docs",
        "/setupEinsatz",
        "/signin",
        "/auth/signout",
        "/prestart/settings",
        "/admin/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/betroffene",
        "/app/einheiten",
        "/app/einsatzdaten",
        "/app/einsatztagebuch",
        "/app/lagekarte",
        "/app/"
      ]
    },
    "/docs": {
      "filePath": "docs.lazy.tsx",
      "children": [
        "/docs/"
      ]
    },
    "/setupEinsatz": {
      "filePath": "setupEinsatz.lazy.tsx"
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/auth/signout": {
      "filePath": "auth/signout.tsx"
    },
    "/app/betroffene": {
      "filePath": "app/betroffene.lazy.tsx",
      "parent": "/app"
    },
    "/app/einheiten": {
      "filePath": "app/einheiten.lazy.tsx",
      "parent": "/app"
    },
    "/app/einsatzdaten": {
      "filePath": "app/einsatzdaten.lazy.tsx",
      "parent": "/app"
    },
    "/app/einsatztagebuch": {
      "filePath": "app/einsatztagebuch.lazy.tsx",
      "parent": "/app"
    },
    "/app/lagekarte": {
      "filePath": "app/lagekarte.lazy.tsx",
      "parent": "/app"
    },
    "/prestart/settings": {
      "filePath": "prestart/settings.lazy.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/app/": {
      "filePath": "app/index.lazy.tsx",
      "parent": "/app"
    },
    "/docs/": {
      "filePath": "docs/index.lazy.tsx",
      "parent": "/docs"
    }
  }
}
ROUTE_MANIFEST_END */
