/* tslint:disable */
/* eslint-disable */

/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddVehicleToMissionDto
 */
export interface AddVehicleToMissionDto {
  /**
   *
   * @type {string}
   * @memberof AddVehicleToMissionDto
   */
  vehicleId: string;
}

/**
 * Check if a given object implements the AddVehicleToMissionDto interface.
 */
export function instanceOfAddVehicleToMissionDto(value: object): value is AddVehicleToMissionDto {
  if (!('vehicleId' in value) || value['vehicleId'] === undefined) return false;
  return true;
}

export function AddVehicleToMissionDtoFromJSON(json: any): AddVehicleToMissionDto {
  return AddVehicleToMissionDtoFromJSONTyped(json, false);
}

export function AddVehicleToMissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddVehicleToMissionDto {
  if (json == null) {
    return json;
  }
  return {
    vehicleId: json['vehicleId'],
  };
}

export function AddVehicleToMissionDtoToJSON(json: any): AddVehicleToMissionDto {
  return AddVehicleToMissionDtoToJSONTyped(json, false);
}

export function AddVehicleToMissionDtoToJSONTyped(
  value?: AddVehicleToMissionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    vehicleId: value['vehicleId'],
  };
}
