/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiPagination } from './ApiPagination';
import {
  ApiPaginationFromJSON,
  ApiPaginationFromJSONTyped,
  ApiPaginationToJSON,
  ApiPaginationToJSONTyped,
} from './ApiPagination';

/**
 *
 * @export
 * @interface ApiMeta
 */
export interface ApiMeta {
  /**
   *
   * @type {ApiPagination}
   * @memberof ApiMeta
   */
  pagination: ApiPagination;
  /**
   *
   * @type {string}
   * @memberof ApiMeta
   */
  timestamp: string;
}

/**
 * Check if a given object implements the ApiMeta interface.
 */
export function instanceOfApiMeta(value: object): value is ApiMeta {
  if (!('pagination' in value) || value['pagination'] === undefined) return false;
  if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
  return true;
}

export function ApiMetaFromJSON(json: any): ApiMeta {
  return ApiMetaFromJSONTyped(json, false);
}

export function ApiMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMeta {
  if (json == null) {
    return json;
  }
  return {
    pagination: ApiPaginationFromJSON(json['pagination']),
    timestamp: json['timestamp'],
  };
}

export function ApiMetaToJSON(json: any): ApiMeta {
  return ApiMetaToJSONTyped(json, false);
}

export function ApiMetaToJSONTyped(value?: ApiMeta | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    pagination: ApiPaginationToJSON(value['pagination']),
    timestamp: value['timestamp'],
  };
}
