/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BearbeiterDto
 */
export interface BearbeiterDto {
  /**
   *
   * @type {string}
   * @memberof BearbeiterDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof BearbeiterDto
   */
  name: string;
}

/**
 * Check if a given object implements the BearbeiterDto interface.
 */
export function instanceOfBearbeiterDto(value: object): value is BearbeiterDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function BearbeiterDtoFromJSON(json: any): BearbeiterDto {
  return BearbeiterDtoFromJSONTyped(json, false);
}

export function BearbeiterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BearbeiterDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    name: json['name'],
  };
}

export function BearbeiterDtoToJSON(json: any): BearbeiterDto {
  return BearbeiterDtoToJSONTyped(json, false);
}

export function BearbeiterDtoToJSONTyped(value?: BearbeiterDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    name: value['name'],
  };
}
