/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { BearbeiterDto } from './BearbeiterDto';
import {
  BearbeiterDtoFromJSON,
  BearbeiterDtoFromJSONTyped,
  BearbeiterDtoToJSON,
  BearbeiterDtoToJSONTyped,
} from './BearbeiterDto';

/**
 *
 * @export
 * @interface BearbeiterResponse
 */
export interface BearbeiterResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof BearbeiterResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<BearbeiterDto>}
   * @memberof BearbeiterResponse
   */
  data: Array<BearbeiterDto>;
}

/**
 * Check if a given object implements the BearbeiterResponse interface.
 */
export function instanceOfBearbeiterResponse(value: object): value is BearbeiterResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function BearbeiterResponseFromJSON(json: any): BearbeiterResponse {
  return BearbeiterResponseFromJSONTyped(json, false);
}

export function BearbeiterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BearbeiterResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(BearbeiterDtoFromJSON),
  };
}

export function BearbeiterResponseToJSON(json: any): BearbeiterResponse {
  return BearbeiterResponseToJSONTyped(json, false);
}

export function BearbeiterResponseToJSONTyped(
  value?: BearbeiterResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(BearbeiterDtoToJSON),
  };
}
