/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BearbeiterWithStatusDto
 */
export interface BearbeiterWithStatusDto {
  /**
   *
   * @type {string}
   * @memberof BearbeiterWithStatusDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof BearbeiterWithStatusDto
   */
  name: string;
  /**
   *
   * @type {boolean}
   * @memberof BearbeiterWithStatusDto
   */
  active: boolean;
  /**
   *
   * @type {string}
   * @memberof BearbeiterWithStatusDto
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof BearbeiterWithStatusDto
   */
  updatedAt: string;
}

/**
 * Check if a given object implements the BearbeiterWithStatusDto interface.
 */
export function instanceOfBearbeiterWithStatusDto(value: object): value is BearbeiterWithStatusDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('active' in value) || value['active'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function BearbeiterWithStatusDtoFromJSON(json: any): BearbeiterWithStatusDto {
  return BearbeiterWithStatusDtoFromJSONTyped(json, false);
}

export function BearbeiterWithStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BearbeiterWithStatusDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    name: json['name'],
    active: json['active'],
    createdAt: json['createdAt'],
    updatedAt: json['updatedAt'],
  };
}

export function BearbeiterWithStatusDtoToJSON(json: any): BearbeiterWithStatusDto {
  return BearbeiterWithStatusDtoToJSONTyped(json, false);
}

export function BearbeiterWithStatusDtoToJSONTyped(
  value?: BearbeiterWithStatusDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    name: value['name'],
    active: value['active'],
    createdAt: value['createdAt'],
    updatedAt: value['updatedAt'],
  };
}
