/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BosOpta
 */
export interface BosOpta {
  /**
   *
   * @type {string}
   * @memberof BosOpta
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof BosOpta
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof BosOpta
   */
  label: string;
  /**
   *
   * @type {string}
   * @memberof BosOpta
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof BosOpta
   */
  description: string;
  /**
   *
   * @type {boolean}
   * @memberof BosOpta
   */
  isActive: boolean;
  /**
   *
   * @type {string}
   * @memberof BosOpta
   */
  createdAt: string;
  /**
   *
   * @type {Date}
   * @memberof BosOpta
   */
  updatedAt: Date;
  /**
   *
   * @type {Date}
   * @memberof BosOpta
   */
  validFrom: Date;
  /**
   *
   * @type {string}
   * @memberof BosOpta
   */
  group: BosOptaGroupEnum;
  /**
   *
   * @type {string}
   * @memberof BosOpta
   */
  rufname: string;
}

/**
 * @export
 */
export const BosOptaGroupEnum = {
  Feuerwehren: 'Feuerwehren',
  Hilfsorganisationen: 'Hilfsorganisationen',
  Katastrophenschutz: 'Katastrophenschutz',
  Polizei: 'Polizei',
  SonstigeBos: 'Sonstige BOS',
} as const;
export type BosOptaGroupEnum = (typeof BosOptaGroupEnum)[keyof typeof BosOptaGroupEnum];

/**
 * Check if a given object implements the BosOpta interface.
 */
export function instanceOfBosOpta(value: object): value is BosOpta {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('label' in value) || value['label'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('validFrom' in value) || value['validFrom'] === undefined) return false;
  if (!('group' in value) || value['group'] === undefined) return false;
  if (!('rufname' in value) || value['rufname'] === undefined) return false;
  return true;
}

export function BosOptaFromJSON(json: any): BosOpta {
  return BosOptaFromJSONTyped(json, false);
}

export function BosOptaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BosOpta {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    code: json['code'],
    label: json['label'],
    type: json['type'],
    description: json['description'],
    isActive: json['isActive'],
    createdAt: json['createdAt'],
    updatedAt: new Date(json['updatedAt']),
    validFrom: new Date(json['validFrom']),
    group: json['group'],
    rufname: json['rufname'],
  };
}

export function BosOptaToJSON(json: any): BosOpta {
  return BosOptaToJSONTyped(json, false);
}

export function BosOptaToJSONTyped(value?: BosOpta | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    code: value['code'],
    label: value['label'],
    type: value['type'],
    description: value['description'],
    isActive: value['isActive'],
    createdAt: value['createdAt'],
    updatedAt: value['updatedAt'].toISOString(),
    validFrom: value['validFrom'].toISOString(),
    group: value['group'],
    rufname: value['rufname'],
  };
}
