/* tslint:disable */
/* eslint-disable */

/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChangeStatusDto
 */
export interface ChangeStatusDto {
  /**
   *
   * @type {string}
   * @memberof ChangeStatusDto
   */
  statusId: string;
}

/**
 * Check if a given object implements the ChangeStatusDto interface.
 */
export function instanceOfChangeStatusDto(value: object): value is ChangeStatusDto {
  if (!('statusId' in value) || value['statusId'] === undefined) return false;
  return true;
}

export function ChangeStatusDtoFromJSON(json: any): ChangeStatusDto {
  return ChangeStatusDtoFromJSONTyped(json, false);
}

export function ChangeStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeStatusDto {
  if (json == null) {
    return json;
  }
  return {
    statusId: json['statusId'],
  };
}

export function ChangeStatusDtoToJSON(json: any): ChangeStatusDto {
  return ChangeStatusDtoToJSONTyped(json, false);
}

export function ChangeStatusDtoToJSONTyped(value?: ChangeStatusDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    statusId: value['statusId'],
  };
}
