/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChecklisteDto
 */
export interface ChecklisteDto {
  /**
   *
   * @type {boolean}
   * @memberof ChecklisteDto
   */
  akkuGeladen: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ChecklisteDto
   */
  kameraCheck: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ChecklisteDto
   */
  propellerCheck: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ChecklisteDto
   */
  fernsteuerungCheck: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ChecklisteDto
   */
  kompassKalibriert: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ChecklisteDto
   */
  gpsVerfuegbar: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ChecklisteDto
   */
  notlandungspunkte: boolean;
}

/**
 * Check if a given object implements the ChecklisteDto interface.
 */
export function instanceOfChecklisteDto(value: object): value is ChecklisteDto {
  if (!('akkuGeladen' in value) || value['akkuGeladen'] === undefined) return false;
  if (!('kameraCheck' in value) || value['kameraCheck'] === undefined) return false;
  if (!('propellerCheck' in value) || value['propellerCheck'] === undefined) return false;
  if (!('fernsteuerungCheck' in value) || value['fernsteuerungCheck'] === undefined) return false;
  if (!('kompassKalibriert' in value) || value['kompassKalibriert'] === undefined) return false;
  if (!('gpsVerfuegbar' in value) || value['gpsVerfuegbar'] === undefined) return false;
  if (!('notlandungspunkte' in value) || value['notlandungspunkte'] === undefined) return false;
  return true;
}

export function ChecklisteDtoFromJSON(json: any): ChecklisteDto {
  return ChecklisteDtoFromJSONTyped(json, false);
}

export function ChecklisteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChecklisteDto {
  if (json == null) {
    return json;
  }
  return {
    akkuGeladen: json['akkuGeladen'],
    kameraCheck: json['kameraCheck'],
    propellerCheck: json['propellerCheck'],
    fernsteuerungCheck: json['fernsteuerungCheck'],
    kompassKalibriert: json['kompassKalibriert'],
    gpsVerfuegbar: json['gpsVerfuegbar'],
    notlandungspunkte: json['notlandungspunkte'],
  };
}

export function ChecklisteDtoToJSON(json: any): ChecklisteDto {
  return ChecklisteDtoToJSONTyped(json, false);
}

export function ChecklisteDtoToJSONTyped(value?: ChecklisteDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    akkuGeladen: value['akkuGeladen'],
    kameraCheck: value['kameraCheck'],
    propellerCheck: value['propellerCheck'],
    fernsteuerungCheck: value['fernsteuerungCheck'],
    kompassKalibriert: value['kompassKalibriert'],
    gpsVerfuegbar: value['gpsVerfuegbar'],
    notlandungspunkte: value['notlandungspunkte'],
  };
}
