/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateNotizDto
 */
export interface CreateNotizDto {
  /**
   *
   * @type {string}
   * @memberof CreateNotizDto
   */
  content: string;
}

/**
 * Check if a given object implements the CreateNotizDto interface.
 */
export function instanceOfCreateNotizDto(value: object): value is CreateNotizDto {
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function CreateNotizDtoFromJSON(json: any): CreateNotizDto {
  return CreateNotizDtoFromJSONTyped(json, false);
}

export function CreateNotizDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNotizDto {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
  };
}

export function CreateNotizDtoToJSON(json: any): CreateNotizDto {
  return CreateNotizDtoToJSONTyped(json, false);
}

export function CreateNotizDtoToJSONTyped(value?: CreateNotizDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
  };
}
