/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateUAVMissionDto
 */
export interface CreateUAVMissionDto {
  /**
   *
   * @type {string}
   * @memberof CreateUAVMissionDto
   */
  uavId: string;
  /**
   *
   * @type {string}
   * @memberof CreateUAVMissionDto
   */
  einsatzId: string;
}

/**
 * Check if a given object implements the CreateUAVMissionDto interface.
 */
export function instanceOfCreateUAVMissionDto(value: object): value is CreateUAVMissionDto {
  if (!('uavId' in value) || value['uavId'] === undefined) return false;
  if (!('einsatzId' in value) || value['einsatzId'] === undefined) return false;
  return true;
}

export function CreateUAVMissionDtoFromJSON(json: any): CreateUAVMissionDto {
  return CreateUAVMissionDtoFromJSONTyped(json, false);
}

export function CreateUAVMissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUAVMissionDto {
  if (json == null) {
    return json;
  }
  return {
    uavId: json['uavId'],
    einsatzId: json['einsatzId'],
  };
}

export function CreateUAVMissionDtoToJSON(json: any): CreateUAVMissionDto {
  return CreateUAVMissionDtoToJSONTyped(json, false);
}

export function CreateUAVMissionDtoToJSONTyped(
  value?: CreateUAVMissionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    uavId: value['uavId'],
    einsatzId: value['einsatzId'],
  };
}
