/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateUpdateUAVDto
 */
export interface CreateUpdateUAVDto {
  /**
   *
   * @type {string}
   * @memberof CreateUpdateUAVDto
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof CreateUpdateUAVDto
   */
  modell: string;
  /**
   *
   * @type {string}
   * @memberof CreateUpdateUAVDto
   */
  seriennummer: string;
  /**
   *
   * @type {string}
   * @memberof CreateUpdateUAVDto
   */
  konfiguration: string;
  /**
   *
   * @type {string}
   * @memberof CreateUpdateUAVDto
   */
  nutzlast: string;
  /**
   *
   * @type {string}
   * @memberof CreateUpdateUAVDto
   */
  firmware?: string;
  /**
   * Maximale Flugzeit in Minuten
   * @type {number}
   * @memberof CreateUpdateUAVDto
   */
  maxFlugzeit?: number;
  /**
   * Maximale Flughöhe in Metern
   * @type {number}
   * @memberof CreateUpdateUAVDto
   */
  maxFlughoehe?: number;
  /**
   * Maximale Geschwindigkeit in km/h
   * @type {number}
   * @memberof CreateUpdateUAVDto
   */
  maxGeschwindigkeit?: number;
  /**
   * Gewicht in kg
   * @type {number}
   * @memberof CreateUpdateUAVDto
   */
  gewicht?: number;
}

/**
 * Check if a given object implements the CreateUpdateUAVDto interface.
 */
export function instanceOfCreateUpdateUAVDto(value: object): value is CreateUpdateUAVDto {
  if (!('modell' in value) || value['modell'] === undefined) return false;
  if (!('seriennummer' in value) || value['seriennummer'] === undefined) return false;
  if (!('konfiguration' in value) || value['konfiguration'] === undefined) return false;
  if (!('nutzlast' in value) || value['nutzlast'] === undefined) return false;
  return true;
}

export function CreateUpdateUAVDtoFromJSON(json: any): CreateUpdateUAVDto {
  return CreateUpdateUAVDtoFromJSONTyped(json, false);
}

export function CreateUpdateUAVDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUpdateUAVDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'] == null ? undefined : json['_id'],
    modell: json['modell'],
    seriennummer: json['seriennummer'],
    konfiguration: json['konfiguration'],
    nutzlast: json['nutzlast'],
    firmware: json['firmware'] == null ? undefined : json['firmware'],
    maxFlugzeit: json['maxFlugzeit'] == null ? undefined : json['maxFlugzeit'],
    maxFlughoehe: json['maxFlughoehe'] == null ? undefined : json['maxFlughoehe'],
    maxGeschwindigkeit: json['maxGeschwindigkeit'] == null ? undefined : json['maxGeschwindigkeit'],
    gewicht: json['gewicht'] == null ? undefined : json['gewicht'],
  };
}

export function CreateUpdateUAVDtoToJSON(json: any): CreateUpdateUAVDto {
  return CreateUpdateUAVDtoToJSONTyped(json, false);
}

export function CreateUpdateUAVDtoToJSONTyped(
  value?: CreateUpdateUAVDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    modell: value['modell'],
    seriennummer: value['seriennummer'],
    konfiguration: value['konfiguration'],
    nutzlast: value['nutzlast'],
    firmware: value['firmware'],
    maxFlugzeit: value['maxFlugzeit'],
    maxFlughoehe: value['maxFlughoehe'],
    maxGeschwindigkeit: value['maxGeschwindigkeit'],
    gewicht: value['gewicht'],
  };
}
