/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateJournalEntryDto
 */
export interface CreateJournalEntryDto {
  /**
   *
   * @type {string}
   * @memberof CreateJournalEntryDto
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof CreateJournalEntryDto
   */
  type: CreateJournalEntryDtoTypeEnum;
  /**
   *
   * @type {string}
   * @memberof CreateJournalEntryDto
   */
  absender: string;
  /**
   *
   * @type {string}
   * @memberof CreateJournalEntryDto
   */
  empfaenger: string;
  /**
   *
   * @type {string}
   * @memberof CreateJournalEntryDto
   */
  timestamp: string;
}

/**
 * @export
 */
export const CreateJournalEntryDtoTypeEnum = {
  User: 'USER',
  Generisch: 'GENERISCH',
  Ressourcen: 'RESSOURCEN',
  Kommunikation: 'KOMMUNIKATION',
  Lage: 'LAGE',
  Betroffene: 'BETROFFENE',
} as const;
export type CreateJournalEntryDtoTypeEnum =
  (typeof CreateJournalEntryDtoTypeEnum)[keyof typeof CreateJournalEntryDtoTypeEnum];

/**
 * Check if a given object implements the CreateJournalEntryDto interface.
 */
export function instanceOfCreateJournalEntryDto(value: object): value is CreateJournalEntryDto {
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('absender' in value) || value['absender'] === undefined) return false;
  if (!('empfaenger' in value) || value['empfaenger'] === undefined) return false;
  if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
  return true;
}

export function CreateJournalEntryDtoFromJSON(json: any): CreateJournalEntryDto {
  return CreateJournalEntryDtoFromJSONTyped(json, false);
}

export function CreateJournalEntryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJournalEntryDto {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
    type: json['type'],
    absender: json['absender'],
    empfaenger: json['empfaenger'],
    timestamp: json['timestamp'],
  };
}

export function CreateJournalEntryDtoToJSON(json: any): CreateJournalEntryDto {
  return CreateJournalEntryDtoToJSONTyped(json, false);
}

export function CreateJournalEntryDtoToJSONTyped(
  value?: CreateJournalEntryDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
    type: value['type'],
    absender: value['absender'],
    empfaenger: value['empfaenger'],
    timestamp: value['timestamp'],
  };
}
