/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateBearbeiterDto
 */
export interface CreateBearbeiterDto {
  /**
   *
   * @type {string}
   * @memberof CreateBearbeiterDto
   */
  name: string;
}

/**
 * Check if a given object implements the CreateBearbeiterDto interface.
 */
export function instanceOfCreateBearbeiterDto(value: object): value is CreateBearbeiterDto {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function CreateBearbeiterDtoFromJSON(json: any): CreateBearbeiterDto {
  return CreateBearbeiterDtoFromJSONTyped(json, false);
}

export function CreateBearbeiterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBearbeiterDto {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function CreateBearbeiterDtoToJSON(json: any): CreateBearbeiterDto {
  return CreateBearbeiterDtoToJSONTyped(json, false);
}

export function CreateBearbeiterDtoToJSONTyped(
  value?: CreateBearbeiterDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
