/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateMissionDto
 */
export interface CreateMissionDto {
  /**
   *
   * @type {string}
   * @memberof CreateMissionDto
   */
  erstAlarmiert: string;
  /**
   *
   * @type {string}
   * @memberof CreateMissionDto
   */
  aufnehmendesRettungsmittel: string;
  /**
   *
   * @type {string}
   * @memberof CreateMissionDto
   */
  alarmstichwort: string;
  /**
   *
   * @type {string}
   * @memberof CreateMissionDto
   */
  ort: string;
}

/**
 * Check if a given object implements the CreateMissionDto interface.
 */
export function instanceOfCreateMissionDto(value: object): value is CreateMissionDto {
  if (!('erstAlarmiert' in value) || value['erstAlarmiert'] === undefined) return false;
  if (!('aufnehmendesRettungsmittel' in value) || value['aufnehmendesRettungsmittel'] === undefined) return false;
  if (!('alarmstichwort' in value) || value['alarmstichwort'] === undefined) return false;
  if (!('ort' in value) || value['ort'] === undefined) return false;
  return true;
}

export function CreateMissionDtoFromJSON(json: any): CreateMissionDto {
  return CreateMissionDtoFromJSONTyped(json, false);
}

export function CreateMissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMissionDto {
  if (json == null) {
    return json;
  }
  return {
    erstAlarmiert: json['erstAlarmiert'],
    aufnehmendesRettungsmittel: json['aufnehmendesRettungsmittel'],
    alarmstichwort: json['alarmstichwort'],
    ort: json['ort'],
  };
}

export function CreateMissionDtoToJSON(json: any): CreateMissionDto {
  return CreateMissionDtoToJSONTyped(json, false);
}

export function CreateMissionDtoToJSONTyped(
  value?: CreateMissionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    erstAlarmiert: value['erstAlarmiert'],
    aufnehmendesRettungsmittel: value['aufnehmendesRettungsmittel'],
    alarmstichwort: value['alarmstichwort'],
    ort: value['ort'],
  };
}
