/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptaDto } from './OptaDto';
import { OptaDtoFromJSON, OptaDtoFromJSONTyped, OptaDtoToJSON, OptaDtoToJSONTyped } from './OptaDto';
import type { IconDefinitionDto } from './IconDefinitionDto';
import {
  IconDefinitionDtoFromJSON,
  IconDefinitionDtoFromJSONTyped,
  IconDefinitionDtoToJSON,
  IconDefinitionDtoToJSONTyped,
} from './IconDefinitionDto';

/**
 *
 * @export
 * @interface CreateUpdateFahrzeugDto
 */
export interface CreateUpdateFahrzeugDto {
  /**
   *
   * @type {string}
   * @memberof CreateUpdateFahrzeugDto
   */
  id?: string;
  /**
   *
   * @type {OptaDto}
   * @memberof CreateUpdateFahrzeugDto
   */
  opta?: OptaDto;
  /**
   *
   * @type {IconDefinitionDto}
   * @memberof CreateUpdateFahrzeugDto
   */
  iconDefinition?: IconDefinitionDto;
}

/**
 * Check if a given object implements the CreateUpdateFahrzeugDto interface.
 */
export function instanceOfCreateUpdateFahrzeugDto(value: object): value is CreateUpdateFahrzeugDto {
  return true;
}

export function CreateUpdateFahrzeugDtoFromJSON(json: any): CreateUpdateFahrzeugDto {
  return CreateUpdateFahrzeugDtoFromJSONTyped(json, false);
}

export function CreateUpdateFahrzeugDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUpdateFahrzeugDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'] == null ? undefined : json['_id'],
    opta: json['opta'] == null ? undefined : OptaDtoFromJSON(json['opta']),
    iconDefinition: json['iconDefinition'] == null ? undefined : IconDefinitionDtoFromJSON(json['iconDefinition']),
  };
}

export function CreateUpdateFahrzeugDtoToJSON(json: any): CreateUpdateFahrzeugDto {
  return CreateUpdateFahrzeugDtoToJSONTyped(json, false);
}

export function CreateUpdateFahrzeugDtoToJSONTyped(
  value?: CreateUpdateFahrzeugDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    opta: OptaDtoToJSON(value['opta']),
    iconDefinition: IconDefinitionDtoToJSON(value['iconDefinition']),
  };
}
