/* tslint:disable */
/* eslint-disable */

/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateReminderDto
 */
export interface CreateReminderDto {
  /**
   *
   * @type {string}
   * @memberof CreateReminderDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CreateReminderDto
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof CreateReminderDto
   */
  action: string;
  /**
   *
   * @type {string}
   * @memberof CreateReminderDto
   */
  timestamp: string;
}

/**
 * Check if a given object implements the CreateReminderDto interface.
 */
export function instanceOfCreateReminderDto(value: object): value is CreateReminderDto {
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('action' in value) || value['action'] === undefined) return false;
  if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
  return true;
}

export function CreateReminderDtoFromJSON(json: any): CreateReminderDto {
  return CreateReminderDtoFromJSONTyped(json, false);
}

export function CreateReminderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReminderDto {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'],
    content: json['content'],
    action: json['action'],
    timestamp: json['timestamp'],
  };
}

export function CreateReminderDtoToJSON(json: any): CreateReminderDto {
  return CreateReminderDtoToJSONTyped(json, false);
}

export function CreateReminderDtoToJSONTyped(
  value?: CreateReminderDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    content: value['content'],
    action: value['action'],
    timestamp: value['timestamp'],
  };
}
