/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DistrictOpta
 */
export interface DistrictOpta {
  /**
   *
   * @type {string}
   * @memberof DistrictOpta
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof DistrictOpta
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof DistrictOpta
   */
  label: string;
  /**
   *
   * @type {string}
   * @memberof DistrictOpta
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof DistrictOpta
   */
  description: string;
  /**
   *
   * @type {boolean}
   * @memberof DistrictOpta
   */
  isActive: boolean;
  /**
   *
   * @type {string}
   * @memberof DistrictOpta
   */
  createdAt: string;
  /**
   *
   * @type {Date}
   * @memberof DistrictOpta
   */
  updatedAt: Date;
  /**
   *
   * @type {Date}
   * @memberof DistrictOpta
   */
  validFrom: Date;
}

/**
 * Check if a given object implements the DistrictOpta interface.
 */
export function instanceOfDistrictOpta(value: object): value is DistrictOpta {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('label' in value) || value['label'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('validFrom' in value) || value['validFrom'] === undefined) return false;
  return true;
}

export function DistrictOptaFromJSON(json: any): DistrictOpta {
  return DistrictOptaFromJSONTyped(json, false);
}

export function DistrictOptaFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistrictOpta {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    code: json['code'],
    label: json['label'],
    type: json['type'],
    description: json['description'],
    isActive: json['isActive'],
    createdAt: json['createdAt'],
    updatedAt: new Date(json['updatedAt']),
    validFrom: new Date(json['validFrom']),
  };
}

export function DistrictOptaToJSON(json: any): DistrictOpta {
  return DistrictOptaToJSONTyped(json, false);
}

export function DistrictOptaToJSONTyped(value?: DistrictOpta | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    code: value['code'],
    label: value['label'],
    type: value['type'],
    description: value['description'],
    isActive: value['isActive'],
    createdAt: value['createdAt'],
    updatedAt: value['updatedAt'].toISOString(),
    validFrom: value['validFrom'].toISOString(),
  };
}
