/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BearbeiterDto } from './BearbeiterDto';
import {
  BearbeiterDtoFromJSON,
  BearbeiterDtoFromJSONTyped,
  BearbeiterDtoToJSON,
  BearbeiterDtoToJSONTyped,
} from './BearbeiterDto';

/**
 *
 * @export
 * @interface EinsatzNoteDto
 */
export interface EinsatzNoteDto {
  /**
   *
   * @type {string}
   * @memberof EinsatzNoteDto
   */
  id: string;
  /**
   *
   * @type {BearbeiterDto}
   * @memberof EinsatzNoteDto
   */
  bearbeiter: BearbeiterDto;
  /**
   *
   * @type {string}
   * @memberof EinsatzNoteDto
   */
  content: string;
  /**
   *
   * @type {Date}
   * @memberof EinsatzNoteDto
   */
  doneAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EinsatzNoteDto
   */
  deletedAt?: Date;
  /**
   *
   * @type {string}
   * @memberof EinsatzNoteDto
   */
  createdAt: string;
}

/**
 * Check if a given object implements the EinsatzNoteDto interface.
 */
export function instanceOfEinsatzNoteDto(value: object): value is EinsatzNoteDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('bearbeiter' in value) || value['bearbeiter'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  return true;
}

export function EinsatzNoteDtoFromJSON(json: any): EinsatzNoteDto {
  return EinsatzNoteDtoFromJSONTyped(json, false);
}

export function EinsatzNoteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzNoteDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    bearbeiter: BearbeiterDtoFromJSON(json['bearbeiter']),
    content: json['content'],
    doneAt: json['doneAt'] == null ? undefined : new Date(json['doneAt']),
    deletedAt: json['deletedAt'] == null ? undefined : new Date(json['deletedAt']),
    createdAt: json['createdAt'],
  };
}

export function EinsatzNoteDtoToJSON(json: any): EinsatzNoteDto {
  return EinsatzNoteDtoToJSONTyped(json, false);
}

export function EinsatzNoteDtoToJSONTyped(value?: EinsatzNoteDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    bearbeiter: BearbeiterDtoToJSON(value['bearbeiter']),
    content: value['content'],
    doneAt: value['doneAt'] == null ? undefined : value['doneAt'].toISOString(),
    deletedAt: value['deletedAt'] == null ? undefined : value['deletedAt'].toISOString(),
    createdAt: value['createdAt'],
  };
}
