/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EinsatzMetaDto
 */
export interface EinsatzMetaDto {
  /**
   *
   * @type {string}
   * @memberof EinsatzMetaDto
   */
  ort: string;
}

/**
 * Check if a given object implements the EinsatzMetaDto interface.
 */
export function instanceOfEinsatzMetaDto(value: object): value is EinsatzMetaDto {
  if (!('ort' in value) || value['ort'] === undefined) return false;
  return true;
}

export function EinsatzMetaDtoFromJSON(json: any): EinsatzMetaDto {
  return EinsatzMetaDtoFromJSONTyped(json, false);
}

export function EinsatzMetaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzMetaDto {
  if (json == null) {
    return json;
  }
  return {
    ort: json['ort'],
  };
}

export function EinsatzMetaDtoToJSON(json: any): EinsatzMetaDto {
  return EinsatzMetaDtoToJSONTyped(json, false);
}

export function EinsatzMetaDtoToJSONTyped(value?: EinsatzMetaDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    ort: value['ort'],
  };
}
