/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EinsatzNoteDto
 */
export interface EinsatzNoteDto {
  /**
   *
   * @type {string}
   * @memberof EinsatzNoteDto
   */
  content: string;
  /**
   *
   * @type {Date}
   * @memberof EinsatzNoteDto
   */
  doneAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EinsatzNoteDto
   */
  deletedAt?: Date;
}

/**
 * Check if a given object implements the EinsatzNoteDto interface.
 */
export function instanceOfEinsatzNoteDto(value: object): value is EinsatzNoteDto {
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function EinsatzNoteDtoFromJSON(json: any): EinsatzNoteDto {
  return EinsatzNoteDtoFromJSONTyped(json, false);
}

export function EinsatzNoteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzNoteDto {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
    doneAt: json['doneAt'] == null ? undefined : new Date(json['doneAt']),
    deletedAt: json['deletedAt'] == null ? undefined : new Date(json['deletedAt']),
  };
}

export function EinsatzNoteDtoToJSON(json: any): EinsatzNoteDto {
  return EinsatzNoteDtoToJSONTyped(json, false);
}

export function EinsatzNoteDtoToJSONTyped(value?: EinsatzNoteDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
    doneAt: value['doneAt'] == null ? undefined : value['doneAt'].toISOString(),
    deletedAt: value['deletedAt'] == null ? undefined : value['deletedAt'].toISOString(),
  };
}
