/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EinsatzAlarmstichwortDto
 */
export interface EinsatzAlarmstichwortDto {
  /**
   *
   * @type {string}
   * @memberof EinsatzAlarmstichwortDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof EinsatzAlarmstichwortDto
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof EinsatzAlarmstichwortDto
   */
  description: string;
  /**
   *
   * @type {boolean}
   * @memberof EinsatzAlarmstichwortDto
   */
  isActive: boolean;
  /**
   *
   * @type {string}
   * @memberof EinsatzAlarmstichwortDto
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof EinsatzAlarmstichwortDto
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof EinsatzAlarmstichwortDto
   */
  validFrom: string;
}

/**
 * Check if a given object implements the EinsatzAlarmstichwortDto interface.
 */
export function instanceOfEinsatzAlarmstichwortDto(value: object): value is EinsatzAlarmstichwortDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('validFrom' in value) || value['validFrom'] === undefined) return false;
  return true;
}

export function EinsatzAlarmstichwortDtoFromJSON(json: any): EinsatzAlarmstichwortDto {
  return EinsatzAlarmstichwortDtoFromJSONTyped(json, false);
}

export function EinsatzAlarmstichwortDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EinsatzAlarmstichwortDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    code: json['code'],
    description: json['description'],
    isActive: json['isActive'],
    updatedAt: json['updatedAt'],
    createdAt: json['createdAt'],
    validFrom: json['validFrom'],
  };
}

export function EinsatzAlarmstichwortDtoToJSON(json: any): EinsatzAlarmstichwortDto {
  return EinsatzAlarmstichwortDtoToJSONTyped(json, false);
}

export function EinsatzAlarmstichwortDtoToJSONTyped(
  value?: EinsatzAlarmstichwortDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    code: value['code'],
    description: value['description'],
    isActive: value['isActive'],
    updatedAt: value['updatedAt'],
    createdAt: value['createdAt'],
    validFrom: value['validFrom'],
  };
}
