/* tslint:disable */
/* eslint-disable */

/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EinsatzReminderDto
 */
export interface EinsatzReminderDto {
  /**
   *
   * @type {string}
   * @memberof EinsatzReminderDto
   */
  timestamp: string;
  /**
   *
   * @type {string}
   * @memberof EinsatzReminderDto
   */
  notified: string;
  /**
   *
   * @type {string}
   * @memberof EinsatzReminderDto
   */
  read: string;
  /**
   *
   * @type {string}
   * @memberof EinsatzReminderDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof EinsatzReminderDto
   */
  content: string;
}

/**
 * Check if a given object implements the EinsatzReminderDto interface.
 */
export function instanceOfEinsatzReminderDto(value: object): value is EinsatzReminderDto {
  if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
  if (!('notified' in value) || value['notified'] === undefined) return false;
  if (!('read' in value) || value['read'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function EinsatzReminderDtoFromJSON(json: any): EinsatzReminderDto {
  return EinsatzReminderDtoFromJSONTyped(json, false);
}

export function EinsatzReminderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EinsatzReminderDto {
  if (json == null) {
    return json;
  }
  return {
    timestamp: json['timestamp'],
    notified: json['notified'],
    read: json['read'],
    title: json['title'],
    content: json['content'],
  };
}

export function EinsatzReminderDtoToJSON(json: any): EinsatzReminderDto {
  return EinsatzReminderDtoToJSONTyped(json, false);
}

export function EinsatzReminderDtoToJSONTyped(
  value?: EinsatzReminderDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    timestamp: value['timestamp'],
    notified: value['notified'],
    read: value['read'],
    title: value['title'],
    content: value['content'],
  };
}
