/* tslint:disable */
/* eslint-disable */

/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FahrzeugTypDto
 */
export interface FahrzeugTypDto {
  /**
   *
   * @type {string}
   * @memberof FahrzeugTypDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof FahrzeugTypDto
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof FahrzeugTypDto
   */
  label: string;
  /**
   *
   * @type {string}
   * @memberof FahrzeugTypDto
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof FahrzeugTypDto
   */
  type: FahrzeugTypDtoTypeEnum;
  /**
   *
   * @type {string}
   * @memberof FahrzeugTypDto
   */
  group: FahrzeugTypDtoGroupEnum;
}

/**
 * @export
 */
export const FahrzeugTypDtoTypeEnum = {
  District: 'DISTRICT',
  BosCode: 'BOS_CODE',
  LocalCode: 'LOCAL_CODE',
  FunctionCode: 'FUNCTION_CODE',
} as const;
export type FahrzeugTypDtoTypeEnum = (typeof FahrzeugTypDtoTypeEnum)[keyof typeof FahrzeugTypDtoTypeEnum];

/**
 * @export
 */
export const FahrzeugTypDtoGroupEnum = {
  OrtsfesteFunkstellen: 'Ortsfeste Funkstellen',
  Funktionskennungen: 'Funktionskennungen',
  Einsatzleitfahrzeuge: 'Einsatzleitfahrzeuge',
  Mannschaftstransport: 'Mannschaftstransport',
  Logistikfahrzeuge: 'Logistikfahrzeuge',
  Betreuungsfahrzeuge: 'Betreuungsfahrzeuge',
  Notfallrettung: 'Notfallrettung',
  VorbergehendeEinrichtungen: 'Vorübergehende Einrichtungen',
  Krankentransport: 'Krankentransport',
  Sanittsdienst: 'Sanitätsdienst',
  Spezialtransport: 'Spezialtransport',
  SonstigeTransportmittel: 'Sonstige Transportmittel',
} as const;
export type FahrzeugTypDtoGroupEnum = (typeof FahrzeugTypDtoGroupEnum)[keyof typeof FahrzeugTypDtoGroupEnum];

/**
 * Check if a given object implements the FahrzeugTypDto interface.
 */
export function instanceOfFahrzeugTypDto(value: object): value is FahrzeugTypDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('label' in value) || value['label'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('group' in value) || value['group'] === undefined) return false;
  return true;
}

export function FahrzeugTypDtoFromJSON(json: any): FahrzeugTypDto {
  return FahrzeugTypDtoFromJSONTyped(json, false);
}

export function FahrzeugTypDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FahrzeugTypDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    code: json['code'],
    label: json['label'],
    description: json['description'] == null ? undefined : json['description'],
    type: json['type'],
    group: json['group'],
  };
}

export function FahrzeugTypDtoToJSON(json: any): FahrzeugTypDto {
  return FahrzeugTypDtoToJSONTyped(json, false);
}

export function FahrzeugTypDtoToJSONTyped(value?: FahrzeugTypDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    code: value['code'],
    label: value['label'],
    description: value['description'],
    type: value['type'],
    group: value['group'],
  };
}
