/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IconDefinitionDto } from './IconDefinitionDto';
import {
  IconDefinitionDtoFromJSON,
  IconDefinitionDtoFromJSONTyped,
  IconDefinitionDtoToJSON,
  IconDefinitionDtoToJSONTyped,
} from './IconDefinitionDto';

/**
 *
 * @export
 * @interface FahrzeugeDto
 */
export interface FahrzeugeDto {
  /**
   *
   * @type {string}
   * @memberof FahrzeugeDto
   */
  fullOpta: string;
  /**
   *
   * @type {IconDefinitionDto}
   * @memberof FahrzeugeDto
   */
  iconDefinition: IconDefinitionDto;
  /**
   *
   * @type {number}
   * @memberof FahrzeugeDto
   */
  kapazitaet: number;
}

/**
 * Check if a given object implements the FahrzeugeDto interface.
 */
export function instanceOfFahrzeugeDto(value: object): value is FahrzeugeDto {
  if (!('fullOpta' in value) || value['fullOpta'] === undefined) return false;
  if (!('iconDefinition' in value) || value['iconDefinition'] === undefined) return false;
  if (!('kapazitaet' in value) || value['kapazitaet'] === undefined) return false;
  return true;
}

export function FahrzeugeDtoFromJSON(json: any): FahrzeugeDto {
  return FahrzeugeDtoFromJSONTyped(json, false);
}

export function FahrzeugeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FahrzeugeDto {
  if (json == null) {
    return json;
  }
  return {
    fullOpta: json['fullOpta'],
    iconDefinition: IconDefinitionDtoFromJSON(json['iconDefinition']),
    kapazitaet: json['kapazitaet'],
  };
}

export function FahrzeugeDtoToJSON(json: any): FahrzeugeDto {
  return FahrzeugeDtoToJSONTyped(json, false);
}

export function FahrzeugeDtoToJSONTyped(value?: FahrzeugeDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    fullOpta: value['fullOpta'],
    iconDefinition: IconDefinitionDtoToJSON(value['iconDefinition']),
    kapazitaet: value['kapazitaet'],
  };
}
