/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptaDto } from './OptaDto';
import { OptaDtoFromJSON, OptaDtoFromJSONTyped, OptaDtoToJSON, OptaDtoToJSONTyped } from './OptaDto';
import type { IconDefinitionDto } from './IconDefinitionDto';
import {
  IconDefinitionDtoFromJSON,
  IconDefinitionDtoFromJSONTyped,
  IconDefinitionDtoToJSON,
  IconDefinitionDtoToJSONTyped,
} from './IconDefinitionDto';

/**
 *
 * @export
 * @interface FahrzeugTemplateDto
 */
export interface FahrzeugTemplateDto {
  /**
   *
   * @type {string}
   * @memberof FahrzeugTemplateDto
   */
  id: string;
  /**
   *
   * @type {OptaDto}
   * @memberof FahrzeugTemplateDto
   */
  opta: OptaDto;
  /**
   *
   * @type {string}
   * @memberof FahrzeugTemplateDto
   */
  fullOpta: string;
  /**
   *
   * @type {IconDefinitionDto}
   * @memberof FahrzeugTemplateDto
   */
  iconDefinition: IconDefinitionDto;
  /**
   *
   * @type {number}
   * @memberof FahrzeugTemplateDto
   */
  kapazitaet: number;
}

/**
 * Check if a given object implements the FahrzeugTemplateDto interface.
 */
export function instanceOfFahrzeugTemplateDto(value: object): value is FahrzeugTemplateDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('opta' in value) || value['opta'] === undefined) return false;
  if (!('fullOpta' in value) || value['fullOpta'] === undefined) return false;
  if (!('iconDefinition' in value) || value['iconDefinition'] === undefined) return false;
  if (!('kapazitaet' in value) || value['kapazitaet'] === undefined) return false;
  return true;
}

export function FahrzeugTemplateDtoFromJSON(json: any): FahrzeugTemplateDto {
  return FahrzeugTemplateDtoFromJSONTyped(json, false);
}

export function FahrzeugTemplateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FahrzeugTemplateDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    opta: OptaDtoFromJSON(json['opta']),
    fullOpta: json['fullOpta'],
    iconDefinition: IconDefinitionDtoFromJSON(json['iconDefinition']),
    kapazitaet: json['kapazitaet'],
  };
}

export function FahrzeugTemplateDtoToJSON(json: any): FahrzeugTemplateDto {
  return FahrzeugTemplateDtoToJSONTyped(json, false);
}

export function FahrzeugTemplateDtoToJSONTyped(
  value?: FahrzeugTemplateDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    opta: OptaDtoToJSON(value['opta']),
    fullOpta: value['fullOpta'],
    iconDefinition: IconDefinitionDtoToJSON(value['iconDefinition']),
    kapazitaet: value['kapazitaet'],
  };
}
