/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { FlightProtocolDto } from './FlightProtocolDto';
import {
  FlightProtocolDtoFromJSON,
  FlightProtocolDtoFromJSONTyped,
  FlightProtocolDtoToJSON,
  FlightProtocolDtoToJSONTyped,
} from './FlightProtocolDto';

/**
 *
 * @export
 * @interface FlightProtocolResponse
 */
export interface FlightProtocolResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof FlightProtocolResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {FlightProtocolDto}
   * @memberof FlightProtocolResponse
   */
  data: FlightProtocolDto;
}

/**
 * Check if a given object implements the FlightProtocolResponse interface.
 */
export function instanceOfFlightProtocolResponse(value: object): value is FlightProtocolResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function FlightProtocolResponseFromJSON(json: any): FlightProtocolResponse {
  return FlightProtocolResponseFromJSONTyped(json, false);
}

export function FlightProtocolResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlightProtocolResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: FlightProtocolDtoFromJSON(json['data']),
  };
}

export function FlightProtocolResponseToJSON(json: any): FlightProtocolResponse {
  return FlightProtocolResponseToJSONTyped(json, false);
}

export function FlightProtocolResponseToJSONTyped(
  value?: FlightProtocolResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: FlightProtocolDtoToJSON(value['data']),
  };
}
