/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FlightProtocolDto
 */
export interface FlightProtocolDto {
  /**
   *
   * @type {number}
   * @memberof FlightProtocolDto
   */
  index: number;
  /**
   *
   * @type {string}
   * @memberof FlightProtocolDto
   */
  pilot: string;
  /**
   *
   * @type {string}
   * @memberof FlightProtocolDto
   */
  copilot?: string;
  /**
   *
   * @type {string}
   * @memberof FlightProtocolDto
   */
  missionsziel: string;
  /**
   *
   * @type {Date}
   * @memberof FlightProtocolDto
   */
  takeoff: Date;
  /**
   *
   * @type {Date}
   * @memberof FlightProtocolDto
   */
  landing?: Date;
  /**
   *
   * @type {string}
   * @memberof FlightProtocolDto
   */
  status: FlightProtocolDtoStatusEnum;
  /**
   *
   * @type {number}
   * @memberof FlightProtocolDto
   */
  flugdauer?: number;
  /**
   *
   * @type {number}
   * @memberof FlightProtocolDto
   */
  maxFlughoehe?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof FlightProtocolDto
   */
  besondereVorkommnisse?: Array<string>;
}

/**
 * @export
 */
export const FlightProtocolDtoStatusEnum = {
  Planned: 'PLANNED',
  Takeoff: 'TAKEOFF',
  Inflight: 'INFLIGHT',
  Landed: 'LANDED',
  Completed: 'COMPLETED',
} as const;
export type FlightProtocolDtoStatusEnum =
  (typeof FlightProtocolDtoStatusEnum)[keyof typeof FlightProtocolDtoStatusEnum];

/**
 * Check if a given object implements the FlightProtocolDto interface.
 */
export function instanceOfFlightProtocolDto(value: object): value is FlightProtocolDto {
  if (!('index' in value) || value['index'] === undefined) return false;
  if (!('pilot' in value) || value['pilot'] === undefined) return false;
  if (!('missionsziel' in value) || value['missionsziel'] === undefined) return false;
  if (!('takeoff' in value) || value['takeoff'] === undefined) return false;
  if (!('status' in value) || value['status'] === undefined) return false;
  return true;
}

export function FlightProtocolDtoFromJSON(json: any): FlightProtocolDto {
  return FlightProtocolDtoFromJSONTyped(json, false);
}

export function FlightProtocolDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlightProtocolDto {
  if (json == null) {
    return json;
  }
  return {
    index: json['index'],
    pilot: json['pilot'],
    copilot: json['copilot'] == null ? undefined : json['copilot'],
    missionsziel: json['missionsziel'],
    takeoff: new Date(json['takeoff']),
    landing: json['landing'] == null ? undefined : new Date(json['landing']),
    status: json['status'],
    flugdauer: json['flugdauer'] == null ? undefined : json['flugdauer'],
    maxFlughoehe: json['maxFlughoehe'] == null ? undefined : json['maxFlughoehe'],
    besondereVorkommnisse: json['besondereVorkommnisse'] == null ? undefined : json['besondereVorkommnisse'],
  };
}

export function FlightProtocolDtoToJSON(json: any): FlightProtocolDto {
  return FlightProtocolDtoToJSONTyped(json, false);
}

export function FlightProtocolDtoToJSONTyped(
  value?: FlightProtocolDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    index: value['index'],
    pilot: value['pilot'],
    copilot: value['copilot'],
    missionsziel: value['missionsziel'],
    takeoff: value['takeoff'].toISOString(),
    landing: value['landing'] == null ? undefined : value['landing'].toISOString(),
    status: value['status'],
    flugdauer: value['flugdauer'],
    maxFlughoehe: value['maxFlughoehe'],
    besondereVorkommnisse: value['besondereVorkommnisse'],
  };
}
