/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FunctionOptaDto
 */
export interface FunctionOptaDto {
  /**
   *
   * @type {string}
   * @memberof FunctionOptaDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof FunctionOptaDto
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof FunctionOptaDto
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof FunctionOptaDto
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof FunctionOptaDto
   */
  group: string;
  /**
   *
   * @type {boolean}
   * @memberof FunctionOptaDto
   */
  isActive: boolean;
  /**
   *
   * @type {string}
   * @memberof FunctionOptaDto
   */
  label: string;
  /**
   *
   * @type {number}
   * @memberof FunctionOptaDto
   */
  maxPersonnel: number;
  /**
   *
   * @type {number}
   * @memberof FunctionOptaDto
   */
  minPersonnel: number;
  /**
   *
   * @type {string}
   * @memberof FunctionOptaDto
   */
  type: string;
  /**
   *
   * @type {Date}
   * @memberof FunctionOptaDto
   */
  updatedAt: Date;
  /**
   *
   * @type {Date}
   * @memberof FunctionOptaDto
   */
  validFrom: Date;
}

/**
 * Check if a given object implements the FunctionOptaDto interface.
 */
export function instanceOfFunctionOptaDto(value: object): value is FunctionOptaDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('group' in value) || value['group'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  if (!('label' in value) || value['label'] === undefined) return false;
  if (!('maxPersonnel' in value) || value['maxPersonnel'] === undefined) return false;
  if (!('minPersonnel' in value) || value['minPersonnel'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('validFrom' in value) || value['validFrom'] === undefined) return false;
  return true;
}

export function FunctionOptaDtoFromJSON(json: any): FunctionOptaDto {
  return FunctionOptaDtoFromJSONTyped(json, false);
}

export function FunctionOptaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionOptaDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    code: json['code'],
    createdAt: json['createdAt'],
    description: json['description'],
    group: json['group'],
    isActive: json['isActive'],
    label: json['label'],
    maxPersonnel: json['maxPersonnel'],
    minPersonnel: json['minPersonnel'],
    type: json['type'],
    updatedAt: new Date(json['updatedAt']),
    validFrom: new Date(json['validFrom']),
  };
}

export function FunctionOptaDtoToJSON(json: any): FunctionOptaDto {
  return FunctionOptaDtoToJSONTyped(json, false);
}

export function FunctionOptaDtoToJSONTyped(value?: FunctionOptaDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    code: value['code'],
    createdAt: value['createdAt'],
    description: value['description'],
    group: value['group'],
    isActive: value['isActive'],
    label: value['label'],
    maxPersonnel: value['maxPersonnel'],
    minPersonnel: value['minPersonnel'],
    type: value['type'],
    updatedAt: value['updatedAt'].toISOString(),
    validFrom: value['validFrom'].toISOString(),
  };
}
