/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IconDefinitionDto
 */
export interface IconDefinitionDto {
  /**
   *
   * @type {string}
   * @memberof IconDefinitionDto
   */
  organisation?: string;
  /**
   *
   * @type {string}
   * @memberof IconDefinitionDto
   */
  fachaufgabe?: string;
  /**
   *
   * @type {string}
   * @memberof IconDefinitionDto
   */
  verwaltungsstufe?: string;
}

/**
 * Check if a given object implements the IconDefinitionDto interface.
 */
export function instanceOfIconDefinitionDto(value: object): value is IconDefinitionDto {
  return true;
}

export function IconDefinitionDtoFromJSON(json: any): IconDefinitionDto {
  return IconDefinitionDtoFromJSONTyped(json, false);
}

export function IconDefinitionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IconDefinitionDto {
  if (json == null) {
    return json;
  }
  return {
    organisation: json['organisation'] == null ? undefined : json['organisation'],
    fachaufgabe: json['fachaufgabe'] == null ? undefined : json['fachaufgabe'],
    verwaltungsstufe: json['verwaltungsstufe'] == null ? undefined : json['verwaltungsstufe'],
  };
}

export function IconDefinitionDtoToJSON(json: any): IconDefinitionDto {
  return IconDefinitionDtoToJSONTyped(json, false);
}

export function IconDefinitionDtoToJSONTyped(
  value?: IconDefinitionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    organisation: value['organisation'],
    fachaufgabe: value['fachaufgabe'],
    verwaltungsstufe: value['verwaltungsstufe'],
  };
}
