/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateUpdateUAVDto } from './CreateUpdateUAVDto';
import {
  CreateUpdateUAVDtoFromJSON,
  CreateUpdateUAVDtoFromJSONTyped,
  CreateUpdateUAVDtoToJSON,
  CreateUpdateUAVDtoToJSONTyped,
} from './CreateUpdateUAVDto';

/**
 *
 * @export
 * @interface ImportManyUAVsDto
 */
export interface ImportManyUAVsDto {
  /**
   *
   * @type {Array<CreateUpdateUAVDto>}
   * @memberof ImportManyUAVsDto
   */
  items: Array<CreateUpdateUAVDto>;
}

/**
 * Check if a given object implements the ImportManyUAVsDto interface.
 */
export function instanceOfImportManyUAVsDto(value: object): value is ImportManyUAVsDto {
  if (!('items' in value) || value['items'] === undefined) return false;
  return true;
}

export function ImportManyUAVsDtoFromJSON(json: any): ImportManyUAVsDto {
  return ImportManyUAVsDtoFromJSONTyped(json, false);
}

export function ImportManyUAVsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportManyUAVsDto {
  if (json == null) {
    return json;
  }
  return {
    items: (json['items'] as Array<any>).map(CreateUpdateUAVDtoFromJSON),
  };
}

export function ImportManyUAVsDtoToJSON(json: any): ImportManyUAVsDto {
  return ImportManyUAVsDtoToJSONTyped(json, false);
}

export function ImportManyUAVsDtoToJSONTyped(
  value?: ImportManyUAVsDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    items: (value['items'] as Array<any>).map(CreateUpdateUAVDtoToJSON),
  };
}
