/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IconDefinitionDto } from './IconDefinitionDto';
import {
  IconDefinitionDtoFromJSON,
  IconDefinitionDtoFromJSONTyped,
  IconDefinitionDtoToJSON,
  IconDefinitionDtoToJSONTyped,
} from './IconDefinitionDto';

/**
 *
 * @export
 * @interface ImportFahrzeugDto
 */
export interface ImportFahrzeugDto {
  /**
   *
   * @type {string}
   * @memberof ImportFahrzeugDto
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ImportFahrzeugDto
   */
  fullOpta: string;
  /**
   *
   * @type {IconDefinitionDto}
   * @memberof ImportFahrzeugDto
   */
  iconDefinition?: IconDefinitionDto;
}

/**
 * Check if a given object implements the ImportFahrzeugDto interface.
 */
export function instanceOfImportFahrzeugDto(value: object): value is ImportFahrzeugDto {
  if (!('fullOpta' in value) || value['fullOpta'] === undefined) return false;
  return true;
}

export function ImportFahrzeugDtoFromJSON(json: any): ImportFahrzeugDto {
  return ImportFahrzeugDtoFromJSONTyped(json, false);
}

export function ImportFahrzeugDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportFahrzeugDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'] == null ? undefined : json['_id'],
    fullOpta: json['fullOpta'],
    iconDefinition: json['iconDefinition'] == null ? undefined : IconDefinitionDtoFromJSON(json['iconDefinition']),
  };
}

export function ImportFahrzeugDtoToJSON(json: any): ImportFahrzeugDto {
  return ImportFahrzeugDtoToJSONTyped(json, false);
}

export function ImportFahrzeugDtoToJSONTyped(
  value?: ImportFahrzeugDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    fullOpta: value['fullOpta'],
    iconDefinition: IconDefinitionDtoToJSON(value['iconDefinition']),
  };
}
