/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImportFahrzeugDto } from './ImportFahrzeugDto';
import {
  ImportFahrzeugDtoFromJSON,
  ImportFahrzeugDtoFromJSONTyped,
  ImportFahrzeugDtoToJSON,
  ImportFahrzeugDtoToJSONTyped,
} from './ImportFahrzeugDto';

/**
 *
 * @export
 * @interface ImportManyFahrzeugeDto
 */
export interface ImportManyFahrzeugeDto {
  /**
   *
   * @type {Array<ImportFahrzeugDto>}
   * @memberof ImportManyFahrzeugeDto
   */
  items: Array<ImportFahrzeugDto>;
}

/**
 * Check if a given object implements the ImportManyFahrzeugeDto interface.
 */
export function instanceOfImportManyFahrzeugeDto(value: object): value is ImportManyFahrzeugeDto {
  if (!('items' in value) || value['items'] === undefined) return false;
  return true;
}

export function ImportManyFahrzeugeDtoFromJSON(json: any): ImportManyFahrzeugeDto {
  return ImportManyFahrzeugeDtoFromJSONTyped(json, false);
}

export function ImportManyFahrzeugeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportManyFahrzeugeDto {
  if (json == null) {
    return json;
  }
  return {
    items: (json['items'] as Array<any>).map(ImportFahrzeugDtoFromJSON),
  };
}

export function ImportManyFahrzeugeDtoToJSON(json: any): ImportManyFahrzeugeDto {
  return ImportManyFahrzeugeDtoToJSONTyped(json, false);
}

export function ImportManyFahrzeugeDtoToJSONTyped(
  value?: ImportManyFahrzeugeDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    items: (value['items'] as Array<any>).map(ImportFahrzeugDtoToJSON),
  };
}
