/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { JournalEntryDto } from './JournalEntryDto';
import {
  JournalEntryDtoFromJSON,
  JournalEntryDtoFromJSONTyped,
  JournalEntryDtoToJSON,
  JournalEntryDtoToJSONTyped,
} from './JournalEntryDto';

/**
 *
 * @export
 * @interface JournalEntryResponse
 */
export interface JournalEntryResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof JournalEntryResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {JournalEntryDto}
   * @memberof JournalEntryResponse
   */
  data: JournalEntryDto;
}

/**
 * Check if a given object implements the JournalEntryResponse interface.
 */
export function instanceOfJournalEntryResponse(value: object): value is JournalEntryResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function JournalEntryResponseFromJSON(json: any): JournalEntryResponse {
  return JournalEntryResponseFromJSONTyped(json, false);
}

export function JournalEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalEntryResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: JournalEntryDtoFromJSON(json['data']),
  };
}

export function JournalEntryResponseToJSON(json: any): JournalEntryResponse {
  return JournalEntryResponseToJSONTyped(json, false);
}

export function JournalEntryResponseToJSONTyped(
  value?: JournalEntryResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: JournalEntryDtoToJSON(value['data']),
  };
}
