/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JournalEntryDto } from './JournalEntryDto';
import {
  JournalEntryDtoFromJSON,
  JournalEntryDtoFromJSONTyped,
  JournalEntryDtoToJSON,
  JournalEntryDtoToJSONTyped,
} from './JournalEntryDto';

/**
 *
 * @export
 * @interface JournalDto
 */
export interface JournalDto {
  /**
   *
   * @type {Array<JournalEntryDto>}
   * @memberof JournalDto
   */
  items: Array<JournalEntryDto>;
}

/**
 * Check if a given object implements the JournalDto interface.
 */
export function instanceOfJournalDto(value: object): value is JournalDto {
  if (!('items' in value) || value['items'] === undefined) return false;
  return true;
}

export function JournalDtoFromJSON(json: any): JournalDto {
  return JournalDtoFromJSONTyped(json, false);
}

export function JournalDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalDto {
  if (json == null) {
    return json;
  }
  return {
    items: (json['items'] as Array<any>).map(JournalEntryDtoFromJSON),
  };
}

export function JournalDtoToJSON(json: any): JournalDto {
  return JournalDtoToJSONTyped(json, false);
}

export function JournalDtoToJSONTyped(value?: JournalDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    items: (value['items'] as Array<any>).map(JournalEntryDtoToJSON),
  };
}
