/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface JournalEntryDto
 */
export interface JournalEntryDto {
  /**
   *
   * @type {string}
   * @memberof JournalEntryDto
   */
  timestamp: string;
  /**
   *
   * @type {string}
   * @memberof JournalEntryDto
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof JournalEntryDto
   */
  sender: string;
  /**
   *
   * @type {string}
   * @memberof JournalEntryDto
   */
  receiver: string;
  /**
   *
   * @type {boolean}
   * @memberof JournalEntryDto
   */
  archived: boolean;
  /**
   *
   * @type {number}
   * @memberof JournalEntryDto
   */
  nummer: number;
  /**
   *
   * @type {string}
   * @memberof JournalEntryDto
   */
  type: JournalEntryDtoTypeEnum;
  /**
   *
   * @type {string}
   * @memberof JournalEntryDto
   */
  bearbeiter: string;
}

/**
 * @export
 */
export const JournalEntryDtoTypeEnum = {
  User: 'USER',
  Generisch: 'GENERISCH',
  Ressourcen: 'RESSOURCEN',
  Kommunikation: 'KOMMUNIKATION',
  Lage: 'LAGE',
  Betroffene: 'BETROFFENE',
} as const;
export type JournalEntryDtoTypeEnum = (typeof JournalEntryDtoTypeEnum)[keyof typeof JournalEntryDtoTypeEnum];

/**
 * Check if a given object implements the JournalEntryDto interface.
 */
export function instanceOfJournalEntryDto(value: object): value is JournalEntryDto {
  if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('sender' in value) || value['sender'] === undefined) return false;
  if (!('receiver' in value) || value['receiver'] === undefined) return false;
  if (!('archived' in value) || value['archived'] === undefined) return false;
  if (!('nummer' in value) || value['nummer'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('bearbeiter' in value) || value['bearbeiter'] === undefined) return false;
  return true;
}

export function JournalEntryDtoFromJSON(json: any): JournalEntryDto {
  return JournalEntryDtoFromJSONTyped(json, false);
}

export function JournalEntryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalEntryDto {
  if (json == null) {
    return json;
  }
  return {
    timestamp: json['timestamp'],
    content: json['content'],
    sender: json['sender'],
    receiver: json['receiver'],
    archived: json['archived'],
    nummer: json['nummer'],
    type: json['type'],
    bearbeiter: json['bearbeiter'],
  };
}

export function JournalEntryDtoToJSON(json: any): JournalEntryDto {
  return JournalEntryDtoToJSONTyped(json, false);
}

export function JournalEntryDtoToJSONTyped(value?: JournalEntryDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    timestamp: value['timestamp'],
    content: value['content'],
    sender: value['sender'],
    receiver: value['receiver'],
    archived: value['archived'],
    nummer: value['nummer'],
    type: value['type'],
    bearbeiter: value['bearbeiter'],
  };
}
