/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { JournalDto } from './JournalDto';
import { JournalDtoFromJSON, JournalDtoFromJSONTyped, JournalDtoToJSON, JournalDtoToJSONTyped } from './JournalDto';

/**
 *
 * @export
 * @interface JournalResponse
 */
export interface JournalResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof JournalResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {JournalDto}
   * @memberof JournalResponse
   */
  data: JournalDto;
}

/**
 * Check if a given object implements the JournalResponse interface.
 */
export function instanceOfJournalResponse(value: object): value is JournalResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function JournalResponseFromJSON(json: any): JournalResponse {
  return JournalResponseFromJSONTyped(json, false);
}

export function JournalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: JournalDtoFromJSON(json['data']),
  };
}

export function JournalResponseToJSON(json: any): JournalResponse {
  return JournalResponseToJSONTyped(json, false);
}

export function JournalResponseToJSONTyped(value?: JournalResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: JournalDtoToJSON(value['data']),
  };
}
