/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LocalCodeOpta
 */
export interface LocalCodeOpta {
  /**
   *
   * @type {string}
   * @memberof LocalCodeOpta
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof LocalCodeOpta
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof LocalCodeOpta
   */
  label: string;
  /**
   *
   * @type {string}
   * @memberof LocalCodeOpta
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof LocalCodeOpta
   */
  description: string;
  /**
   *
   * @type {boolean}
   * @memberof LocalCodeOpta
   */
  isActive: boolean;
  /**
   *
   * @type {string}
   * @memberof LocalCodeOpta
   */
  createdAt: string;
  /**
   *
   * @type {Date}
   * @memberof LocalCodeOpta
   */
  updatedAt: Date;
  /**
   *
   * @type {Date}
   * @memberof LocalCodeOpta
   */
  validFrom: Date;
  /**
   *
   * @type {string}
   * @memberof LocalCodeOpta
   */
  group: LocalCodeOptaGroupEnum;
}

/**
 * @export
 */
export const LocalCodeOptaGroupEnum = {
  MinisteriumFrInneresUndSport: 'Ministerium für Inneres und Sport',
  NiederschsischesLandesamtFrBrandUndKatastrophenschutz:
    'Niedersächsisches Landesamt für Brand- und Katastrophenschutz',
  Sonstige: 'Sonstige',
  GemeindeFf: 'Gemeinde / FF',
  HilfsorganisationenAufLandesebene: 'Hilfsorganisationen auf Landesebene',
  BeauftragteFrRdOhneHilfsorganisation: 'Beauftragte für RD ohne Hilfsorganisation',
  LandeseinheitenImKatastrophenschutz: 'Landeseinheiten im Katastrophenschutz',
  Intensivtransport: 'Intensivtransport',
  Waldbrandbeauftragte: 'Waldbrandbeauftragte',
  Werkfeuerwehr: 'Werkfeuerwehr',
  FhrungskrfteRettungsdienst: 'Führungskräfte Rettungsdienst',
  FhrungskrfteFeuerwehr: 'Führungskräfte Feuerwehr',
} as const;
export type LocalCodeOptaGroupEnum = (typeof LocalCodeOptaGroupEnum)[keyof typeof LocalCodeOptaGroupEnum];

/**
 * Check if a given object implements the LocalCodeOpta interface.
 */
export function instanceOfLocalCodeOpta(value: object): value is LocalCodeOpta {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('label' in value) || value['label'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('validFrom' in value) || value['validFrom'] === undefined) return false;
  if (!('group' in value) || value['group'] === undefined) return false;
  return true;
}

export function LocalCodeOptaFromJSON(json: any): LocalCodeOpta {
  return LocalCodeOptaFromJSONTyped(json, false);
}

export function LocalCodeOptaFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalCodeOpta {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    code: json['code'],
    label: json['label'],
    type: json['type'],
    description: json['description'],
    isActive: json['isActive'],
    createdAt: json['createdAt'],
    updatedAt: new Date(json['updatedAt']),
    validFrom: new Date(json['validFrom']),
    group: json['group'],
  };
}

export function LocalCodeOptaToJSON(json: any): LocalCodeOpta {
  return LocalCodeOptaToJSONTyped(json, false);
}

export function LocalCodeOptaToJSONTyped(value?: LocalCodeOpta | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    code: value['code'],
    label: value['label'],
    type: value['type'],
    description: value['description'],
    isActive: value['isActive'],
    createdAt: value['createdAt'],
    updatedAt: value['updatedAt'].toISOString(),
    validFrom: value['validFrom'].toISOString(),
    group: value['group'],
  };
}
