/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { UAVTemplateDto } from './UAVTemplateDto';
import {
  UAVTemplateDtoFromJSON,
  UAVTemplateDtoFromJSONTyped,
  UAVTemplateDtoToJSON,
  UAVTemplateDtoToJSONTyped,
} from './UAVTemplateDto';

/**
 *
 * @export
 * @interface ManyUAVTemplateResponse
 */
export interface ManyUAVTemplateResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyUAVTemplateResponse
   */
  meta: ApiMeta;
  /**
   * List of UAVs
   * @type {Array<UAVTemplateDto>}
   * @memberof ManyUAVTemplateResponse
   */
  data: Array<UAVTemplateDto>;
}

/**
 * Check if a given object implements the ManyUAVTemplateResponse interface.
 */
export function instanceOfManyUAVTemplateResponse(value: object): value is ManyUAVTemplateResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyUAVTemplateResponseFromJSON(json: any): ManyUAVTemplateResponse {
  return ManyUAVTemplateResponseFromJSONTyped(json, false);
}

export function ManyUAVTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManyUAVTemplateResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(UAVTemplateDtoFromJSON),
  };
}

export function ManyUAVTemplateResponseToJSON(json: any): ManyUAVTemplateResponse {
  return ManyUAVTemplateResponseToJSONTyped(json, false);
}

export function ManyUAVTemplateResponseToJSONTyped(
  value?: ManyUAVTemplateResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(UAVTemplateDtoToJSON),
  };
}
