/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { FahrzeugTypDto } from './FahrzeugTypDto';
import {
  FahrzeugTypDtoFromJSON,
  FahrzeugTypDtoFromJSONTyped,
  FahrzeugTypDtoToJSON,
  FahrzeugTypDtoToJSONTyped,
} from './FahrzeugTypDto';

/**
 *
 * @export
 * @interface ManyFahrzeugTypResponse
 */
export interface ManyFahrzeugTypResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyFahrzeugTypResponse
   */
  meta: ApiMeta;
  /**
   * List of vehicle types
   * @type {Array<FahrzeugTypDto>}
   * @memberof ManyFahrzeugTypResponse
   */
  data: Array<FahrzeugTypDto>;
}

/**
 * Check if a given object implements the ManyFahrzeugTypResponse interface.
 */
export function instanceOfManyFahrzeugTypResponse(value: object): value is ManyFahrzeugTypResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyFahrzeugTypResponseFromJSON(json: any): ManyFahrzeugTypResponse {
  return ManyFahrzeugTypResponseFromJSONTyped(json, false);
}

export function ManyFahrzeugTypResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManyFahrzeugTypResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(FahrzeugTypDtoFromJSON),
  };
}

export function ManyFahrzeugTypResponseToJSON(json: any): ManyFahrzeugTypResponse {
  return ManyFahrzeugTypResponseToJSONTyped(json, false);
}

export function ManyFahrzeugTypResponseToJSONTyped(
  value?: ManyFahrzeugTypResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(FahrzeugTypDtoToJSON),
  };
}
