/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { FahrzeugeDto } from './FahrzeugeDto';
import {
  FahrzeugeDtoFromJSON,
  FahrzeugeDtoFromJSONTyped,
  FahrzeugeDtoToJSON,
  FahrzeugeDtoToJSONTyped,
} from './FahrzeugeDto';

/**
 *
 * @export
 * @interface ManyFahrzeugeResponse
 */
export interface ManyFahrzeugeResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyFahrzeugeResponse
   */
  meta: ApiMeta;
  /**
   * List of vehicles
   * @type {FahrzeugeDto}
   * @memberof ManyFahrzeugeResponse
   */
  data: FahrzeugeDto;
}

/**
 * Check if a given object implements the ManyFahrzeugeResponse interface.
 */
export function instanceOfManyFahrzeugeResponse(value: object): value is ManyFahrzeugeResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyFahrzeugeResponseFromJSON(json: any): ManyFahrzeugeResponse {
  return ManyFahrzeugeResponseFromJSONTyped(json, false);
}

export function ManyFahrzeugeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManyFahrzeugeResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: FahrzeugeDtoFromJSON(json['data']),
  };
}

export function ManyFahrzeugeResponseToJSON(json: any): ManyFahrzeugeResponse {
  return ManyFahrzeugeResponseToJSONTyped(json, false);
}

export function ManyFahrzeugeResponseToJSONTyped(
  value?: ManyFahrzeugeResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: FahrzeugeDtoToJSON(value['data']),
  };
}
