/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { LocalCodeOpta } from './LocalCodeOpta';
import {
  LocalCodeOptaFromJSON,
  LocalCodeOptaFromJSONTyped,
  LocalCodeOptaToJSON,
  LocalCodeOptaToJSONTyped,
} from './LocalCodeOpta';

/**
 *
 * @export
 * @interface ManyLocalCodeOptaTemplatesResponse
 */
export interface ManyLocalCodeOptaTemplatesResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyLocalCodeOptaTemplatesResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<LocalCodeOpta>}
   * @memberof ManyLocalCodeOptaTemplatesResponse
   */
  data: Array<LocalCodeOpta>;
}

/**
 * Check if a given object implements the ManyLocalCodeOptaTemplatesResponse interface.
 */
export function instanceOfManyLocalCodeOptaTemplatesResponse(
  value: object,
): value is ManyLocalCodeOptaTemplatesResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyLocalCodeOptaTemplatesResponseFromJSON(json: any): ManyLocalCodeOptaTemplatesResponse {
  return ManyLocalCodeOptaTemplatesResponseFromJSONTyped(json, false);
}

export function ManyLocalCodeOptaTemplatesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ManyLocalCodeOptaTemplatesResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(LocalCodeOptaFromJSON),
  };
}

export function ManyLocalCodeOptaTemplatesResponseToJSON(json: any): ManyLocalCodeOptaTemplatesResponse {
  return ManyLocalCodeOptaTemplatesResponseToJSONTyped(json, false);
}

export function ManyLocalCodeOptaTemplatesResponseToJSONTyped(
  value?: ManyLocalCodeOptaTemplatesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(LocalCodeOptaToJSON),
  };
}
