/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { FunctionOptaDto } from './FunctionOptaDto';
import {
  FunctionOptaDtoFromJSON,
  FunctionOptaDtoFromJSONTyped,
  FunctionOptaDtoToJSON,
  FunctionOptaDtoToJSONTyped,
} from './FunctionOptaDto';

/**
 *
 * @export
 * @interface ManyFunctionOptaTemplatesResponse
 */
export interface ManyFunctionOptaTemplatesResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyFunctionOptaTemplatesResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<FunctionOptaDto>}
   * @memberof ManyFunctionOptaTemplatesResponse
   */
  data: Array<FunctionOptaDto>;
}

/**
 * Check if a given object implements the ManyFunctionOptaTemplatesResponse interface.
 */
export function instanceOfManyFunctionOptaTemplatesResponse(value: object): value is ManyFunctionOptaTemplatesResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyFunctionOptaTemplatesResponseFromJSON(json: any): ManyFunctionOptaTemplatesResponse {
  return ManyFunctionOptaTemplatesResponseFromJSONTyped(json, false);
}

export function ManyFunctionOptaTemplatesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ManyFunctionOptaTemplatesResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(FunctionOptaDtoFromJSON),
  };
}

export function ManyFunctionOptaTemplatesResponseToJSON(json: any): ManyFunctionOptaTemplatesResponse {
  return ManyFunctionOptaTemplatesResponseToJSONTyped(json, false);
}

export function ManyFunctionOptaTemplatesResponseToJSONTyped(
  value?: ManyFunctionOptaTemplatesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(FunctionOptaDtoToJSON),
  };
}
