/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { SmallMissionDto } from './SmallMissionDto';
import {
  SmallMissionDtoFromJSON,
  SmallMissionDtoFromJSONTyped,
  SmallMissionDtoToJSON,
  SmallMissionDtoToJSONTyped,
} from './SmallMissionDto';

/**
 *
 * @export
 * @interface ManyMissionsResponse
 */
export interface ManyMissionsResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyMissionsResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<SmallMissionDto>}
   * @memberof ManyMissionsResponse
   */
  data: Array<SmallMissionDto>;
}

/**
 * Check if a given object implements the ManyMissionsResponse interface.
 */
export function instanceOfManyMissionsResponse(value: object): value is ManyMissionsResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyMissionsResponseFromJSON(json: any): ManyMissionsResponse {
  return ManyMissionsResponseFromJSONTyped(json, false);
}

export function ManyMissionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManyMissionsResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(SmallMissionDtoFromJSON),
  };
}

export function ManyMissionsResponseToJSON(json: any): ManyMissionsResponse {
  return ManyMissionsResponseToJSONTyped(json, false);
}

export function ManyMissionsResponseToJSONTyped(
  value?: ManyMissionsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(SmallMissionDtoToJSON),
  };
}
