/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { EinsatzReminderDto } from './EinsatzReminderDto';
import {
  EinsatzReminderDtoFromJSON,
  EinsatzReminderDtoFromJSONTyped,
  EinsatzReminderDtoToJSON,
  EinsatzReminderDtoToJSONTyped,
} from './EinsatzReminderDto';

/**
 *
 * @export
 * @interface ManyEinsatzReminderResponse
 */
export interface ManyEinsatzReminderResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyEinsatzReminderResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<EinsatzReminderDto>}
   * @memberof ManyEinsatzReminderResponse
   */
  data: Array<EinsatzReminderDto>;
}

/**
 * Check if a given object implements the ManyEinsatzReminderResponse interface.
 */
export function instanceOfManyEinsatzReminderResponse(value: object): value is ManyEinsatzReminderResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyEinsatzReminderResponseFromJSON(json: any): ManyEinsatzReminderResponse {
  return ManyEinsatzReminderResponseFromJSONTyped(json, false);
}

export function ManyEinsatzReminderResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ManyEinsatzReminderResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(EinsatzReminderDtoFromJSON),
  };
}

export function ManyEinsatzReminderResponseToJSON(json: any): ManyEinsatzReminderResponse {
  return ManyEinsatzReminderResponseToJSONTyped(json, false);
}

export function ManyEinsatzReminderResponseToJSONTyped(
  value?: ManyEinsatzReminderResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(EinsatzReminderDtoToJSON),
  };
}
