/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { StatusDto } from './StatusDto';
import { StatusDtoFromJSON, StatusDtoFromJSONTyped, StatusDtoToJSON, StatusDtoToJSONTyped } from './StatusDto';

/**
 *
 * @export
 * @interface ManyStatusDtoReponse
 */
export interface ManyStatusDtoReponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyStatusDtoReponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<StatusDto>}
   * @memberof ManyStatusDtoReponse
   */
  data: Array<StatusDto>;
}

/**
 * Check if a given object implements the ManyStatusDtoReponse interface.
 */
export function instanceOfManyStatusDtoReponse(value: object): value is ManyStatusDtoReponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyStatusDtoReponseFromJSON(json: any): ManyStatusDtoReponse {
  return ManyStatusDtoReponseFromJSONTyped(json, false);
}

export function ManyStatusDtoReponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManyStatusDtoReponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(StatusDtoFromJSON),
  };
}

export function ManyStatusDtoReponseToJSON(json: any): ManyStatusDtoReponse {
  return ManyStatusDtoReponseToJSONTyped(json, false);
}

export function ManyStatusDtoReponseToJSONTyped(
  value?: ManyStatusDtoReponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(StatusDtoToJSON),
  };
}
