/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { BosOpta } from './BosOpta';
import { BosOptaFromJSON, BosOptaFromJSONTyped, BosOptaToJSON, BosOptaToJSONTyped } from './BosOpta';

/**
 *
 * @export
 * @interface ManyBosOptaTemplatesResponse
 */
export interface ManyBosOptaTemplatesResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyBosOptaTemplatesResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<BosOpta>}
   * @memberof ManyBosOptaTemplatesResponse
   */
  data: Array<BosOpta>;
}

/**
 * Check if a given object implements the ManyBosOptaTemplatesResponse interface.
 */
export function instanceOfManyBosOptaTemplatesResponse(value: object): value is ManyBosOptaTemplatesResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyBosOptaTemplatesResponseFromJSON(json: any): ManyBosOptaTemplatesResponse {
  return ManyBosOptaTemplatesResponseFromJSONTyped(json, false);
}

export function ManyBosOptaTemplatesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ManyBosOptaTemplatesResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(BosOptaFromJSON),
  };
}

export function ManyBosOptaTemplatesResponseToJSON(json: any): ManyBosOptaTemplatesResponse {
  return ManyBosOptaTemplatesResponseToJSONTyped(json, false);
}

export function ManyBosOptaTemplatesResponseToJSONTyped(
  value?: ManyBosOptaTemplatesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(BosOptaToJSON),
  };
}
