/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { QualificationDto } from './QualificationDto';
import {
  QualificationDtoFromJSON,
  QualificationDtoFromJSONTyped,
  QualificationDtoToJSON,
  QualificationDtoToJSONTyped,
} from './QualificationDto';

/**
 *
 * @export
 * @interface ManyQualificationsResponse
 */
export interface ManyQualificationsResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyQualificationsResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<QualificationDto>}
   * @memberof ManyQualificationsResponse
   */
  data: Array<QualificationDto>;
}

/**
 * Check if a given object implements the ManyQualificationsResponse interface.
 */
export function instanceOfManyQualificationsResponse(value: object): value is ManyQualificationsResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyQualificationsResponseFromJSON(json: any): ManyQualificationsResponse {
  return ManyQualificationsResponseFromJSONTyped(json, false);
}

export function ManyQualificationsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ManyQualificationsResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(QualificationDtoFromJSON),
  };
}

export function ManyQualificationsResponseToJSON(json: any): ManyQualificationsResponse {
  return ManyQualificationsResponseToJSONTyped(json, false);
}

export function ManyQualificationsResponseToJSONTyped(
  value?: ManyQualificationsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(QualificationDtoToJSON),
  };
}
