/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { EinsatzAlarmstichwortDto } from './EinsatzAlarmstichwortDto';
import {
  EinsatzAlarmstichwortDtoFromJSON,
  EinsatzAlarmstichwortDtoFromJSONTyped,
  EinsatzAlarmstichwortDtoToJSON,
  EinsatzAlarmstichwortDtoToJSONTyped,
} from './EinsatzAlarmstichwortDto';

/**
 *
 * @export
 * @interface ManyEinsatzAlarmstichwortDto
 */
export interface ManyEinsatzAlarmstichwortDto {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyEinsatzAlarmstichwortDto
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<EinsatzAlarmstichwortDto>}
   * @memberof ManyEinsatzAlarmstichwortDto
   */
  data: Array<EinsatzAlarmstichwortDto>;
}

/**
 * Check if a given object implements the ManyEinsatzAlarmstichwortDto interface.
 */
export function instanceOfManyEinsatzAlarmstichwortDto(value: object): value is ManyEinsatzAlarmstichwortDto {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyEinsatzAlarmstichwortDtoFromJSON(json: any): ManyEinsatzAlarmstichwortDto {
  return ManyEinsatzAlarmstichwortDtoFromJSONTyped(json, false);
}

export function ManyEinsatzAlarmstichwortDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ManyEinsatzAlarmstichwortDto {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(EinsatzAlarmstichwortDtoFromJSON),
  };
}

export function ManyEinsatzAlarmstichwortDtoToJSON(json: any): ManyEinsatzAlarmstichwortDto {
  return ManyEinsatzAlarmstichwortDtoToJSONTyped(json, false);
}

export function ManyEinsatzAlarmstichwortDtoToJSONTyped(
  value?: ManyEinsatzAlarmstichwortDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(EinsatzAlarmstichwortDtoToJSON),
  };
}
