/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { EinsatzNoteDto } from './EinsatzNoteDto';
import {
  EinsatzNoteDtoFromJSON,
  EinsatzNoteDtoFromJSONTyped,
  EinsatzNoteDtoToJSON,
  EinsatzNoteDtoToJSONTyped,
} from './EinsatzNoteDto';

/**
 *
 * @export
 * @interface ManyNoteResponse
 */
export interface ManyNoteResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyNoteResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<EinsatzNoteDto>}
   * @memberof ManyNoteResponse
   */
  data: Array<EinsatzNoteDto>;
}

/**
 * Check if a given object implements the ManyNoteResponse interface.
 */
export function instanceOfManyNoteResponse(value: object): value is ManyNoteResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyNoteResponseFromJSON(json: any): ManyNoteResponse {
  return ManyNoteResponseFromJSONTyped(json, false);
}

export function ManyNoteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManyNoteResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(EinsatzNoteDtoFromJSON),
  };
}

export function ManyNoteResponseToJSON(json: any): ManyNoteResponse {
  return ManyNoteResponseToJSONTyped(json, false);
}

export function ManyNoteResponseToJSONTyped(
  value?: ManyNoteResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(EinsatzNoteDtoToJSON),
  };
}
