/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { BearbeiterDto } from './BearbeiterDto';
import {
  BearbeiterDtoFromJSON,
  BearbeiterDtoFromJSONTyped,
  BearbeiterDtoToJSON,
  BearbeiterDtoToJSONTyped,
} from './BearbeiterDto';

/**
 *
 * @export
 * @interface ManyBearbeiterResponse
 */
export interface ManyBearbeiterResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyBearbeiterResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<BearbeiterDto>}
   * @memberof ManyBearbeiterResponse
   */
  data: Array<BearbeiterDto>;
}

/**
 * Check if a given object implements the ManyBearbeiterResponse interface.
 */
export function instanceOfManyBearbeiterResponse(value: object): value is ManyBearbeiterResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyBearbeiterResponseFromJSON(json: any): ManyBearbeiterResponse {
  return ManyBearbeiterResponseFromJSONTyped(json, false);
}

export function ManyBearbeiterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManyBearbeiterResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(BearbeiterDtoFromJSON),
  };
}

export function ManyBearbeiterResponseToJSON(json: any): ManyBearbeiterResponse {
  return ManyBearbeiterResponseToJSONTyped(json, false);
}

export function ManyBearbeiterResponseToJSONTyped(
  value?: ManyBearbeiterResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(BearbeiterDtoToJSON),
  };
}
