/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { ReminderDto } from './ReminderDto';
import {
  ReminderDtoFromJSON,
  ReminderDtoFromJSONTyped,
  ReminderDtoToJSON,
  ReminderDtoToJSONTyped,
} from './ReminderDto';

/**
 *
 * @export
 * @interface ManyReminderResponse
 */
export interface ManyReminderResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyReminderResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<ReminderDto>}
   * @memberof ManyReminderResponse
   */
  data: Array<ReminderDto>;
}

/**
 * Check if a given object implements the ManyReminderResponse interface.
 */
export function instanceOfManyReminderResponse(value: object): value is ManyReminderResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyReminderResponseFromJSON(json: any): ManyReminderResponse {
  return ManyReminderResponseFromJSONTyped(json, false);
}

export function ManyReminderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManyReminderResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(ReminderDtoFromJSON),
  };
}

export function ManyReminderResponseToJSON(json: any): ManyReminderResponse {
  return ManyReminderResponseToJSONTyped(json, false);
}

export function ManyReminderResponseToJSONTyped(
  value?: ManyReminderResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(ReminderDtoToJSON),
  };
}
