/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { FahrzeugTemplateDto } from './FahrzeugTemplateDto';
import {
  FahrzeugTemplateDtoFromJSON,
  FahrzeugTemplateDtoFromJSONTyped,
  FahrzeugTemplateDtoToJSON,
  FahrzeugTemplateDtoToJSONTyped,
} from './FahrzeugTemplateDto';

/**
 *
 * @export
 * @interface ManyFahrzeugeTemplateResponse
 */
export interface ManyFahrzeugeTemplateResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyFahrzeugeTemplateResponse
   */
  meta: ApiMeta;
  /**
   * List of vehicles
   * @type {Array<FahrzeugTemplateDto>}
   * @memberof ManyFahrzeugeTemplateResponse
   */
  data: Array<FahrzeugTemplateDto>;
}

/**
 * Check if a given object implements the ManyFahrzeugeTemplateResponse interface.
 */
export function instanceOfManyFahrzeugeTemplateResponse(value: object): value is ManyFahrzeugeTemplateResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyFahrzeugeTemplateResponseFromJSON(json: any): ManyFahrzeugeTemplateResponse {
  return ManyFahrzeugeTemplateResponseFromJSONTyped(json, false);
}

export function ManyFahrzeugeTemplateResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ManyFahrzeugeTemplateResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(FahrzeugTemplateDtoFromJSON),
  };
}

export function ManyFahrzeugeTemplateResponseToJSON(json: any): ManyFahrzeugeTemplateResponse {
  return ManyFahrzeugeTemplateResponseToJSONTyped(json, false);
}

export function ManyFahrzeugeTemplateResponseToJSONTyped(
  value?: ManyFahrzeugeTemplateResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(FahrzeugTemplateDtoToJSON),
  };
}
