/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { DistrictOpta } from './DistrictOpta';
import {
  DistrictOptaFromJSON,
  DistrictOptaFromJSONTyped,
  DistrictOptaToJSON,
  DistrictOptaToJSONTyped,
} from './DistrictOpta';

/**
 *
 * @export
 * @interface ManyDistrictOptaTemplatesResponse
 */
export interface ManyDistrictOptaTemplatesResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof ManyDistrictOptaTemplatesResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<DistrictOpta>}
   * @memberof ManyDistrictOptaTemplatesResponse
   */
  data: Array<DistrictOpta>;
}

/**
 * Check if a given object implements the ManyDistrictOptaTemplatesResponse interface.
 */
export function instanceOfManyDistrictOptaTemplatesResponse(value: object): value is ManyDistrictOptaTemplatesResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ManyDistrictOptaTemplatesResponseFromJSON(json: any): ManyDistrictOptaTemplatesResponse {
  return ManyDistrictOptaTemplatesResponseFromJSONTyped(json, false);
}

export function ManyDistrictOptaTemplatesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ManyDistrictOptaTemplatesResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(DistrictOptaFromJSON),
  };
}

export function ManyDistrictOptaTemplatesResponseToJSON(json: any): ManyDistrictOptaTemplatesResponse {
  return ManyDistrictOptaTemplatesResponseToJSONTyped(json, false);
}

export function ManyDistrictOptaTemplatesResponseToJSONTyped(
  value?: ManyDistrictOptaTemplatesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(DistrictOptaToJSON),
  };
}
