/* tslint:disable */
/* eslint-disable */

/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MetaDto
 */
export interface MetaDto {
  /**
   *
   * @type {string}
   * @memberof MetaDto
   */
  version: string;
  /**
   *
   * @type {string}
   * @memberof MetaDto
   */
  serverName: string;
  /**
   *
   * @type {string}
   * @memberof MetaDto
   */
  serverId: string;
}

/**
 * Check if a given object implements the MetaDto interface.
 */
export function instanceOfMetaDto(value: object): value is MetaDto {
  if (!('version' in value) || value['version'] === undefined) return false;
  if (!('serverName' in value) || value['serverName'] === undefined) return false;
  if (!('serverId' in value) || value['serverId'] === undefined) return false;
  return true;
}

export function MetaDtoFromJSON(json: any): MetaDto {
  return MetaDtoFromJSONTyped(json, false);
}

export function MetaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaDto {
  if (json == null) {
    return json;
  }
  return {
    version: json['version'],
    serverName: json['serverName'],
    serverId: json['serverId'],
  };
}

export function MetaDtoToJSON(json: any): MetaDto {
  return MetaDtoToJSONTyped(json, false);
}

export function MetaDtoToJSONTyped(value?: MetaDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    version: value['version'],
    serverName: value['serverName'],
    serverId: value['serverId'],
  };
}
