/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BearbeiterWithStatusDto } from './BearbeiterWithStatusDto';
import {
  BearbeiterWithStatusDtoFromJSON,
  BearbeiterWithStatusDtoFromJSONTyped,
  BearbeiterWithStatusDtoToJSON,
  BearbeiterWithStatusDtoToJSONTyped,
} from './BearbeiterWithStatusDto';
import type { EinsatzAlarmstichwortDto } from './EinsatzAlarmstichwortDto';
import {
  EinsatzAlarmstichwortDtoFromJSON,
  EinsatzAlarmstichwortDtoFromJSONTyped,
  EinsatzAlarmstichwortDtoToJSON,
  EinsatzAlarmstichwortDtoToJSONTyped,
} from './EinsatzAlarmstichwortDto';
import type { JournalDto } from './JournalDto';
import { JournalDtoFromJSON, JournalDtoFromJSONTyped, JournalDtoToJSON, JournalDtoToJSONTyped } from './JournalDto';
import type { MissionMetaDto } from './MissionMetaDto';
import {
  MissionMetaDtoFromJSON,
  MissionMetaDtoFromJSONTyped,
  MissionMetaDtoToJSON,
  MissionMetaDtoToJSONTyped,
} from './MissionMetaDto';

/**
 *
 * @export
 * @interface MissionDto
 */
export interface MissionDto {
  /**
   *
   * @type {string}
   * @memberof MissionDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof MissionDto
   */
  aufnehmendesRettungsmittel: string;
  /**
   *
   * @type {BearbeiterWithStatusDto}
   * @memberof MissionDto
   */
  bearbeiter: BearbeiterWithStatusDto;
  /**
   *
   * @type {string}
   * @memberof MissionDto
   */
  beginn: string;
  /**
   *
   * @type {string}
   * @memberof MissionDto
   */
  ende: string;
  /**
   *
   * @type {EinsatzAlarmstichwortDto}
   * @memberof MissionDto
   */
  einsatzAlarmstichwort: EinsatzAlarmstichwortDto;
  /**
   *
   * @type {MissionMetaDto}
   * @memberof MissionDto
   */
  einsatzMeta: MissionMetaDto;
  /**
   *
   * @type {string}
   * @memberof MissionDto
   */
  abgeschlossen: string;
  /**
   *
   * @type {number}
   * @memberof MissionDto
   */
  einsatznummer: number;
  /**
   *
   * @type {JournalDto}
   * @memberof MissionDto
   */
  einsatzTagebuch: JournalDto;
  /**
   *
   * @type {Array<string>}
   * @memberof MissionDto
   */
  fahrzeuge: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof MissionDto
   */
  notizen: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof MissionDto
   */
  reminders: Array<string>;
}

/**
 * Check if a given object implements the MissionDto interface.
 */
export function instanceOfMissionDto(value: object): value is MissionDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('aufnehmendesRettungsmittel' in value) || value['aufnehmendesRettungsmittel'] === undefined) return false;
  if (!('bearbeiter' in value) || value['bearbeiter'] === undefined) return false;
  if (!('beginn' in value) || value['beginn'] === undefined) return false;
  if (!('ende' in value) || value['ende'] === undefined) return false;
  if (!('einsatzAlarmstichwort' in value) || value['einsatzAlarmstichwort'] === undefined) return false;
  if (!('einsatzMeta' in value) || value['einsatzMeta'] === undefined) return false;
  if (!('abgeschlossen' in value) || value['abgeschlossen'] === undefined) return false;
  if (!('einsatznummer' in value) || value['einsatznummer'] === undefined) return false;
  if (!('einsatzTagebuch' in value) || value['einsatzTagebuch'] === undefined) return false;
  if (!('fahrzeuge' in value) || value['fahrzeuge'] === undefined) return false;
  if (!('notizen' in value) || value['notizen'] === undefined) return false;
  if (!('reminders' in value) || value['reminders'] === undefined) return false;
  return true;
}

export function MissionDtoFromJSON(json: any): MissionDto {
  return MissionDtoFromJSONTyped(json, false);
}

export function MissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MissionDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    aufnehmendesRettungsmittel: json['aufnehmendesRettungsmittel'],
    bearbeiter: BearbeiterWithStatusDtoFromJSON(json['bearbeiter']),
    beginn: json['beginn'],
    ende: json['ende'],
    einsatzAlarmstichwort: EinsatzAlarmstichwortDtoFromJSON(json['einsatzAlarmstichwort']),
    einsatzMeta: MissionMetaDtoFromJSON(json['einsatzMeta']),
    abgeschlossen: json['abgeschlossen'],
    einsatznummer: json['einsatznummer'],
    einsatzTagebuch: JournalDtoFromJSON(json['einsatzTagebuch']),
    fahrzeuge: json['fahrzeuge'],
    notizen: json['notizen'],
    reminders: json['reminders'],
  };
}

export function MissionDtoToJSON(json: any): MissionDto {
  return MissionDtoToJSONTyped(json, false);
}

export function MissionDtoToJSONTyped(value?: MissionDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    aufnehmendesRettungsmittel: value['aufnehmendesRettungsmittel'],
    bearbeiter: BearbeiterWithStatusDtoToJSON(value['bearbeiter']),
    beginn: value['beginn'],
    ende: value['ende'],
    einsatzAlarmstichwort: EinsatzAlarmstichwortDtoToJSON(value['einsatzAlarmstichwort']),
    einsatzMeta: MissionMetaDtoToJSON(value['einsatzMeta']),
    abgeschlossen: value['abgeschlossen'],
    einsatznummer: value['einsatznummer'],
    einsatzTagebuch: JournalDtoToJSON(value['einsatzTagebuch']),
    fahrzeuge: value['fahrzeuge'],
    notizen: value['notizen'],
    reminders: value['reminders'],
  };
}
