/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MissionMetaDto
 */
export interface MissionMetaDto {
  /**
   *
   * @type {string}
   * @memberof MissionMetaDto
   */
  ort: string;
}

/**
 * Check if a given object implements the MissionMetaDto interface.
 */
export function instanceOfMissionMetaDto(value: object): value is MissionMetaDto {
  if (!('ort' in value) || value['ort'] === undefined) return false;
  return true;
}

export function MissionMetaDtoFromJSON(json: any): MissionMetaDto {
  return MissionMetaDtoFromJSONTyped(json, false);
}

export function MissionMetaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MissionMetaDto {
  if (json == null) {
    return json;
  }
  return {
    ort: json['ort'],
  };
}

export function MissionMetaDtoToJSON(json: any): MissionMetaDto {
  return MissionMetaDtoToJSONTyped(json, false);
}

export function MissionMetaDtoToJSONTyped(value?: MissionMetaDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    ort: value['ort'],
  };
}
