/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';

/**
 *
 * @export
 * @interface MyApiResponse
 */
export interface MyApiResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof MyApiResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {object}
   * @memberof MyApiResponse
   */
  data: object;
}

/**
 * Check if a given object implements the MyApiResponse interface.
 */
export function instanceOfMyApiResponse(value: object): value is MyApiResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function MyApiResponseFromJSON(json: any): MyApiResponse {
  return MyApiResponseFromJSONTyped(json, false);
}

export function MyApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyApiResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: json['data'],
  };
}

export function MyApiResponseToJSON(json: any): MyApiResponse {
  return MyApiResponseToJSONTyped(json, false);
}

export function MyApiResponseToJSONTyped(value?: MyApiResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: value['data'],
  };
}
