/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';

/**
 *
 * @export
 * @interface MyMultiApiResponse
 */
export interface MyMultiApiResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof MyMultiApiResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<object>}
   * @memberof MyMultiApiResponse
   */
  data: Array<object>;
}

/**
 * Check if a given object implements the MyMultiApiResponse interface.
 */
export function instanceOfMyMultiApiResponse(value: object): value is MyMultiApiResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function MyMultiApiResponseFromJSON(json: any): MyMultiApiResponse {
  return MyMultiApiResponseFromJSONTyped(json, false);
}

export function MyMultiApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyMultiApiResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: json['data'],
  };
}

export function MyMultiApiResponseToJSON(json: any): MyMultiApiResponse {
  return MyMultiApiResponseToJSONTyped(json, false);
}

export function MyMultiApiResponseToJSONTyped(
  value?: MyMultiApiResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: value['data'],
  };
}
