/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { BearbeiterDto } from './BearbeiterDto';
import {
  BearbeiterDtoFromJSON,
  BearbeiterDtoFromJSONTyped,
  BearbeiterDtoToJSON,
  BearbeiterDtoToJSONTyped,
} from './BearbeiterDto';

/**
 *
 * @export
 * @interface OneBearbeiterResponse
 */
export interface OneBearbeiterResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof OneBearbeiterResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {BearbeiterDto}
   * @memberof OneBearbeiterResponse
   */
  data?: BearbeiterDto;
}

/**
 * Check if a given object implements the OneBearbeiterResponse interface.
 */
export function instanceOfOneBearbeiterResponse(value: object): value is OneBearbeiterResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function OneBearbeiterResponseFromJSON(json: any): OneBearbeiterResponse {
  return OneBearbeiterResponseFromJSONTyped(json, false);
}

export function OneBearbeiterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneBearbeiterResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: json['data'] == null ? undefined : BearbeiterDtoFromJSON(json['data']),
  };
}

export function OneBearbeiterResponseToJSON(json: any): OneBearbeiterResponse {
  return OneBearbeiterResponseToJSONTyped(json, false);
}

export function OneBearbeiterResponseToJSONTyped(
  value?: OneBearbeiterResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: BearbeiterDtoToJSON(value['data']),
  };
}
