/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { EinsatzReminderDto } from './EinsatzReminderDto';
import {
  EinsatzReminderDtoFromJSON,
  EinsatzReminderDtoFromJSONTyped,
  EinsatzReminderDtoToJSON,
  EinsatzReminderDtoToJSONTyped,
} from './EinsatzReminderDto';

/**
 *
 * @export
 * @interface OneEinsatzReminderResponse
 */
export interface OneEinsatzReminderResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof OneEinsatzReminderResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {EinsatzReminderDto}
   * @memberof OneEinsatzReminderResponse
   */
  data: EinsatzReminderDto;
}

/**
 * Check if a given object implements the OneEinsatzReminderResponse interface.
 */
export function instanceOfOneEinsatzReminderResponse(value: object): value is OneEinsatzReminderResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function OneEinsatzReminderResponseFromJSON(json: any): OneEinsatzReminderResponse {
  return OneEinsatzReminderResponseFromJSONTyped(json, false);
}

export function OneEinsatzReminderResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OneEinsatzReminderResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: EinsatzReminderDtoFromJSON(json['data']),
  };
}

export function OneEinsatzReminderResponseToJSON(json: any): OneEinsatzReminderResponse {
  return OneEinsatzReminderResponseToJSONTyped(json, false);
}

export function OneEinsatzReminderResponseToJSONTyped(
  value?: OneEinsatzReminderResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: EinsatzReminderDtoToJSON(value['data']),
  };
}
