/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { MissionDto } from './MissionDto';
import { MissionDtoFromJSON, MissionDtoFromJSONTyped, MissionDtoToJSON, MissionDtoToJSONTyped } from './MissionDto';

/**
 *
 * @export
 * @interface OneMissionResponse
 */
export interface OneMissionResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof OneMissionResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {MissionDto}
   * @memberof OneMissionResponse
   */
  data?: MissionDto;
}

/**
 * Check if a given object implements the OneMissionResponse interface.
 */
export function instanceOfOneMissionResponse(value: object): value is OneMissionResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function OneMissionResponseFromJSON(json: any): OneMissionResponse {
  return OneMissionResponseFromJSONTyped(json, false);
}

export function OneMissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneMissionResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: json['data'] == null ? undefined : MissionDtoFromJSON(json['data']),
  };
}

export function OneMissionResponseToJSON(json: any): OneMissionResponse {
  return OneMissionResponseToJSONTyped(json, false);
}

export function OneMissionResponseToJSONTyped(
  value?: OneMissionResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: MissionDtoToJSON(value['data']),
  };
}
