/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { EinsatzNoteDto } from './EinsatzNoteDto';
import {
  EinsatzNoteDtoFromJSON,
  EinsatzNoteDtoFromJSONTyped,
  EinsatzNoteDtoToJSON,
  EinsatzNoteDtoToJSONTyped,
} from './EinsatzNoteDto';

/**
 *
 * @export
 * @interface OneNoteResponse
 */
export interface OneNoteResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof OneNoteResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {EinsatzNoteDto}
   * @memberof OneNoteResponse
   */
  data: EinsatzNoteDto;
}

/**
 * Check if a given object implements the OneNoteResponse interface.
 */
export function instanceOfOneNoteResponse(value: object): value is OneNoteResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function OneNoteResponseFromJSON(json: any): OneNoteResponse {
  return OneNoteResponseFromJSONTyped(json, false);
}

export function OneNoteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneNoteResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: EinsatzNoteDtoFromJSON(json['data']),
  };
}

export function OneNoteResponseToJSON(json: any): OneNoteResponse {
  return OneNoteResponseToJSONTyped(json, false);
}

export function OneNoteResponseToJSONTyped(value?: OneNoteResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: EinsatzNoteDtoToJSON(value['data']),
  };
}
