/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { ReminderDto } from './ReminderDto';
import {
  ReminderDtoFromJSON,
  ReminderDtoFromJSONTyped,
  ReminderDtoToJSON,
  ReminderDtoToJSONTyped,
} from './ReminderDto';

/**
 *
 * @export
 * @interface OneReminderResponse
 */
export interface OneReminderResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof OneReminderResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {ReminderDto}
   * @memberof OneReminderResponse
   */
  data: ReminderDto;
}

/**
 * Check if a given object implements the OneReminderResponse interface.
 */
export function instanceOfOneReminderResponse(value: object): value is OneReminderResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function OneReminderResponseFromJSON(json: any): OneReminderResponse {
  return OneReminderResponseFromJSONTyped(json, false);
}

export function OneReminderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneReminderResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: ReminderDtoFromJSON(json['data']),
  };
}

export function OneReminderResponseToJSON(json: any): OneReminderResponse {
  return OneReminderResponseToJSONTyped(json, false);
}

export function OneReminderResponseToJSONTyped(
  value?: OneReminderResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: ReminderDtoToJSON(value['data']),
  };
}
