/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OptaDto
 */
export interface OptaDto {
  /**
   *
   * @type {string}
   * @memberof OptaDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof OptaDto
   */
  district?: string;
  /**
   *
   * @type {string}
   * @memberof OptaDto
   */
  bosCode?: string;
  /**
   *
   * @type {string}
   * @memberof OptaDto
   */
  localCode?: string;
  /**
   *
   * @type {string}
   * @memberof OptaDto
   */
  functionCode?: string;
  /**
   *
   * @type {string}
   * @memberof OptaDto
   */
  orderNumber?: string;
  /**
   *
   * @type {string}
   * @memberof OptaDto
   */
  ort?: string;
  /**
   *
   * @type {string}
   * @memberof OptaDto
   */
  supplement?: string;
  /**
   *
   * @type {string}
   * @memberof OptaDto
   */
  fullOpta: string;
}

/**
 * Check if a given object implements the OptaDto interface.
 */
export function instanceOfOptaDto(value: object): value is OptaDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('fullOpta' in value) || value['fullOpta'] === undefined) return false;
  return true;
}

export function OptaDtoFromJSON(json: any): OptaDto {
  return OptaDtoFromJSONTyped(json, false);
}

export function OptaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptaDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    district: json['district'] == null ? undefined : json['district'],
    bosCode: json['bosCode'] == null ? undefined : json['bosCode'],
    localCode: json['localCode'] == null ? undefined : json['localCode'],
    functionCode: json['functionCode'] == null ? undefined : json['functionCode'],
    orderNumber: json['orderNumber'] == null ? undefined : json['orderNumber'],
    ort: json['ort'] == null ? undefined : json['ort'],
    supplement: json['supplement'] == null ? undefined : json['supplement'],
    fullOpta: json['fullOpta'],
  };
}

export function OptaDtoToJSON(json: any): OptaDto {
  return OptaDtoToJSONTyped(json, false);
}

export function OptaDtoToJSONTyped(value?: OptaDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    district: value['district'],
    bosCode: value['bosCode'],
    localCode: value['localCode'],
    functionCode: value['functionCode'],
    orderNumber: value['orderNumber'],
    ort: value['ort'],
    supplement: value['supplement'],
    fullOpta: value['fullOpta'],
  };
}
