/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PostFlightChecksDto
 */
export interface PostFlightChecksDto {
  /**
   *
   * @type {Date}
   * @memberof PostFlightChecksDto
   */
  landezeitpunkt: Date;
  /**
   *
   * @type {number}
   * @memberof PostFlightChecksDto
   */
  akkuStand: number;
  /**
   *
   * @type {boolean}
   * @memberof PostFlightChecksDto
   */
  schaeden: boolean;
  /**
   *
   * @type {string}
   * @memberof PostFlightChecksDto
   */
  schadensBeschreibung?: string;
  /**
   *
   * @type {string}
   * @memberof PostFlightChecksDto
   */
  einsatzleiterAbnahme: string;
  /**
   *
   * @type {string}
   * @memberof PostFlightChecksDto
   */
  anmerkungen?: string;
}

/**
 * Check if a given object implements the PostFlightChecksDto interface.
 */
export function instanceOfPostFlightChecksDto(value: object): value is PostFlightChecksDto {
  if (!('landezeitpunkt' in value) || value['landezeitpunkt'] === undefined) return false;
  if (!('akkuStand' in value) || value['akkuStand'] === undefined) return false;
  if (!('schaeden' in value) || value['schaeden'] === undefined) return false;
  if (!('einsatzleiterAbnahme' in value) || value['einsatzleiterAbnahme'] === undefined) return false;
  return true;
}

export function PostFlightChecksDtoFromJSON(json: any): PostFlightChecksDto {
  return PostFlightChecksDtoFromJSONTyped(json, false);
}

export function PostFlightChecksDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostFlightChecksDto {
  if (json == null) {
    return json;
  }
  return {
    landezeitpunkt: new Date(json['landezeitpunkt']),
    akkuStand: json['akkuStand'],
    schaeden: json['schaeden'],
    schadensBeschreibung: json['schadensBeschreibung'] == null ? undefined : json['schadensBeschreibung'],
    einsatzleiterAbnahme: json['einsatzleiterAbnahme'],
    anmerkungen: json['anmerkungen'] == null ? undefined : json['anmerkungen'],
  };
}

export function PostFlightChecksDtoToJSON(json: any): PostFlightChecksDto {
  return PostFlightChecksDtoToJSONTyped(json, false);
}

export function PostFlightChecksDtoToJSONTyped(
  value?: PostFlightChecksDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    landezeitpunkt: value['landezeitpunkt'].toISOString(),
    akkuStand: value['akkuStand'],
    schaeden: value['schaeden'],
    schadensBeschreibung: value['schadensBeschreibung'],
    einsatzleiterAbnahme: value['einsatzleiterAbnahme'],
    anmerkungen: value['anmerkungen'],
  };
}
