/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WetterbedingungsDto } from './WetterbedingungsDto';
import {
  WetterbedingungsDtoFromJSON,
  WetterbedingungsDtoFromJSONTyped,
  WetterbedingungsDtoToJSON,
  WetterbedingungsDtoToJSONTyped,
} from './WetterbedingungsDto';
import type { ChecklisteDto } from './ChecklisteDto';
import {
  ChecklisteDtoFromJSON,
  ChecklisteDtoFromJSONTyped,
  ChecklisteDtoToJSON,
  ChecklisteDtoToJSONTyped,
} from './ChecklisteDto';

/**
 *
 * @export
 * @interface PreFlightChecksDto
 */
export interface PreFlightChecksDto {
  /**
   *
   * @type {string}
   * @memberof PreFlightChecksDto
   */
  drohnenmodell: string;
  /**
   *
   * @type {string}
   * @memberof PreFlightChecksDto
   */
  pilot: string;
  /**
   *
   * @type {string}
   * @memberof PreFlightChecksDto
   */
  copilot?: string;
  /**
   *
   * @type {string}
   * @memberof PreFlightChecksDto
   */
  einsatzleiter: string;
  /**
   *
   * @type {WetterbedingungsDto}
   * @memberof PreFlightChecksDto
   */
  wetterbedingungen: WetterbedingungsDto;
  /**
   *
   * @type {ChecklisteDto}
   * @memberof PreFlightChecksDto
   */
  checkliste: ChecklisteDto;
}

/**
 * Check if a given object implements the PreFlightChecksDto interface.
 */
export function instanceOfPreFlightChecksDto(value: object): value is PreFlightChecksDto {
  if (!('drohnenmodell' in value) || value['drohnenmodell'] === undefined) return false;
  if (!('pilot' in value) || value['pilot'] === undefined) return false;
  if (!('einsatzleiter' in value) || value['einsatzleiter'] === undefined) return false;
  if (!('wetterbedingungen' in value) || value['wetterbedingungen'] === undefined) return false;
  if (!('checkliste' in value) || value['checkliste'] === undefined) return false;
  return true;
}

export function PreFlightChecksDtoFromJSON(json: any): PreFlightChecksDto {
  return PreFlightChecksDtoFromJSONTyped(json, false);
}

export function PreFlightChecksDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreFlightChecksDto {
  if (json == null) {
    return json;
  }
  return {
    drohnenmodell: json['drohnenmodell'],
    pilot: json['pilot'],
    copilot: json['copilot'] == null ? undefined : json['copilot'],
    einsatzleiter: json['einsatzleiter'],
    wetterbedingungen: WetterbedingungsDtoFromJSON(json['wetterbedingungen']),
    checkliste: ChecklisteDtoFromJSON(json['checkliste']),
  };
}

export function PreFlightChecksDtoToJSON(json: any): PreFlightChecksDto {
  return PreFlightChecksDtoToJSONTyped(json, false);
}

export function PreFlightChecksDtoToJSONTyped(
  value?: PreFlightChecksDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    drohnenmodell: value['drohnenmodell'],
    pilot: value['pilot'],
    copilot: value['copilot'],
    einsatzleiter: value['einsatzleiter'],
    wetterbedingungen: WetterbedingungsDtoToJSON(value['wetterbedingungen']),
    checkliste: ChecklisteDtoToJSON(value['checkliste']),
  };
}
