/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface QualificationDto
 */
export interface QualificationDto {
  /**
   *
   * @type {string}
   * @memberof QualificationDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof QualificationDto
   */
  label: string;
  /**
   *
   * @type {string}
   * @memberof QualificationDto
   */
  abkuerzung: string;
}

/**
 * Check if a given object implements the QualificationDto interface.
 */
export function instanceOfQualificationDto(value: object): value is QualificationDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('label' in value) || value['label'] === undefined) return false;
  if (!('abkuerzung' in value) || value['abkuerzung'] === undefined) return false;
  return true;
}

export function QualificationDtoFromJSON(json: any): QualificationDto {
  return QualificationDtoFromJSONTyped(json, false);
}

export function QualificationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QualificationDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    label: json['label'],
    abkuerzung: json['abkuerzung'],
  };
}

export function QualificationDtoToJSON(json: any): QualificationDto {
  return QualificationDtoToJSONTyped(json, false);
}

export function QualificationDtoToJSONTyped(
  value?: QualificationDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    label: value['label'],
    abkuerzung: value['abkuerzung'],
  };
}
