/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReminderDto
 */
export interface ReminderDto {
  /**
   *
   * @type {string}
   * @memberof ReminderDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ReminderDto
   */
  timestamp: string;
  /**
   *
   * @type {string}
   * @memberof ReminderDto
   */
  notified: string;
  /**
   *
   * @type {string}
   * @memberof ReminderDto
   */
  read: string;
  /**
   *
   * @type {string}
   * @memberof ReminderDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof ReminderDto
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof ReminderDto
   */
  action: string;
}

/**
 * Check if a given object implements the ReminderDto interface.
 */
export function instanceOfReminderDto(value: object): value is ReminderDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
  if (!('notified' in value) || value['notified'] === undefined) return false;
  if (!('read' in value) || value['read'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('action' in value) || value['action'] === undefined) return false;
  return true;
}

export function ReminderDtoFromJSON(json: any): ReminderDto {
  return ReminderDtoFromJSONTyped(json, false);
}

export function ReminderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReminderDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    timestamp: json['timestamp'],
    notified: json['notified'],
    read: json['read'],
    title: json['title'],
    content: json['content'],
    action: json['action'],
  };
}

export function ReminderDtoToJSON(json: any): ReminderDto {
  return ReminderDtoToJSONTyped(json, false);
}

export function ReminderDtoToJSONTyped(value?: ReminderDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    timestamp: value['timestamp'],
    notified: value['notified'],
    read: value['read'],
    title: value['title'],
    content: value['content'],
    action: value['action'],
  };
}
