/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { BearbeiterDto } from './BearbeiterDto';
import {
  BearbeiterDtoFromJSON,
  BearbeiterDtoFromJSONTyped,
  BearbeiterDtoToJSON,
  BearbeiterDtoToJSONTyped,
} from './BearbeiterDto';

/**
 *
 * @export
 * @interface Response
 */
export interface Response {
  /**
   *
   * @type {ApiMeta}
   * @memberof Response
   */
  meta: ApiMeta;
  /**
   *
   * @type {Array<BearbeiterDto>}
   * @memberof Response
   */
  data: Array<BearbeiterDto>;
}

/**
 * Check if a given object implements the Response interface.
 */
export function instanceOfResponse(value: object): value is Response {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ResponseFromJSON(json: any): Response {
  return ResponseFromJSONTyped(json, false);
}

export function ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Response {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: (json['data'] as Array<any>).map(BearbeiterDtoFromJSON),
  };
}

export function ResponseToJSON(json: any): Response {
  return ResponseToJSONTyped(json, false);
}

export function ResponseToJSONTyped(value?: Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: (value['data'] as Array<any>).map(BearbeiterDtoToJSON),
  };
}
