/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { SecretsDto } from './SecretsDto';
import { SecretsDtoFromJSON, SecretsDtoFromJSONTyped, SecretsDtoToJSON, SecretsDtoToJSONTyped } from './SecretsDto';

/**
 *
 * @export
 * @interface SecretsResponse
 */
export interface SecretsResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof SecretsResponse
   */
  meta: ApiMeta;
  /**
   * The secret
   * @type {SecretsDto}
   * @memberof SecretsResponse
   */
  data: SecretsDto;
}

/**
 * Check if a given object implements the SecretsResponse interface.
 */
export function instanceOfSecretsResponse(value: object): value is SecretsResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function SecretsResponseFromJSON(json: any): SecretsResponse {
  return SecretsResponseFromJSONTyped(json, false);
}

export function SecretsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretsResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: SecretsDtoFromJSON(json['data']),
  };
}

export function SecretsResponseToJSON(json: any): SecretsResponse {
  return SecretsResponseToJSONTyped(json, false);
}

export function SecretsResponseToJSONTyped(value?: SecretsResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: SecretsDtoToJSON(value['data']),
  };
}
