/* tslint:disable */
/* eslint-disable */

/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SecretsDto
 */
export interface SecretsDto {
  /**
   * The key of the secret
   * @type {string}
   * @memberof SecretsDto
   */
  key: string;
  /**
   * The value of the secret
   * @type {string}
   * @memberof SecretsDto
   */
  value?: string | null;
}

/**
 * Check if a given object implements the SecretsDto interface.
 */
export function instanceOfSecretsDto(value: object): value is SecretsDto {
  if (!('key' in value) || value['key'] === undefined) return false;
  return true;
}

export function SecretsDtoFromJSON(json: any): SecretsDto {
  return SecretsDtoFromJSONTyped(json, false);
}

export function SecretsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretsDto {
  if (json == null) {
    return json;
  }
  return {
    key: json['key'],
    value: json['value'] == null ? undefined : json['value'],
  };
}

export function SecretsDtoToJSON(json: any): SecretsDto {
  return SecretsDtoToJSONTyped(json, false);
}

export function SecretsDtoToJSONTyped(value?: SecretsDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    key: value['key'],
    value: value['value'],
  };
}
