/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SettingsDto
 */
export interface SettingsDto {
  /**
   *
   * @type {string}
   * @memberof SettingsDto
   */
  mapboxApi?: string;
}

/**
 * Check if a given object implements the SettingsDto interface.
 */
export function instanceOfSettingsDto(value: object): value is SettingsDto {
  return true;
}

export function SettingsDtoFromJSON(json: any): SettingsDto {
  return SettingsDtoFromJSONTyped(json, false);
}

export function SettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsDto {
  if (json == null) {
    return json;
  }
  return {
    mapboxApi: json['mapboxApi'] == null ? undefined : json['mapboxApi'],
  };
}

export function SettingsDtoToJSON(json: any): SettingsDto {
  return SettingsDtoToJSONTyped(json, false);
}

export function SettingsDtoToJSONTyped(value?: SettingsDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    mapboxApi: value['mapboxApi'],
  };
}
