/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { SettingsDto } from './SettingsDto';
import {
  SettingsDtoFromJSON,
  SettingsDtoFromJSONTyped,
  SettingsDtoToJSON,
  SettingsDtoToJSONTyped,
} from './SettingsDto';

/**
 *
 * @export
 * @interface SettingsResponse
 */
export interface SettingsResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof SettingsResponse
   */
  meta: ApiMeta;
  /**
   * Application settings
   * @type {SettingsDto}
   * @memberof SettingsResponse
   */
  data: SettingsDto;
}

/**
 * Check if a given object implements the SettingsResponse interface.
 */
export function instanceOfSettingsResponse(value: object): value is SettingsResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function SettingsResponseFromJSON(json: any): SettingsResponse {
  return SettingsResponseFromJSONTyped(json, false);
}

export function SettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: SettingsDtoFromJSON(json['data']),
  };
}

export function SettingsResponseToJSON(json: any): SettingsResponse {
  return SettingsResponseToJSONTyped(json, false);
}

export function SettingsResponseToJSONTyped(
  value?: SettingsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: SettingsDtoToJSON(value['data']),
  };
}
