/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BearbeiterWithStatusDto } from './BearbeiterWithStatusDto';
import {
  BearbeiterWithStatusDtoFromJSON,
  BearbeiterWithStatusDtoFromJSONTyped,
  BearbeiterWithStatusDtoToJSON,
  BearbeiterWithStatusDtoToJSONTyped,
} from './BearbeiterWithStatusDto';
import type { EinsatzAlarmstichwortDto } from './EinsatzAlarmstichwortDto';
import {
  EinsatzAlarmstichwortDtoFromJSON,
  EinsatzAlarmstichwortDtoFromJSONTyped,
  EinsatzAlarmstichwortDtoToJSON,
  EinsatzAlarmstichwortDtoToJSONTyped,
} from './EinsatzAlarmstichwortDto';
import type { MissionMetaDto } from './MissionMetaDto';
import {
  MissionMetaDtoFromJSON,
  MissionMetaDtoFromJSONTyped,
  MissionMetaDtoToJSON,
  MissionMetaDtoToJSONTyped,
} from './MissionMetaDto';

/**
 *
 * @export
 * @interface SmallMissionDto
 */
export interface SmallMissionDto {
  /**
   *
   * @type {string}
   * @memberof SmallMissionDto
   */
  id: string;
  /**
   * Backend version of the server that created the mission
   * @type {string}
   * @memberof SmallMissionDto
   */
  backendVersion: string;
  /**
   * Whether the mission is compatible with the backend version
   * @type {boolean}
   * @memberof SmallMissionDto
   */
  backendCompatible: boolean;
  /**
   *
   * @type {string}
   * @memberof SmallMissionDto
   */
  aufnehmendesRettungsmittel: string;
  /**
   *
   * @type {BearbeiterWithStatusDto}
   * @memberof SmallMissionDto
   */
  bearbeiter: BearbeiterWithStatusDto;
  /**
   *
   * @type {string}
   * @memberof SmallMissionDto
   */
  beginn: string;
  /**
   *
   * @type {string}
   * @memberof SmallMissionDto
   */
  ende: string;
  /**
   *
   * @type {EinsatzAlarmstichwortDto}
   * @memberof SmallMissionDto
   */
  einsatzAlarmstichwort: EinsatzAlarmstichwortDto;
  /**
   *
   * @type {MissionMetaDto}
   * @memberof SmallMissionDto
   */
  einsatzMeta: MissionMetaDto;
}

/**
 * Check if a given object implements the SmallMissionDto interface.
 */
export function instanceOfSmallMissionDto(value: object): value is SmallMissionDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('backendVersion' in value) || value['backendVersion'] === undefined) return false;
  if (!('backendCompatible' in value) || value['backendCompatible'] === undefined) return false;
  if (!('aufnehmendesRettungsmittel' in value) || value['aufnehmendesRettungsmittel'] === undefined) return false;
  if (!('bearbeiter' in value) || value['bearbeiter'] === undefined) return false;
  if (!('beginn' in value) || value['beginn'] === undefined) return false;
  if (!('ende' in value) || value['ende'] === undefined) return false;
  if (!('einsatzAlarmstichwort' in value) || value['einsatzAlarmstichwort'] === undefined) return false;
  if (!('einsatzMeta' in value) || value['einsatzMeta'] === undefined) return false;
  return true;
}

export function SmallMissionDtoFromJSON(json: any): SmallMissionDto {
  return SmallMissionDtoFromJSONTyped(json, false);
}

export function SmallMissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmallMissionDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    backendVersion: json['backendVersion'],
    backendCompatible: json['backendCompatible'],
    aufnehmendesRettungsmittel: json['aufnehmendesRettungsmittel'],
    bearbeiter: BearbeiterWithStatusDtoFromJSON(json['bearbeiter']),
    beginn: json['beginn'],
    ende: json['ende'],
    einsatzAlarmstichwort: EinsatzAlarmstichwortDtoFromJSON(json['einsatzAlarmstichwort']),
    einsatzMeta: MissionMetaDtoFromJSON(json['einsatzMeta']),
  };
}

export function SmallMissionDtoToJSON(json: any): SmallMissionDto {
  return SmallMissionDtoToJSONTyped(json, false);
}

export function SmallMissionDtoToJSONTyped(value?: SmallMissionDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    backendVersion: value['backendVersion'],
    backendCompatible: value['backendCompatible'],
    aufnehmendesRettungsmittel: value['aufnehmendesRettungsmittel'],
    bearbeiter: BearbeiterWithStatusDtoToJSON(value['bearbeiter']),
    beginn: value['beginn'],
    ende: value['ende'],
    einsatzAlarmstichwort: EinsatzAlarmstichwortDtoToJSON(value['einsatzAlarmstichwort']),
    einsatzMeta: MissionMetaDtoToJSON(value['einsatzMeta']),
  };
}
