/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StatusDto
 */
export interface StatusDto {
  /**
   *
   * @type {string}
   * @memberof StatusDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof StatusDto
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof StatusDto
   */
  label: string;
  /**
   *
   * @type {string}
   * @memberof StatusDto
   */
  description: string;
}

/**
 * Check if a given object implements the StatusDto interface.
 */
export function instanceOfStatusDto(value: object): value is StatusDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('label' in value) || value['label'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  return true;
}

export function StatusDtoFromJSON(json: any): StatusDto {
  return StatusDtoFromJSONTyped(json, false);
}

export function StatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    code: json['code'],
    label: json['label'],
    description: json['description'],
  };
}

export function StatusDtoToJSON(json: any): StatusDto {
  return StatusDtoToJSONTyped(json, false);
}

export function StatusDtoToJSONTyped(value?: StatusDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    code: value['code'],
    label: value['label'],
    description: value['description'],
  };
}
