/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UAVIconDefinitionDto
 */
export interface UAVIconDefinitionDto {
  /**
   *
   * @type {string}
   * @memberof UAVIconDefinitionDto
   */
  organisation?: string;
  /**
   *
   * @type {string}
   * @memberof UAVIconDefinitionDto
   */
  fachaufgabe?: string;
  /**
   *
   * @type {string}
   * @memberof UAVIconDefinitionDto
   */
  verwaltungsstufe?: string;
}

/**
 * Check if a given object implements the UAVIconDefinitionDto interface.
 */
export function instanceOfUAVIconDefinitionDto(value: object): value is UAVIconDefinitionDto {
  return true;
}

export function UAVIconDefinitionDtoFromJSON(json: any): UAVIconDefinitionDto {
  return UAVIconDefinitionDtoFromJSONTyped(json, false);
}

export function UAVIconDefinitionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UAVIconDefinitionDto {
  if (json == null) {
    return json;
  }
  return {
    organisation: json['organisation'] == null ? undefined : json['organisation'],
    fachaufgabe: json['fachaufgabe'] == null ? undefined : json['fachaufgabe'],
    verwaltungsstufe: json['verwaltungsstufe'] == null ? undefined : json['verwaltungsstufe'],
  };
}

export function UAVIconDefinitionDtoToJSON(json: any): UAVIconDefinitionDto {
  return UAVIconDefinitionDtoToJSONTyped(json, false);
}

export function UAVIconDefinitionDtoToJSONTyped(
  value?: UAVIconDefinitionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    organisation: value['organisation'],
    fachaufgabe: value['fachaufgabe'],
    verwaltungsstufe: value['verwaltungsstufe'],
  };
}
