/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UAVMissionDto } from './UAVMissionDto';
import {
  UAVMissionDtoFromJSON,
  UAVMissionDtoFromJSONTyped,
  UAVMissionDtoToJSON,
  UAVMissionDtoToJSONTyped,
} from './UAVMissionDto';

/**
 *
 * @export
 * @interface UAVMissionsDto
 */
export interface UAVMissionsDto {
  /**
   *
   * @type {Array<UAVMissionDto>}
   * @memberof UAVMissionsDto
   */
  missions: Array<UAVMissionDto>;
}

/**
 * Check if a given object implements the UAVMissionsDto interface.
 */
export function instanceOfUAVMissionsDto(value: object): value is UAVMissionsDto {
  if (!('missions' in value) || value['missions'] === undefined) return false;
  return true;
}

export function UAVMissionsDtoFromJSON(json: any): UAVMissionsDto {
  return UAVMissionsDtoFromJSONTyped(json, false);
}

export function UAVMissionsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UAVMissionsDto {
  if (json == null) {
    return json;
  }
  return {
    missions: (json['missions'] as Array<any>).map(UAVMissionDtoFromJSON),
  };
}

export function UAVMissionsDtoToJSON(json: any): UAVMissionsDto {
  return UAVMissionsDtoToJSONTyped(json, false);
}

export function UAVMissionsDtoToJSONTyped(value?: UAVMissionsDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    missions: (value['missions'] as Array<any>).map(UAVMissionDtoToJSON),
  };
}
