/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { UAVMissionsDto } from './UAVMissionsDto';
import {
  UAVMissionsDtoFromJSON,
  UAVMissionsDtoFromJSONTyped,
  UAVMissionsDtoToJSON,
  UAVMissionsDtoToJSONTyped,
} from './UAVMissionsDto';

/**
 *
 * @export
 * @interface UAVMissionsResponse
 */
export interface UAVMissionsResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof UAVMissionsResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {UAVMissionsDto}
   * @memberof UAVMissionsResponse
   */
  data: UAVMissionsDto;
}

/**
 * Check if a given object implements the UAVMissionsResponse interface.
 */
export function instanceOfUAVMissionsResponse(value: object): value is UAVMissionsResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function UAVMissionsResponseFromJSON(json: any): UAVMissionsResponse {
  return UAVMissionsResponseFromJSONTyped(json, false);
}

export function UAVMissionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UAVMissionsResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: UAVMissionsDtoFromJSON(json['data']),
  };
}

export function UAVMissionsResponseToJSON(json: any): UAVMissionsResponse {
  return UAVMissionsResponseToJSONTyped(json, false);
}

export function UAVMissionsResponseToJSONTyped(
  value?: UAVMissionsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: UAVMissionsDtoToJSON(value['data']),
  };
}
