/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { UAVMissionDto } from './UAVMissionDto';
import {
  UAVMissionDtoFromJSON,
  UAVMissionDtoFromJSONTyped,
  UAVMissionDtoToJSON,
  UAVMissionDtoToJSONTyped,
} from './UAVMissionDto';

/**
 *
 * @export
 * @interface UAVMissionResponse
 */
export interface UAVMissionResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof UAVMissionResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {UAVMissionDto}
   * @memberof UAVMissionResponse
   */
  data: UAVMissionDto;
}

/**
 * Check if a given object implements the UAVMissionResponse interface.
 */
export function instanceOfUAVMissionResponse(value: object): value is UAVMissionResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function UAVMissionResponseFromJSON(json: any): UAVMissionResponse {
  return UAVMissionResponseFromJSONTyped(json, false);
}

export function UAVMissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UAVMissionResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: UAVMissionDtoFromJSON(json['data']),
  };
}

export function UAVMissionResponseToJSON(json: any): UAVMissionResponse {
  return UAVMissionResponseToJSONTyped(json, false);
}

export function UAVMissionResponseToJSONTyped(
  value?: UAVMissionResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: UAVMissionDtoToJSON(value['data']),
  };
}
