/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PreFlightChecksDto } from './PreFlightChecksDto';
import {
  PreFlightChecksDtoFromJSON,
  PreFlightChecksDtoFromJSONTyped,
  PreFlightChecksDtoToJSON,
  PreFlightChecksDtoToJSONTyped,
} from './PreFlightChecksDto';
import type { UAVTemplateDto } from './UAVTemplateDto';
import {
  UAVTemplateDtoFromJSON,
  UAVTemplateDtoFromJSONTyped,
  UAVTemplateDtoToJSON,
  UAVTemplateDtoToJSONTyped,
} from './UAVTemplateDto';
import type { FlightProtocolDto } from './FlightProtocolDto';
import {
  FlightProtocolDtoFromJSON,
  FlightProtocolDtoFromJSONTyped,
  FlightProtocolDtoToJSON,
  FlightProtocolDtoToJSONTyped,
} from './FlightProtocolDto';
import type { PostFlightChecksDto } from './PostFlightChecksDto';
import {
  PostFlightChecksDtoFromJSON,
  PostFlightChecksDtoFromJSONTyped,
  PostFlightChecksDtoToJSON,
  PostFlightChecksDtoToJSONTyped,
} from './PostFlightChecksDto';

/**
 *
 * @export
 * @interface UAVMissionDto
 */
export interface UAVMissionDto {
  /**
   *
   * @type {number}
   * @memberof UAVMissionDto
   */
  index: number;
  /**
   *
   * @type {UAVTemplateDto}
   * @memberof UAVMissionDto
   */
  uav: UAVTemplateDto;
  /**
   *
   * @type {PreFlightChecksDto}
   * @memberof UAVMissionDto
   */
  preFlightChecks?: PreFlightChecksDto;
  /**
   *
   * @type {Array<FlightProtocolDto>}
   * @memberof UAVMissionDto
   */
  flightProtocols: Array<FlightProtocolDto>;
  /**
   *
   * @type {PostFlightChecksDto}
   * @memberof UAVMissionDto
   */
  postFlightChecks?: PostFlightChecksDto;
  /**
   *
   * @type {string}
   * @memberof UAVMissionDto
   */
  status: UAVMissionDtoStatusEnum;
}

/**
 * @export
 */
export const UAVMissionDtoStatusEnum = {
  PreflightChecks: 'PREFLIGHT_CHECKS',
  Active: 'ACTIVE',
  PostflightChecks: 'POSTFLIGHT_CHECKS',
  Completed: 'COMPLETED',
} as const;
export type UAVMissionDtoStatusEnum = (typeof UAVMissionDtoStatusEnum)[keyof typeof UAVMissionDtoStatusEnum];

/**
 * Check if a given object implements the UAVMissionDto interface.
 */
export function instanceOfUAVMissionDto(value: object): value is UAVMissionDto {
  if (!('index' in value) || value['index'] === undefined) return false;
  if (!('uav' in value) || value['uav'] === undefined) return false;
  if (!('flightProtocols' in value) || value['flightProtocols'] === undefined) return false;
  if (!('status' in value) || value['status'] === undefined) return false;
  return true;
}

export function UAVMissionDtoFromJSON(json: any): UAVMissionDto {
  return UAVMissionDtoFromJSONTyped(json, false);
}

export function UAVMissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UAVMissionDto {
  if (json == null) {
    return json;
  }
  return {
    index: json['index'],
    uav: UAVTemplateDtoFromJSON(json['uav']),
    preFlightChecks: json['preFlightChecks'] == null ? undefined : PreFlightChecksDtoFromJSON(json['preFlightChecks']),
    flightProtocols: (json['flightProtocols'] as Array<any>).map(FlightProtocolDtoFromJSON),
    postFlightChecks:
      json['postFlightChecks'] == null ? undefined : PostFlightChecksDtoFromJSON(json['postFlightChecks']),
    status: json['status'],
  };
}

export function UAVMissionDtoToJSON(json: any): UAVMissionDto {
  return UAVMissionDtoToJSONTyped(json, false);
}

export function UAVMissionDtoToJSONTyped(value?: UAVMissionDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    index: value['index'],
    uav: UAVTemplateDtoToJSON(value['uav']),
    preFlightChecks: PreFlightChecksDtoToJSON(value['preFlightChecks']),
    flightProtocols: (value['flightProtocols'] as Array<any>).map(FlightProtocolDtoToJSON),
    postFlightChecks: PostFlightChecksDtoToJSON(value['postFlightChecks']),
    status: value['status'],
  };
}
