/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UAVTemplateDto
 */
export interface UAVTemplateDto {
  /**
   *
   * @type {string}
   * @memberof UAVTemplateDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof UAVTemplateDto
   */
  modell: string;
  /**
   *
   * @type {string}
   * @memberof UAVTemplateDto
   */
  seriennummer: string;
  /**
   *
   * @type {string}
   * @memberof UAVTemplateDto
   */
  konfiguration: string;
  /**
   *
   * @type {string}
   * @memberof UAVTemplateDto
   */
  nutzlast: string;
  /**
   *
   * @type {string}
   * @memberof UAVTemplateDto
   */
  firmware?: string;
  /**
   *
   * @type {number}
   * @memberof UAVTemplateDto
   */
  maxFlugzeit?: number;
  /**
   *
   * @type {number}
   * @memberof UAVTemplateDto
   */
  maxFlughoehe?: number;
  /**
   *
   * @type {number}
   * @memberof UAVTemplateDto
   */
  maxGeschwindigkeit?: number;
  /**
   *
   * @type {number}
   * @memberof UAVTemplateDto
   */
  gewicht?: number;
}

/**
 * Check if a given object implements the UAVTemplateDto interface.
 */
export function instanceOfUAVTemplateDto(value: object): value is UAVTemplateDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('modell' in value) || value['modell'] === undefined) return false;
  if (!('seriennummer' in value) || value['seriennummer'] === undefined) return false;
  if (!('konfiguration' in value) || value['konfiguration'] === undefined) return false;
  if (!('nutzlast' in value) || value['nutzlast'] === undefined) return false;
  return true;
}

export function UAVTemplateDtoFromJSON(json: any): UAVTemplateDto {
  return UAVTemplateDtoFromJSONTyped(json, false);
}

export function UAVTemplateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UAVTemplateDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['_id'],
    modell: json['modell'],
    seriennummer: json['seriennummer'],
    konfiguration: json['konfiguration'],
    nutzlast: json['nutzlast'],
    firmware: json['firmware'] == null ? undefined : json['firmware'],
    maxFlugzeit: json['maxFlugzeit'] == null ? undefined : json['maxFlugzeit'],
    maxFlughoehe: json['maxFlughoehe'] == null ? undefined : json['maxFlughoehe'],
    maxGeschwindigkeit: json['maxGeschwindigkeit'] == null ? undefined : json['maxGeschwindigkeit'],
    gewicht: json['gewicht'] == null ? undefined : json['gewicht'],
  };
}

export function UAVTemplateDtoToJSON(json: any): UAVTemplateDto {
  return UAVTemplateDtoToJSONTyped(json, false);
}

export function UAVTemplateDtoToJSONTyped(value?: UAVTemplateDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    _id: value['id'],
    modell: value['modell'],
    seriennummer: value['seriennummer'],
    konfiguration: value['konfiguration'],
    nutzlast: value['nutzlast'],
    firmware: value['firmware'],
    maxFlugzeit: value['maxFlugzeit'],
    maxFlughoehe: value['maxFlughoehe'],
    maxGeschwindigkeit: value['maxGeschwindigkeit'],
    gewicht: value['gewicht'],
  };
}
