/* tslint:disable */
/* eslint-disable */
/**
 * Project Rescue Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateMissionDto
 */
export interface UpdateMissionDto {
  /**
   *
   * @type {string}
   * @memberof UpdateMissionDto
   */
  alarmstichwort: string;
  /**
   *
   * @type {string}
   * @memberof UpdateMissionDto
   */
  ort: string;
  /**
   * Start and end times in ISO format
   * @type {Array<string>}
   * @memberof UpdateMissionDto
   */
  timeframe: Array<string>;
}

/**
 * Check if a given object implements the UpdateMissionDto interface.
 */
export function instanceOfUpdateMissionDto(value: object): value is UpdateMissionDto {
  if (!('alarmstichwort' in value) || value['alarmstichwort'] === undefined) return false;
  if (!('ort' in value) || value['ort'] === undefined) return false;
  if (!('timeframe' in value) || value['timeframe'] === undefined) return false;
  return true;
}

export function UpdateMissionDtoFromJSON(json: any): UpdateMissionDto {
  return UpdateMissionDtoFromJSONTyped(json, false);
}

export function UpdateMissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMissionDto {
  if (json == null) {
    return json;
  }
  return {
    alarmstichwort: json['alarmstichwort'],
    ort: json['ort'],
    timeframe: json['timeframe'],
  };
}

export function UpdateMissionDtoToJSON(json: any): UpdateMissionDto {
  return UpdateMissionDtoToJSONTyped(json, false);
}

export function UpdateMissionDtoToJSONTyped(
  value?: UpdateMissionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    alarmstichwort: value['alarmstichwort'],
    ort: value['ort'],
    timeframe: value['timeframe'],
  };
}
