/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface VehicleOnMissionDto
 */
export interface VehicleOnMissionDto {
  /**
   *
   * @type {string}
   * @memberof VehicleOnMissionDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof VehicleOnMissionDto
   */
  fullOpta: string;
  /**
   *
   * @type {string}
   * @memberof VehicleOnMissionDto
   */
  optaFunktion: string;
  /**
   *
   * @type {string}
   * @memberof VehicleOnMissionDto
   */
  einsatzbeginn: string;
  /**
   *
   * @type {Date}
   * @memberof VehicleOnMissionDto
   */
  einsatzende: Date;
  /**
   *
   * @type {Array<string>}
   * @memberof VehicleOnMissionDto
   */
  personal: Array<string>;
  /**
   *
   * @type {number}
   * @memberof VehicleOnMissionDto
   */
  kapazitaet: number;
  /**
   *
   * @type {Array<string>}
   * @memberof VehicleOnMissionDto
   */
  statusHistory: Array<string>;
}

/**
 * Check if a given object implements the VehicleOnMissionDto interface.
 */
export function instanceOfVehicleOnMissionDto(value: object): value is VehicleOnMissionDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('fullOpta' in value) || value['fullOpta'] === undefined) return false;
  if (!('optaFunktion' in value) || value['optaFunktion'] === undefined) return false;
  if (!('einsatzbeginn' in value) || value['einsatzbeginn'] === undefined) return false;
  if (!('einsatzende' in value) || value['einsatzende'] === undefined) return false;
  if (!('personal' in value) || value['personal'] === undefined) return false;
  if (!('kapazitaet' in value) || value['kapazitaet'] === undefined) return false;
  if (!('statusHistory' in value) || value['statusHistory'] === undefined) return false;
  return true;
}

export function VehicleOnMissionDtoFromJSON(json: any): VehicleOnMissionDto {
  return VehicleOnMissionDtoFromJSONTyped(json, false);
}

export function VehicleOnMissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleOnMissionDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    fullOpta: json['fullOpta'],
    optaFunktion: json['optaFunktion'],
    einsatzbeginn: json['einsatzbeginn'],
    einsatzende: new Date(json['einsatzende']),
    personal: json['personal'],
    kapazitaet: json['kapazitaet'],
    statusHistory: json['status_history'],
  };
}

export function VehicleOnMissionDtoToJSON(json: any): VehicleOnMissionDto {
  return VehicleOnMissionDtoToJSONTyped(json, false);
}

export function VehicleOnMissionDtoToJSONTyped(
  value?: VehicleOnMissionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    fullOpta: value['fullOpta'],
    optaFunktion: value['optaFunktion'],
    einsatzbeginn: value['einsatzbeginn'],
    einsatzende: value['einsatzende'].toISOString(),
    personal: value['personal'],
    kapazitaet: value['kapazitaet'],
    status_history: value['statusHistory'],
  };
}
