/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleOnMissionDto } from './VehicleOnMissionDto';
import {
  VehicleOnMissionDtoFromJSON,
  VehicleOnMissionDtoFromJSONTyped,
  VehicleOnMissionDtoToJSON,
  VehicleOnMissionDtoToJSONTyped,
} from './VehicleOnMissionDto';

/**
 *
 * @export
 * @interface VehiclesDto
 */
export interface VehiclesDto {
  /**
   *
   * @type {Array<VehicleOnMissionDto>}
   * @memberof VehiclesDto
   */
  fahrzeugeImEinsatz: Array<VehicleOnMissionDto>;
  /**
   *
   * @type {Array<VehicleOnMissionDto>}
   * @memberof VehiclesDto
   */
  verfuegbareFahrzeuge: Array<VehicleOnMissionDto>;
}

/**
 * Check if a given object implements the VehiclesDto interface.
 */
export function instanceOfVehiclesDto(value: object): value is VehiclesDto {
  if (!('fahrzeugeImEinsatz' in value) || value['fahrzeugeImEinsatz'] === undefined) return false;
  if (!('verfuegbareFahrzeuge' in value) || value['verfuegbareFahrzeuge'] === undefined) return false;
  return true;
}

export function VehiclesDtoFromJSON(json: any): VehiclesDto {
  return VehiclesDtoFromJSONTyped(json, false);
}

export function VehiclesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehiclesDto {
  if (json == null) {
    return json;
  }
  return {
    fahrzeugeImEinsatz: (json['fahrzeugeImEinsatz'] as Array<any>).map(VehicleOnMissionDtoFromJSON),
    verfuegbareFahrzeuge: (json['verfuegbareFahrzeuge'] as Array<any>).map(VehicleOnMissionDtoFromJSON),
  };
}

export function VehiclesDtoToJSON(json: any): VehiclesDto {
  return VehiclesDtoToJSONTyped(json, false);
}

export function VehiclesDtoToJSONTyped(value?: VehiclesDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    fahrzeugeImEinsatz: (value['fahrzeugeImEinsatz'] as Array<any>).map(VehicleOnMissionDtoToJSON),
    verfuegbareFahrzeuge: (value['verfuegbareFahrzeuge'] as Array<any>).map(VehicleOnMissionDtoToJSON),
  };
}
