/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMeta } from './ApiMeta';
import { ApiMetaFromJSON, ApiMetaFromJSONTyped, ApiMetaToJSON, ApiMetaToJSONTyped } from './ApiMeta';
import type { VehiclesDto } from './VehiclesDto';
import {
  VehiclesDtoFromJSON,
  VehiclesDtoFromJSONTyped,
  VehiclesDtoToJSON,
  VehiclesDtoToJSONTyped,
} from './VehiclesDto';

/**
 *
 * @export
 * @interface VehiclesResponse
 */
export interface VehiclesResponse {
  /**
   *
   * @type {ApiMeta}
   * @memberof VehiclesResponse
   */
  meta: ApiMeta;
  /**
   *
   * @type {VehiclesDto}
   * @memberof VehiclesResponse
   */
  data: VehiclesDto;
}

/**
 * Check if a given object implements the VehiclesResponse interface.
 */
export function instanceOfVehiclesResponse(value: object): value is VehiclesResponse {
  if (!('meta' in value) || value['meta'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function VehiclesResponseFromJSON(json: any): VehiclesResponse {
  return VehiclesResponseFromJSONTyped(json, false);
}

export function VehiclesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehiclesResponse {
  if (json == null) {
    return json;
  }
  return {
    meta: ApiMetaFromJSON(json['meta']),
    data: VehiclesDtoFromJSON(json['data']),
  };
}

export function VehiclesResponseToJSON(json: any): VehiclesResponse {
  return VehiclesResponseToJSONTyped(json, false);
}

export function VehiclesResponseToJSONTyped(
  value?: VehiclesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    meta: ApiMetaToJSON(value['meta']),
    data: VehiclesDtoToJSON(value['data']),
  };
}
