/* tslint:disable */
/* eslint-disable */
/**
 * Bluelight Hub Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: development
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface WetterbedingungsDto
 */
export interface WetterbedingungsDto {
  /**
   *
   * @type {number}
   * @memberof WetterbedingungsDto
   */
  temperatur: number;
  /**
   *
   * @type {number}
   * @memberof WetterbedingungsDto
   */
  windgeschwindigkeit: number;
  /**
   *
   * @type {boolean}
   * @memberof WetterbedingungsDto
   */
  niederschlag: boolean;
  /**
   *
   * @type {number}
   * @memberof WetterbedingungsDto
   */
  sicht: number;
}

/**
 * Check if a given object implements the WetterbedingungsDto interface.
 */
export function instanceOfWetterbedingungsDto(value: object): value is WetterbedingungsDto {
  if (!('temperatur' in value) || value['temperatur'] === undefined) return false;
  if (!('windgeschwindigkeit' in value) || value['windgeschwindigkeit'] === undefined) return false;
  if (!('niederschlag' in value) || value['niederschlag'] === undefined) return false;
  if (!('sicht' in value) || value['sicht'] === undefined) return false;
  return true;
}

export function WetterbedingungsDtoFromJSON(json: any): WetterbedingungsDto {
  return WetterbedingungsDtoFromJSONTyped(json, false);
}

export function WetterbedingungsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WetterbedingungsDto {
  if (json == null) {
    return json;
  }
  return {
    temperatur: json['temperatur'],
    windgeschwindigkeit: json['windgeschwindigkeit'],
    niederschlag: json['niederschlag'],
    sicht: json['sicht'],
  };
}

export function WetterbedingungsDtoToJSON(json: any): WetterbedingungsDto {
  return WetterbedingungsDtoToJSONTyped(json, false);
}

export function WetterbedingungsDtoToJSONTyped(
  value?: WetterbedingungsDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    temperatur: value['temperatur'],
    windgeschwindigkeit: value['windgeschwindigkeit'],
    niederschlag: value['niederschlag'],
    sicht: value['sicht'],
  };
}
