name: Test and Coverage

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20 ]  # Specify the Node.js versions you want to test against

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: backend
        run: pnpm install

      - name: Run tests and generate coverage
        working-directory: backend
        run: pnpm run test:cov